const { Router } = require('express');
const { authenticate } = require('../../common/middlewares/authenticate.js');
const { tenantScope } = require('../../common/middlewares/tenant-scope.js');
const { authorize } = require('../../common/middlewares/authorize.js');
const controller = require('./sach.controller.js');
const router = Router();
const loaiLienKet = ':loai(ten-khac|tac-gia|the-loai|tu-khoa|bo-sach|lien-quan|phan-loai)';
router.use(authenticate, tenantScope);
router.get('/', authorize('books.read'), controller.danhSach);
router.post('/', authorize('books.create'), controller.taoSach);
router.get('/:sachId', authorize('books.read'), controller.chiTiet);
router.patch('/:sachId', authorize('books.create'), controller.suaSach);
router.patch('/:sachId/trang-thai', authorize('books.create'), controller.doiTrangThai);
router.delete('/:sachId', authorize('books.create'), controller.xoaSach);
router.post('/:sachId/khoi-phuc', authorize('books.create'), controller.khoiPhuc);
router.get('/:sachId/anh', authorize('books.read'), controller.danhSachAnh);
router.post('/:sachId/anh', authorize('books.create'), controller.themNhieuAnh);
router.patch('/:sachId/anh/sap-xep', authorize('books.create'), controller.sapXepAnh);
router.patch('/:sachId/anh/:anhId', authorize('books.create'), controller.suaAnh);
router.patch('/:sachId/anh/:anhId/anh-chinh', authorize('books.create'), controller.datAnhChinh);
router.delete('/:sachId/anh/:anhId', authorize('books.create'), controller.xoaAnh);
router.get('/:sachId/:loai', authorize('books.read'), controller.danhSachLienKet);
router.post('/:sachId/:loai', authorize('books.create'), controller.taoLienKet);
router.patch('/:sachId/:loai/:lienKetId', authorize('books.create'), controller.suaLienKet);
router.delete('/:sachId/:loai/:lienKetId', authorize('books.create'), controller.xoaLienKet);
module.exports = router;