const { Router } = require('express');
const { authenticate } = require('../../common/middlewares/authenticate.js');
const { tenantScope } = require('../../common/middlewares/tenant-scope.js');
const { authorize } = require('../../common/middlewares/authorize.js');
const controller = require('./nhap-kho.controller.js');
const router = Router();
router.use(authenticate, tenantScope);
router.get('/', authorize('books.read'), controller.xuLy('danhSach'));
router.post('/', authorize('books.create'), controller.xuLy('tao', 201));
router.get('/:phieuId', authorize('books.read'), controller.xuLy('chiTiet'));
router.patch('/:phieuId', authorize('books.create'), controller.xuLy('sua'));
router.post('/:phieuId/chi-tiet', authorize('books.create'), controller.xuLy('themDong', 201));
router.patch('/:phieuId/chi-tiet/:dongId', authorize('books.create'), controller.xuLy('suaDong'));
router.delete('/:phieuId/chi-tiet/:dongId', authorize('books.create'), controller.xuLy('xoaDong'));
router.post('/:phieuId/bat-dau-kiem-nhan', authorize('books.create'), controller.xuLy('batDauKiemNhan'));
router.patch('/:phieuId/chi-tiet/:dongId/kiem-nhan', authorize('books.create'), controller.xuLy('kiemNhan'));
router.post('/:phieuId/xac-nhan', authorize('books.create'), controller.xuLy('xacNhan'));
router.post('/:phieuId/huy', authorize('books.create'), controller.xuLy('huy'));
module.exports = router;