const { Router } = require('express');
const { authenticate } = require('../../common/middlewares/authenticate.js');
const { tenantScope } = require('../../common/middlewares/tenant-scope.js');
const { authorize } = require('../../common/middlewares/authorize.js');
const c = require('./thanh-toan.controller.js');
const router = Router();
router.post('/qr/webhook/:nhaCungCap',c.webhookQR);
router.use(authenticate,tenantScope);
router.get('/phuong-thuc',authorize('payments.read'),c.xuLy('danhSachPhuongThuc'));
router.post('/phuong-thuc',authorize('payments.manage'),c.xuLy('taoPhuongThuc',201));
router.patch('/phuong-thuc/:id',authorize('payments.manage'),c.xuLy('suaPhuongThuc'));
router.get('/tai-khoan-nhan',authorize('payments.read'),c.xuLy('danhSachTaiKhoan'));
router.post('/tai-khoan-nhan',authorize('payments.manage'),c.xuLy('taoTaiKhoan',201));
router.patch('/tai-khoan-nhan/:id',authorize('payments.manage'),c.xuLy('suaTaiKhoan'));
router.get('/giao-dich',authorize('payments.read'),c.xuLy('danhSachGiaoDich'));
router.post('/giao-dich/thu',authorize('payments.collect'),c.xuLy('taoGiaoDich',201));
router.post('/giao-dich/chi',authorize('payments.disburse'),c.xuLy('taoGiaoDich',201));
router.get('/giao-dich/:id',authorize('payments.read'),c.xuLy('chiTietGiaoDich'));
router.post('/giao-dich/:id/xac-nhan',authorize('payments.confirm'),c.xuLy('xacNhanGiaoDich'));
router.get('/hoan-tien',authorize('payments.refund'),c.xuLy('danhSachHoan'));
router.post('/hoan-tien',authorize('payments.refund'),c.xuLy('taoYeuCauHoan',201));
router.post('/hoan-tien/:id/duyet',authorize('payments.refund.approve'),c.xuLy('duyetHoan'));
router.get('/doi-soat',authorize('payments.reconcile'),c.xuLy('danhSachDot'));
router.post('/doi-soat',authorize('payments.reconcile'),c.xuLy('taoDotDoiSoat',201));
router.get('/doi-soat/:id',authorize('payments.reconcile'),c.xuLy('chiTietDot'));
router.post('/doi-soat/:id/xu-ly',authorize('payments.reconcile'),c.xuLy('xuLyDoiSoat'));
router.post('/doi-soat/:id/chot',authorize('payments.reconcile'),c.xuLy('chotDot'));
module.exports = router;