const { Router } = require('express');
const { authenticate } = require('../../common/middlewares/authenticate.js');
const { tenantScope } = require('../../common/middlewares/tenant-scope.js');
const { authorize } = require('../../common/middlewares/authorize.js');
const controller = require('./ban-hang.controller.js');
const router = Router();
router.use(authenticate,tenantScope);
router.get('/ca',authorize('sales.read'),controller.xuLy('danhSachCa'));
router.post('/ca',authorize('sales.manage'),controller.xuLy('moCa',201));
router.get('/ca/:caId',authorize('sales.read'),controller.xuLy('chiTietCa'));
router.post('/ca/:caId/dong',authorize('sales.manage'),controller.xuLy('dongCa'));
router.post('/ca/:caId/duyet',authorize('sales.manage'),controller.xuLy('duyetCa'));
router.get('/phien',authorize('sales.read'),controller.xuLy('danhSachPhien'));
router.post('/phien',authorize('sales.manage'),controller.xuLy('taoPhien',201));
router.get('/phien/:phienId',authorize('sales.read'),controller.xuLy('chiTietPhien'));
router.post('/phien/:phienId/huy',authorize('sales.manage'),controller.xuLy('huyPhien'));
router.post('/phien/:phienId/chot',authorize('sales.manage'),controller.xuLy('chotPhien'));
router.post('/thanh-toan/tien-mat',authorize('sales.manage'),controller.xuLy('thuTienMat',201));
module.exports = router;