-- F09: Quan ly file dung chung.
-- Yeu cau cac migration 001-013 da chuyen ID nghiep vu sang INTEGER.

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND (table_name, column_name) IN (
              ('don_vi', 'id'),
              ('tai_khoan', 'id'),
              ('don_vi', 'logo_tep_id'),
              ('tai_khoan', 'anh_dai_dien_tep_id')
          )
          AND data_type <> 'integer'
    ) THEN
        RAISE EXCEPTION
            'Chua chuyen tat ca ID nghiep vu 001-013 sang INTEGER';
    END IF;
END;
$$;

CREATE TABLE tep_dinh_kem (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),

    don_vi_so_huu_id INTEGER REFERENCES don_vi(id),
    tai_khoan_so_huu_id INTEGER REFERENCES tai_khoan(id),
    nguoi_tai_len_id INTEGER REFERENCES tai_khoan(id),

    ma_tep VARCHAR(100) NOT NULL UNIQUE,
    ten_tep_goc VARCHAR(300) NOT NULL,
    ten_tep_luu VARCHAR(300) NOT NULL,
    duong_dan_luu_tru TEXT NOT NULL,
    bucket VARCHAR(120) NOT NULL,

    mime_type_khai_bao VARCHAR(160),
    mime_type_xac_minh VARCHAR(160) NOT NULL,
    duoi_tep VARCHAR(30),
    kich_thuoc_byte BIGINT NOT NULL
        CHECK (kich_thuoc_byte >= 0),
    ma_bam_sha256 CHAR(64) NOT NULL
        CHECK (btrim(ma_bam_sha256) ~ '^[0-9a-f]{64}$'),

    loai_tep VARCHAR(40) NOT NULL,
    pham_vi_truy_cap VARCHAR(24) NOT NULL DEFAULT 'RIENG_TU'
        CHECK (
            pham_vi_truy_cap IN (
                'RIENG_TU',
                'NOI_BO_DON_VI',
                'CONG_KHAI'
            )
        ),

    trang_thai_quet_virus VARCHAR(24) NOT NULL DEFAULT 'CHO_QUET'
        CHECK (
            trang_thai_quet_virus IN (
                'CHO_QUET',
                'SACH',
                'NGHI_NGO',
                'BI_CHAN'
            )
        ),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'TAM'
        CHECK (
            trang_thai IN (
                'TAM',
                'DANG_XU_LY',
                'SAN_SANG',
                'CACH_LY',
                'DA_XOA'
            )
        ),

    chieu_rong_px INTEGER CHECK (chieu_rong_px > 0),
    chieu_cao_px INTEGER CHECK (chieu_cao_px > 0),
    thoi_luong_giay NUMERIC(12,3)
        CHECK (thoi_luong_giay >= 0),
    so_trang INTEGER CHECK (so_trang > 0),
    metadata_ky_thuat JSONB NOT NULL DEFAULT '{}'::jsonb,

    nguon_tep VARCHAR(30) NOT NULL DEFAULT 'UPLOAD'
        CHECK (
            nguon_tep IN (
                'UPLOAD',
                'IMPORT',
                'HE_THONG'
            )
        ),

    ngay_het_han TIMESTAMPTZ,
    ngay_xoa TIMESTAMPTZ,
    ly_do_xoa TEXT,

    CONSTRAINT ck_tep_co_chu_so_huu CHECK (
        don_vi_so_huu_id IS NOT NULL
        OR tai_khoan_so_huu_id IS NOT NULL
        OR nguon_tep = 'HE_THONG'
    ),

    CONSTRAINT uq_tep_noi_luu
        UNIQUE (bucket, duong_dan_luu_tru),

    CONSTRAINT uq_tep_don_vi_id
        UNIQUE (don_vi_so_huu_id, id)
);

CREATE INDEX idx_tep_don_vi
ON tep_dinh_kem (
    don_vi_so_huu_id,
    trang_thai,
    ngay_tao DESC
);

CREATE INDEX idx_tep_tai_khoan
ON tep_dinh_kem (
    tai_khoan_so_huu_id,
    ngay_tao DESC
);

CREATE INDEX idx_tep_checksum
ON tep_dinh_kem (
    ma_bam_sha256,
    kich_thuoc_byte
);

-- Hai cot nay da duoc de cho tu migration nen tang.
ALTER TABLE don_vi
ADD CONSTRAINT fk_don_vi_logo_tep
FOREIGN KEY (logo_tep_id)
REFERENCES tep_dinh_kem(id);

ALTER TABLE tai_khoan
ADD CONSTRAINT fk_tai_khoan_anh_dai_dien_tep
FOREIGN KEY (anh_dai_dien_tep_id)
REFERENCES tep_dinh_kem(id);


-- Anh dai dien ca nhan co the khong thuoc don vi.
CREATE TABLE bien_the_tep (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    tep_goc_id INTEGER NOT NULL REFERENCES tep_dinh_kem(id),
    ma_bien_the VARCHAR(40) NOT NULL,
    bucket VARCHAR(120) NOT NULL,
    duong_dan_luu_tru TEXT NOT NULL,
    mime_type VARCHAR(160) NOT NULL,

    kich_thuoc_byte BIGINT NOT NULL
        CHECK (kich_thuoc_byte >= 0),
    chieu_rong_px INTEGER CHECK (chieu_rong_px > 0),
    chieu_cao_px INTEGER CHECK (chieu_cao_px > 0),
    ma_bam_sha256 CHAR(64) NOT NULL
        CHECK (btrim(ma_bam_sha256) ~ '^[0-9a-f]{64}$'),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_XU_LY'
        CHECK (
            trang_thai IN (
                'DANG_XU_LY',
                'SAN_SANG',
                'THAT_BAI',
                'DA_XOA'
            )
        ),

    ngay_xu_ly TIMESTAMPTZ,
    loi_xu_ly TEXT,

    CONSTRAINT uq_bien_the_tep
        UNIQUE (tep_goc_id, ma_bien_the),

    CONSTRAINT uq_bien_the_noi_luu
        UNIQUE (bucket, duong_dan_luu_tru)
);

CREATE INDEX idx_bien_the_tep_goc
ON bien_the_tep (
    tep_goc_id,
    trang_thai
);


CREATE TABLE lo_tai_tep (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    ma_lo VARCHAR(100) NOT NULL UNIQUE,
    nguoi_tai_len_id INTEGER NOT NULL REFERENCES tai_khoan(id),

    tong_so_tep INTEGER NOT NULL
        CHECK (tong_so_tep > 0),

    so_tep_thanh_cong INTEGER NOT NULL DEFAULT 0
        CHECK (so_tep_thanh_cong >= 0),

    so_tep_that_bai INTEGER NOT NULL DEFAULT 0
        CHECK (so_tep_that_bai >= 0),

    tong_dung_luong_byte BIGINT NOT NULL DEFAULT 0
        CHECK (tong_dung_luong_byte >= 0),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_TAI'
        CHECK (
            trang_thai IN (
                'DANG_TAI',
                'HOAN_TAT',
                'HOAN_TAT_MOT_PHAN',
                'THAT_BAI',
                'DA_HUY'
            )
        ),

    ngay_bat_dau TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_hoan_tat TIMESTAMPTZ,

    CONSTRAINT ck_lo_tai_dem CHECK (
        so_tep_thanh_cong + so_tep_that_bai <= tong_so_tep
    ),

    CONSTRAINT uq_lo_tai_tenant_id
        UNIQUE (don_vi_id, id)
);

CREATE INDEX idx_lo_tai_nguoi
ON lo_tai_tep (
    nguoi_tai_len_id,
    ngay_tao DESC
);


CREATE TABLE chi_tiet_lo_tai_tep (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    lo_tai_tep_id INTEGER NOT NULL REFERENCES lo_tai_tep(id),
    tep_dinh_kem_id INTEGER REFERENCES tep_dinh_kem(id),
    ten_tep_goc VARCHAR(300) NOT NULL,
    thu_tu INTEGER NOT NULL CHECK (thu_tu >= 0),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'CHO_TAI'
        CHECK (
            trang_thai IN (
                'CHO_TAI',
                'THANH_CONG',
                'THAT_BAI',
                'DA_HUY'
            )
        ),

    ma_loi VARCHAR(60),
    thong_bao_loi TEXT,

    CONSTRAINT uq_chi_tiet_lo_thu_tu
        UNIQUE (lo_tai_tep_id, thu_tu)
);

CREATE INDEX idx_chi_tiet_lo_file
ON chi_tiet_lo_tai_tep (tep_dinh_kem_id)
WHERE tep_dinh_kem_id IS NOT NULL;


DO $$
DECLARE
    ten_bang TEXT;
BEGIN
    FOREACH ten_bang IN ARRAY ARRAY[
        'tep_dinh_kem',
        'bien_the_tep',
        'lo_tai_tep',
        'chi_tiet_lo_tai_tep'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I
             BEFORE UPDATE ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || ten_bang || '_ngay_cap_nhat',
            ten_bang
        );
    END LOOP;
END;
$$;