CREATE TABLE vi_tri_cong_viec (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    ma_vi_tri VARCHAR(40) NOT NULL,
    ten_vi_tri VARCHAR(160) NOT NULL,
    mo_ta TEXT,
    nhom_vi_tri VARCHAR(60),
    cap_bac SMALLINT CHECK (cap_bac >= 0),
    yeu_cau_nghiep_vu TEXT,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_NGUNG',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT uq_vi_tri_ma
        UNIQUE (don_vi_id, ma_vi_tri),

    CONSTRAINT uq_vi_tri_tenant_id
        UNIQUE (don_vi_id, id)
);


CREATE TABLE ho_so_nhan_vien (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    thanh_vien_don_vi_id INTEGER NOT NULL,
    vi_tri_chinh_id INTEGER,
    nguoi_quan_ly_id INTEGER,

    loai_nhan_su VARCHAR(30) NOT NULL DEFAULT 'CHINH_THUC'
        CHECK (
            loai_nhan_su IN (
                'CHINH_THUC',
                'THOI_VU',
                'CONG_TAC_VIEN'
            )
        ),

    hinh_thuc_lam_viec VARCHAR(30)
        CHECK (
            hinh_thuc_lam_viec IN (
                'TOAN_THOI_GIAN',
                'BAN_THOI_GIAN'
            )
        ),

    ngay_bat_dau_thu_viec DATE,
    ngay_ket_thuc_thu_viec DATE,
    ngay_chinh_thuc DATE,
    ngay_nghi_viec_du_kien DATE,

    ma_cham_cong VARCHAR(50),
    so_may_le VARCHAR(20),
    email_noi_bo VARCHAR(254),
    ghi_chu_cong_viec TEXT,

    CONSTRAINT uq_ho_so_thanh_vien
        UNIQUE (don_vi_id, thanh_vien_don_vi_id),

    CONSTRAINT fk_ho_so_thanh_vien
        FOREIGN KEY (don_vi_id, thanh_vien_don_vi_id)
        REFERENCES thanh_vien_don_vi(don_vi_id, id),

    CONSTRAINT fk_ho_so_vi_tri
        FOREIGN KEY (don_vi_id, vi_tri_chinh_id)
        REFERENCES vi_tri_cong_viec(don_vi_id, id),

    CONSTRAINT fk_ho_so_quan_ly
        FOREIGN KEY (don_vi_id, nguoi_quan_ly_id)
        REFERENCES thanh_vien_don_vi(don_vi_id, id),

    CONSTRAINT ck_ho_so_thu_viec CHECK (
        ngay_ket_thuc_thu_viec IS NULL
        OR ngay_bat_dau_thu_viec IS NULL
        OR ngay_ket_thuc_thu_viec >= ngay_bat_dau_thu_viec
    ),

    CONSTRAINT ck_ho_so_khong_tu_quan_ly CHECK (
        nguoi_quan_ly_id IS NULL
        OR nguoi_quan_ly_id <> thanh_vien_don_vi_id
    )
);

CREATE UNIQUE INDEX uq_ho_so_ma_cham_cong
ON ho_so_nhan_vien (
    don_vi_id,
    ma_cham_cong
)
WHERE ma_cham_cong IS NOT NULL;


CREATE TABLE phan_cong_vi_tri (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    thanh_vien_don_vi_id INTEGER NOT NULL,
    vi_tri_cong_viec_id INTEGER NOT NULL,
    chi_nhanh_id INTEGER,

    ngay_bat_dau DATE NOT NULL,
    ngay_ket_thuc DATE,
    la_vi_tri_chinh BOOLEAN NOT NULL DEFAULT FALSE,
    ly_do_phan_cong TEXT,
    nguoi_phan_cong_id INTEGER,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'HIEU_LUC'
        CHECK (
            trang_thai IN (
                'HIEU_LUC',
                'TAM_DUNG',
                'KET_THUC'
            )
        ),

    CONSTRAINT fk_pcvt_thanh_vien
        FOREIGN KEY (don_vi_id, thanh_vien_don_vi_id)
        REFERENCES thanh_vien_don_vi(don_vi_id, id),

    CONSTRAINT fk_pcvt_vi_tri
        FOREIGN KEY (don_vi_id, vi_tri_cong_viec_id)
        REFERENCES vi_tri_cong_viec(don_vi_id, id),

    CONSTRAINT fk_pcvt_chi_nhanh
        FOREIGN KEY (don_vi_id, chi_nhanh_id)
        REFERENCES chi_nhanh(don_vi_id, id),

    CONSTRAINT fk_pcvt_nguoi_phan_cong
        FOREIGN KEY (don_vi_id, nguoi_phan_cong_id)
        REFERENCES thanh_vien_don_vi(don_vi_id, id),

    CONSTRAINT ck_pcvt_khoang_ngay CHECK (
        ngay_ket_thuc IS NULL
        OR ngay_ket_thuc >= ngay_bat_dau
    )
);

CREATE INDEX idx_pcvt_thanh_vien
ON phan_cong_vi_tri (
    don_vi_id,
    thanh_vien_don_vi_id,
    ngay_bat_dau DESC
);

CREATE UNIQUE INDEX uq_pcvt_vi_tri_chinh_dang_mo
ON phan_cong_vi_tri (
    don_vi_id,
    thanh_vien_don_vi_id
)
WHERE la_vi_tri_chinh
  AND ngay_ket_thuc IS NULL
  AND trang_thai = 'HIEU_LUC';


CREATE TABLE loi_moi_nhan_vien (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    thanh_vien_don_vi_id INTEGER,
    tai_khoan_id INTEGER REFERENCES tai_khoan(id),
    email_moi VARCHAR(254) NOT NULL,
    ma_loi_moi VARCHAR(80) NOT NULL UNIQUE,

    ma_xac_nhan_bam CHAR(64)
        CHECK (
            ma_xac_nhan_bam IS NULL
            OR btrim(ma_xac_nhan_bam) ~ '^[0-9a-f]{64}$'
        ),

    nguoi_moi_id INTEGER NOT NULL,
    ngay_gui TIMESTAMPTZ,
    ngay_het_han TIMESTAMPTZ NOT NULL,
    ngay_chap_nhan TIMESTAMPTZ,
    ngay_tu_choi TIMESTAMPTZ,
    ngay_huy TIMESTAMPTZ,

    so_lan_gui SMALLINT NOT NULL DEFAULT 0
        CHECK (so_lan_gui >= 0),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'CHO_GUI'
        CHECK (
            trang_thai IN (
                'CHO_GUI',
                'DA_GUI',
                'DA_CHAP_NHAN',
                'TU_CHOI',
                'HET_HAN',
                'DA_HUY'
            )
        ),

    ly_do_huy TEXT,

    CONSTRAINT fk_loi_moi_thanh_vien
        FOREIGN KEY (don_vi_id, thanh_vien_don_vi_id)
        REFERENCES thanh_vien_don_vi(don_vi_id, id),

    CONSTRAINT fk_loi_moi_nguoi_moi
        FOREIGN KEY (don_vi_id, nguoi_moi_id)
        REFERENCES thanh_vien_don_vi(don_vi_id, id),

    CONSTRAINT ck_loi_moi_thoi_han CHECK (
        ngay_het_han > ngay_tao
    )
);

CREATE INDEX idx_loi_moi_don_vi_email
ON loi_moi_nhan_vien (
    don_vi_id,
    lower(email_moi),
    ngay_tao DESC
);


CREATE TABLE lich_su_cong_tac_nhan_vien (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    thanh_vien_don_vi_id INTEGER NOT NULL,
    loai_su_kien VARCHAR(40) NOT NULL,

    chi_nhanh_cu_id INTEGER,
    chi_nhanh_moi_id INTEGER,
    vi_tri_cu_id INTEGER,
    vi_tri_moi_id INTEGER,

    trang_thai_cu VARCHAR(24),
    trang_thai_moi VARCHAR(24),
    ngay_hieu_luc TIMESTAMPTZ NOT NULL,

    nguoi_thuc_hien_id INTEGER NOT NULL REFERENCES tai_khoan(id),
    ly_do TEXT,
    ghi_chu TEXT,

    CONSTRAINT fk_lsct_thanh_vien
        FOREIGN KEY (don_vi_id, thanh_vien_don_vi_id)
        REFERENCES thanh_vien_don_vi(don_vi_id, id),

    CONSTRAINT fk_lsct_cn_cu
        FOREIGN KEY (don_vi_id, chi_nhanh_cu_id)
        REFERENCES chi_nhanh(don_vi_id, id),

    CONSTRAINT fk_lsct_cn_moi
        FOREIGN KEY (don_vi_id, chi_nhanh_moi_id)
        REFERENCES chi_nhanh(don_vi_id, id),

    CONSTRAINT fk_lsct_vt_cu
        FOREIGN KEY (don_vi_id, vi_tri_cu_id)
        REFERENCES vi_tri_cong_viec(don_vi_id, id),

    CONSTRAINT fk_lsct_vt_moi
        FOREIGN KEY (don_vi_id, vi_tri_moi_id)
        REFERENCES vi_tri_cong_viec(don_vi_id, id)
);

CREATE INDEX idx_lsct_thanh_vien
ON lich_su_cong_tac_nhan_vien (
    don_vi_id,
    thanh_vien_don_vi_id,
    ngay_hieu_luc DESC
);


DO $$
DECLARE
    ten_bang TEXT;
BEGIN
    FOREACH ten_bang IN ARRAY ARRAY[
        'vi_tri_cong_viec',
        'ho_so_nhan_vien',
        'phan_cong_vi_tri',
        'loi_moi_nhan_vien',
        'lich_su_cong_tac_nhan_vien'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I
             BEFORE UPDATE ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || ten_bang || '_ngay_cap_nhat',
            ten_bang
        );
    END LOOP;
END;
$$;