CREATE TABLE tac_gia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    ma_tac_gia VARCHAR(50) NOT NULL,
    ho_ten VARCHAR(200) NOT NULL,
    ten_hien_thi VARCHAR(200),
    ten_goc VARCHAR(200),
    ten_sap_xep VARCHAR(200),
    ten_khac VARCHAR(200),

    ngay_sinh DATE,
    nam_sinh SMALLINT,
    ngay_mat DATE,
    nam_mat SMALLINT,

    quoc_tich VARCHAR(100),
    quoc_gia_xuat_than VARCHAR(100),
    ngon_ngu_sang_tac VARCHAR(15),

    tieu_su_ngan TEXT,
    tieu_su_day_du TEXT,
    linh_vuc_sang_tac TEXT,
    thanh_tuu TEXT,
    website TEXT,
    url_tham_khao TEXT,

    anh_dai_dien_tep_id INTEGER REFERENCES tep_dinh_kem(id),
    nguon_du_lieu VARCHAR(80),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_AN',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT uq_tac_gia_ma
        UNIQUE (don_vi_id, ma_tac_gia),

    CONSTRAINT uq_tac_gia_tenant_id
        UNIQUE (don_vi_id, id),

    CONSTRAINT ck_tac_gia_nam CHECK (
        nam_mat IS NULL
        OR nam_sinh IS NULL
        OR nam_mat >= nam_sinh
    )
);

CREATE INDEX idx_tac_gia_ten
ON tac_gia (
    don_vi_id,
    lower(ho_ten)
);


CREATE TABLE ten_khac_tac_gia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    tac_gia_id INTEGER NOT NULL,
    ten VARCHAR(200) NOT NULL,

    loai_ten VARCHAR(30) NOT NULL
        CHECK (
            loai_ten IN (
                'BUT_DANH',
                'TEN_GOC',
                'PHIEN_AM',
                'TEN_KHAC'
            )
        ),

    ngon_ngu VARCHAR(15),
    la_ten_uu_tien BOOLEAN NOT NULL DEFAULT FALSE,
    ghi_chu TEXT,

    CONSTRAINT fk_ten_khac_tg
        FOREIGN KEY (don_vi_id, tac_gia_id)
        REFERENCES tac_gia(don_vi_id, id)
);

CREATE UNIQUE INDEX uq_ten_khac_tg
ON ten_khac_tac_gia (
    don_vi_id,
    tac_gia_id,
    loai_ten,
    lower(ten)
);


CREATE TABLE nha_xuat_ban (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    ma_nha_xuat_ban VARCHAR(40) NOT NULL,
    ten_nha_xuat_ban VARCHAR(255) NOT NULL,
    ten_phap_ly VARCHAR(255),
    ten_viet_tat VARCHAR(100),
    ten_quoc_te VARCHAR(255),

    ma_so_thue VARCHAR(30),
    ma_dinh_danh VARCHAR(60),
    quoc_gia VARCHAR(100),
    tinh_thanh VARCHAR(120),
    dia_chi TEXT,

    email VARCHAR(254),
    so_dien_thoai VARCHAR(30),
    website TEXT,
    nguoi_lien_he VARCHAR(160),
    so_dien_thoai_lien_he VARCHAR(30),

    logo_tep_id INTEGER REFERENCES tep_dinh_kem(id),
    mo_ta TEXT,
    ghi_chu_noi_bo TEXT,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_NGUNG',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT uq_nxb_ma
        UNIQUE (don_vi_id, ma_nha_xuat_ban),

    CONSTRAINT uq_nxb_tenant_id
        UNIQUE (don_vi_id, id)
);

CREATE INDEX idx_nxb_ten
ON nha_xuat_ban (
    don_vi_id,
    lower(ten_nha_xuat_ban)
);


CREATE TABLE thuong_hieu_xuat_ban (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    nha_xuat_ban_id INTEGER NOT NULL,
    ma_thuong_hieu VARCHAR(50) NOT NULL,
    ten_thuong_hieu VARCHAR(200) NOT NULL,
    mo_ta TEXT,
    logo_tep_id INTEGER REFERENCES tep_dinh_kem(id),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_NGUNG',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT fk_thxb_nxb
        FOREIGN KEY (don_vi_id, nha_xuat_ban_id)
        REFERENCES nha_xuat_ban(don_vi_id, id),

    CONSTRAINT uq_thxb_ma
        UNIQUE (don_vi_id, ma_thuong_hieu),

    CONSTRAINT uq_thxb_tenant_id
        UNIQUE (don_vi_id, id),

    CONSTRAINT uq_thxb_nxb_id
        UNIQUE (don_vi_id, nha_xuat_ban_id, id)
);


CREATE TABLE nha_phat_hanh (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    ma_nha_phat_hanh VARCHAR(50) NOT NULL,
    ten_nha_phat_hanh VARCHAR(255) NOT NULL,
    ten_phap_ly VARCHAR(255),
    ma_so_thue VARCHAR(30),
    email VARCHAR(254),
    so_dien_thoai VARCHAR(30),
    website TEXT,
    dia_chi TEXT,
    logo_tep_id INTEGER REFERENCES tep_dinh_kem(id),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_NGUNG',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT uq_nph_ma
        UNIQUE (don_vi_id, ma_nha_phat_hanh),

    CONSTRAINT uq_nph_tenant_id
        UNIQUE (don_vi_id, id)
);


CREATE TABLE the_loai_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    ma_the_loai VARCHAR(50) NOT NULL,
    ten_the_loai VARCHAR(200) NOT NULL,
    ten_tieng_anh VARCHAR(200),
    the_loai_cha_id INTEGER,

    mo_ta TEXT,
    duong_dan VARCHAR(240),
    thu_tu INTEGER NOT NULL DEFAULT 0,
    cap_do SMALLINT NOT NULL DEFAULT 1
        CHECK (cap_do >= 1),

    anh_dai_dien_tep_id INTEGER REFERENCES tep_dinh_kem(id),
    icon_tep_id INTEGER REFERENCES tep_dinh_kem(id),

    hien_thi_menu BOOLEAN NOT NULL DEFAULT TRUE,
    hien_thi_trang_chu BOOLEAN NOT NULL DEFAULT FALSE,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_AN',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT uq_the_loai_ma
        UNIQUE (don_vi_id, ma_the_loai),

    CONSTRAINT uq_the_loai_tenant_id
        UNIQUE (don_vi_id, id),

    CONSTRAINT fk_the_loai_cha
        FOREIGN KEY (don_vi_id, the_loai_cha_id)
        REFERENCES the_loai_sach(don_vi_id, id),

    CONSTRAINT ck_the_loai_khong_tu_cha CHECK (
        the_loai_cha_id IS NULL
        OR the_loai_cha_id <> id
    )
);

CREATE UNIQUE INDEX uq_the_loai_slug
ON the_loai_sach (
    don_vi_id,
    lower(duong_dan)
)
WHERE duong_dan IS NOT NULL;

CREATE INDEX idx_the_loai_cha
ON the_loai_sach (
    don_vi_id,
    the_loai_cha_id,
    thu_tu
);


CREATE TABLE tu_khoa_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    ma_tu_khoa VARCHAR(60),
    ten_tu_khoa VARCHAR(120) NOT NULL,
    ten_chuan_hoa VARCHAR(120) NOT NULL,

    loai_tu_khoa VARCHAR(30) NOT NULL DEFAULT 'CHU_DE'
        CHECK (
            loai_tu_khoa IN (
                'CHU_DE',
                'KY_NANG',
                'NHAN_VAT',
                'SU_KIEN',
                'KHAC'
            )
        ),

    mo_ta TEXT,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_AN',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT uq_tu_khoa_chuan
        UNIQUE (
            don_vi_id,
            ten_chuan_hoa,
            loai_tu_khoa
        ),

    CONSTRAINT uq_tu_khoa_tenant_id
        UNIQUE (don_vi_id, id)
);

CREATE UNIQUE INDEX uq_tu_khoa_ma
ON tu_khoa_sach (
    don_vi_id,
    ma_tu_khoa
)
WHERE ma_tu_khoa IS NOT NULL;


DO $$
DECLARE
    ten_bang TEXT;
BEGIN
    FOREACH ten_bang IN ARRAY ARRAY[
        'tac_gia',
        'ten_khac_tac_gia',
        'nha_xuat_ban',
        'thuong_hieu_xuat_ban',
        'nha_phat_hanh',
        'the_loai_sach',
        'tu_khoa_sach'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I
             BEFORE UPDATE ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || ten_bang || '_ngay_cap_nhat',
            ten_bang
        );
    END LOOP;
END;
$$;