CREATE TABLE dau_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    -- Dinh danh
    ma_dau_sach VARCHAR(50) NOT NULL,
    duong_dan VARCHAR(300),
    ma_dau_sach_ngoai VARCHAR(100),

    loai_tac_pham VARCHAR(30) NOT NULL DEFAULT 'SACH'
        CHECK (
            loai_tac_pham IN (
                'SACH',
                'TRUYEN_TRANH',
                'GIAO_TRINH',
                'TAP_CHI',
                'KHAC'
            )
        ),

    -- Nhan de
    ten_sach VARCHAR(300) NOT NULL,
    ten_goc VARCHAR(300),
    ten_phu VARCHAR(300),
    ten_ngan VARCHAR(160),
    ten_hien_thi VARCHAR(350),

    -- Noi dung
    mo_ta_ngan TEXT,
    mo_ta_day_du TEXT,
    tom_tat_noi_dung TEXT,
    diem_noi_bat TEXT,
    muc_luc_gioi_thieu TEXT,
    loi_gioi_thieu TEXT,
    thong_diep_tac_pham TEXT,

    -- Thong tin tac pham
    ngon_ngu_goc VARCHAR(15),
    quoc_gia_xuat_xu VARCHAR(100),
    nam_sang_tac SMALLINT,
    nam_xuat_ban_dau_tien SMALLINT,
    ngay_xuat_ban_hien_thi DATE,
    la_tac_pham_dich BOOLEAN NOT NULL DEFAULT FALSE,
    la_tac_pham_doc_lap BOOLEAN NOT NULL DEFAULT TRUE,

    -- Doc gia
    doi_tuong_doc VARCHAR(160),
    do_tuoi_goi_y SMALLINT
        CHECK (do_tuoi_goi_y >= 0),
    do_tuoi_toi_thieu SMALLINT
        CHECK (do_tuoi_toi_thieu >= 0),
    do_tuoi_toi_da SMALLINT
        CHECK (do_tuoi_toi_da >= 0),
    cap_hoc_goi_y VARCHAR(60),
    muc_do_kho VARCHAR(30),
    chu_de_noi_bat TEXT,
    canh_bao_noi_dung TEXT,
    ghi_chu_noi_dung TEXT,

    -- Anh bia mac dinh
    anh_bia_chinh_id INTEGER REFERENCES tep_dinh_kem(id),

    -- Nguon metadata
    nguon_du_lieu VARCHAR(80),
    ma_nguon_du_lieu VARCHAR(100),
    url_nguon TEXT,
    ngay_dong_bo_nguon TIMESTAMPTZ,
    nguoi_kiem_duyet_id INTEGER REFERENCES tai_khoan(id),
    ngay_kiem_duyet TIMESTAMPTZ,

    -- Hien thi cong khai
    tieu_de_seo VARCHAR(300),
    mo_ta_seo VARCHAR(500),
    cho_hien_thi_cong_khai BOOLEAN NOT NULL DEFAULT FALSE,
    ngay_cong_bo TIMESTAMPTZ,
    ngay_an TIMESTAMPTZ,
    ly_do_an TEXT,

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'NHAP'
        CHECK (
            trang_thai IN (
                'NHAP',
                'CHO_DUYET',
                'DANG_HIEN_THI',
                'TAM_AN',
                'NGUNG_KINH_DOANH'
            )
        ),

    ngay_xoa TIMESTAMPTZ,

    CONSTRAINT uq_dau_sach_ma
        UNIQUE (don_vi_id, ma_dau_sach),

    CONSTRAINT uq_dau_sach_tenant_id
        UNIQUE (don_vi_id, id),

    CONSTRAINT ck_dau_sach_do_tuoi CHECK (
        do_tuoi_toi_thieu IS NULL
        OR do_tuoi_toi_da IS NULL
        OR do_tuoi_toi_da >= do_tuoi_toi_thieu
    )
);

CREATE UNIQUE INDEX uq_dau_sach_slug
ON dau_sach (
    don_vi_id,
    lower(duong_dan)
)
WHERE duong_dan IS NOT NULL;

CREATE INDEX idx_dau_sach_ten
ON dau_sach (
    don_vi_id,
    lower(ten_sach)
);

CREATE INDEX idx_dau_sach_trang_thai
ON dau_sach (
    don_vi_id,
    trang_thai,
    ngay_tao DESC
);


CREATE TABLE dau_sach_ten_khac (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER NOT NULL,
    ten VARCHAR(350) NOT NULL,

    loai_ten VARCHAR(30) NOT NULL
        CHECK (
            loai_ten IN (
                'TEN_GOC',
                'TEN_DICH',
                'TEN_CU',
                'TEN_VIET_TAT',
                'KHAC'
            )
        ),

    ngon_ngu VARCHAR(15),
    la_ten_uu_tien BOOLEAN NOT NULL DEFAULT FALSE,
    thu_tu SMALLINT NOT NULL DEFAULT 0
        CHECK (thu_tu >= 0),

    CONSTRAINT fk_dstk_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id)
);

CREATE UNIQUE INDEX uq_dstk_ten
ON dau_sach_ten_khac (
    don_vi_id,
    dau_sach_id,
    loai_ten,
    lower(ten)
);


CREATE TABLE dau_sach_tac_gia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER NOT NULL,
    tac_gia_id INTEGER NOT NULL,

    vai_tro_dong_gop VARCHAR(30) NOT NULL DEFAULT 'TAC_GIA'
        CHECK (
            vai_tro_dong_gop IN (
                'TAC_GIA',
                'DONG_TAC_GIA',
                'DICH_GIA',
                'BIEN_SOAN',
                'MINH_HOA',
                'HIEU_DINH',
                'BIEN_TAP',
                'KHAC'
            )
        ),

    thu_tu_hien_thi SMALLINT NOT NULL DEFAULT 1
        CHECK (thu_tu_hien_thi >= 1),

    la_nguoi_dong_gop_chinh BOOLEAN NOT NULL DEFAULT FALSE,
    ghi_chu VARCHAR(300),

    CONSTRAINT fk_dstg_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT fk_dstg_tac_gia
        FOREIGN KEY (don_vi_id, tac_gia_id)
        REFERENCES tac_gia(don_vi_id, id),

    CONSTRAINT uq_dstg
        UNIQUE (
            don_vi_id,
            dau_sach_id,
            tac_gia_id,
            vai_tro_dong_gop
        )
);


CREATE TABLE dau_sach_the_loai (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER NOT NULL,
    the_loai_id INTEGER NOT NULL,
    la_the_loai_chinh BOOLEAN NOT NULL DEFAULT FALSE,
    thu_tu_hien_thi SMALLINT NOT NULL DEFAULT 0
        CHECK (thu_tu_hien_thi >= 0),

    CONSTRAINT fk_dstl_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT fk_dstl_the_loai
        FOREIGN KEY (don_vi_id, the_loai_id)
        REFERENCES the_loai_sach(don_vi_id, id),

    CONSTRAINT uq_dstl
        UNIQUE (don_vi_id, dau_sach_id, the_loai_id)
);

CREATE UNIQUE INDEX uq_dstl_chinh
ON dau_sach_the_loai (
    don_vi_id,
    dau_sach_id
)
WHERE la_the_loai_chinh;


CREATE TABLE dau_sach_tu_khoa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER NOT NULL,
    tu_khoa_id INTEGER NOT NULL,

    nguon_gan VARCHAR(20) NOT NULL DEFAULT 'THU_CONG'
        CHECK (
            nguon_gan IN (
                'THU_CONG',
                'NHAP_LIEU',
                'AI_GOI_Y'
            )
        ),

    da_duyet BOOLEAN NOT NULL DEFAULT FALSE,
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ngay_duyet TIMESTAMPTZ,

    CONSTRAINT fk_dstk_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT fk_dstk_tu_khoa
        FOREIGN KEY (don_vi_id, tu_khoa_id)
        REFERENCES tu_khoa_sach(don_vi_id, id),

    CONSTRAINT uq_dstk
        UNIQUE (don_vi_id, dau_sach_id, tu_khoa_id)
);


CREATE TABLE bo_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    ma_bo_sach VARCHAR(50) NOT NULL,
    ten_bo_sach VARCHAR(300) NOT NULL,
    ten_goc VARCHAR(300),
    mo_ta TEXT,
    anh_bia_chinh_id INTEGER REFERENCES tep_dinh_kem(id),
    so_tap_du_kien SMALLINT
        CHECK (so_tap_du_kien > 0),
    da_hoan_thanh BOOLEAN NOT NULL DEFAULT FALSE,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_AN',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT uq_bo_sach_ma
        UNIQUE (don_vi_id, ma_bo_sach),

    CONSTRAINT uq_bo_sach_tenant_id
        UNIQUE (don_vi_id, id)
);


CREATE TABLE bo_sach_dau_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    bo_sach_id INTEGER NOT NULL,
    dau_sach_id INTEGER NOT NULL,
    so_tap VARCHAR(30),
    ten_tap VARCHAR(300),
    thu_tu SMALLINT NOT NULL
        CHECK (thu_tu >= 1),
    ghi_chu TEXT,

    CONSTRAINT fk_bsds_bo
        FOREIGN KEY (don_vi_id, bo_sach_id)
        REFERENCES bo_sach(don_vi_id, id),

    CONSTRAINT fk_bsds_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT uq_bsds
        UNIQUE (don_vi_id, bo_sach_id, dau_sach_id)
);

CREATE INDEX idx_bsds_thu_tu
ON bo_sach_dau_sach (
    don_vi_id,
    bo_sach_id,
    thu_tu
);


CREATE TABLE dau_sach_lien_quan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER NOT NULL,
    dau_sach_lien_quan_id INTEGER NOT NULL,

    loai_lien_quan VARCHAR(30) NOT NULL
        CHECK (
            loai_lien_quan IN (
                'CUNG_CHU_DE',
                'PHAN_TIEP_THEO',
                'PHAN_TRUOC',
                'BAN_MO_RONG',
                'TAI_LIEU_THAM_KHAO'
            )
        ),

    thu_tu SMALLINT NOT NULL DEFAULT 0
        CHECK (thu_tu >= 0),
    ghi_chu TEXT,

    CONSTRAINT fk_dslq_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT fk_dslq_sach_lien_quan
        FOREIGN KEY (don_vi_id, dau_sach_lien_quan_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT uq_dslq
        UNIQUE (
            don_vi_id,
            dau_sach_id,
            dau_sach_lien_quan_id,
            loai_lien_quan
        ),

    CONSTRAINT ck_dslq_khong_tu_lien_quan CHECK (
        dau_sach_id <> dau_sach_lien_quan_id
    )
);


CREATE TABLE dau_sach_phan_loai (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER NOT NULL,

    he_phan_loai VARCHAR(30) NOT NULL
        CHECK (
            he_phan_loai IN (
                'DDC',
                'LCC',
                'BISAC',
                'THEMA',
                'KHAC'
            )
        ),

    ma_phan_loai VARCHAR(60) NOT NULL,
    ten_phan_loai VARCHAR(255),
    phien_ban_he_phan_loai VARCHAR(50),
    la_phan_loai_chinh BOOLEAN NOT NULL DEFAULT FALSE,
    nguon_xac_minh TEXT,
    ngay_xac_minh TIMESTAMPTZ,

    CONSTRAINT fk_dspl_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT uq_dspl
        UNIQUE (
            don_vi_id,
            dau_sach_id,
            he_phan_loai,
            ma_phan_loai
        )
);


DO $$
DECLARE
    ten_bang TEXT;
BEGIN
    FOREACH ten_bang IN ARRAY ARRAY[
        'dau_sach',
        'dau_sach_ten_khac',
        'dau_sach_tac_gia',
        'dau_sach_the_loai',
        'dau_sach_tu_khoa',
        'bo_sach',
        'bo_sach_dau_sach',
        'dau_sach_lien_quan',
        'dau_sach_phan_loai'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I
             BEFORE UPDATE ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || ten_bang || '_ngay_cap_nhat',
            ten_bang
        );
    END LOOP;
END;
$$;