CREATE TABLE phien_ban_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    -- Dinh danh va ten phien ban
    dau_sach_id INTEGER NOT NULL,
    ma_phien_ban VARCHAR(60) NOT NULL,
    ma_sku_noi_bo VARCHAR(80),
    ten_phien_ban VARCHAR(300),
    ten_hien_thi VARCHAR(350),

    -- ISBN va ma xuat ban
    isbn_10 VARCHAR(10)
        CHECK (
            isbn_10 IS NULL
            OR isbn_10 ~ '^[0-9]{9}[0-9X]$'
        ),

    isbn_13 VARCHAR(13)
        CHECK (
            isbn_13 IS NULL
            OR isbn_13 ~ '^[0-9]{13}$'
        ),

    ma_isbn VARCHAR(20)
        GENERATED ALWAYS AS (
            COALESCE(isbn_13, isbn_10)
        ) STORED,

    ma_ean_13 VARCHAR(13)
        CHECK (
            ma_ean_13 IS NULL
            OR ma_ean_13 ~ '^[0-9]{13}$'
        ),

    ma_vach_nha_xuat_ban VARCHAR(60),
    ma_san_pham_nha_xuat_ban VARCHAR(80),
    ma_luu_chieu VARCHAR(100),

    nhan_de_tren_bia VARCHAR(350),
    phu_de_phien_ban VARCHAR(350),
    ghi_chu_phien_ban TEXT,

    -- Xuat ban va phat hanh
    nha_xuat_ban_id INTEGER,
    thuong_hieu_xuat_ban_id INTEGER,
    nha_phat_hanh_id INTEGER,
    ten_nha_in VARCHAR(255),
    noi_xuat_ban VARCHAR(200),
    quoc_gia_xuat_ban VARCHAR(100),

    lan_xuat_ban SMALLINT
        CHECK (lan_xuat_ban > 0),
    lan_tai_ban SMALLINT
        CHECK (lan_tai_ban > 0),
    lan_in SMALLINT
        CHECK (lan_in > 0),
    so_ban_in INTEGER
        CHECK (so_ban_in > 0),

    nam_xuat_ban SMALLINT
        CHECK (nam_xuat_ban BETWEEN 1000 AND 9999),

    ngay_xuat_ban DATE,
    ngay_phat_hanh DATE,
    ngay_ngung_phat_hanh DATE,
    ghi_chu_lan_xuat_ban TEXT,

    -- Ngon ngu va dinh dang
    ngon_ngu_chinh VARCHAR(15) NOT NULL DEFAULT 'vi',
    ngon_ngu_goc VARCHAR(15),
    la_ban_dich BOOLEAN NOT NULL DEFAULT FALSE,
    la_ban_song_ngu BOOLEAN NOT NULL DEFAULT FALSE,

    loai_phien_ban VARCHAR(30) NOT NULL DEFAULT 'SACH_IN'
        CHECK (
            loai_phien_ban IN (
                'SACH_IN',
                'EBOOK',
                'SACH_NOI',
                'KHAC'
            )
        ),

    dinh_dang_noi_dung VARCHAR(30),

    -- Quy cach bia va giay
    loai_bia VARCHAR(24)
        CHECK (
            loai_bia IS NULL
            OR loai_bia IN (
                'BIA_MEM',
                'BIA_CUNG',
                'BIA_GAP',
                'KHAC'
            )
        ),

    chat_lieu_bia VARCHAR(100),
    kieu_dong_gay VARCHAR(80),
    chat_lieu_giay VARCHAR(100),

    dinh_luong_giay_gsm NUMERIC(8,2)
        CHECK (dinh_luong_giay_gsm > 0),

    loai_muc_in VARCHAR(80),
    so_mau_in SMALLINT
        CHECK (so_mau_in > 0),
    in_mau BOOLEAN,
    co_minh_hoa_mau BOOLEAN,

    -- Trang va cau truc
    so_trang INTEGER CHECK (so_trang > 0),
    so_trang_noi_dung INTEGER
        CHECK (so_trang_noi_dung > 0),
    so_trang_phu_luc INTEGER
        CHECK (so_trang_phu_luc >= 0),
    so_chuong INTEGER CHECK (so_chuong > 0),
    so_tap_trong_hop SMALLINT
        CHECK (so_tap_trong_hop > 0),
    so_quyen_trong_bo SMALLINT
        CHECK (so_quyen_trong_bo > 0),

    co_phu_luc BOOLEAN,
    co_dia_kem_theo BOOLEAN,
    so_dia_kem_theo SMALLINT
        CHECK (so_dia_kem_theo >= 0),

    -- Kich thuoc va trong luong
    chieu_dai_mm NUMERIC(8,2)
        CHECK (chieu_dai_mm > 0),
    chieu_rong_mm NUMERIC(8,2)
        CHECK (chieu_rong_mm > 0),
    do_day_mm NUMERIC(8,2)
        CHECK (do_day_mm > 0),
    trong_luong_gram INTEGER
        CHECK (trong_luong_gram > 0),

    chieu_dai_dong_goi_mm NUMERIC(8,2)
        CHECK (chieu_dai_dong_goi_mm > 0),
    chieu_rong_dong_goi_mm NUMERIC(8,2)
        CHECK (chieu_rong_dong_goi_mm > 0),
    chieu_cao_dong_goi_mm NUMERIC(8,2)
        CHECK (chieu_cao_dong_goi_mm > 0),
    trong_luong_dong_goi_gram INTEGER
        CHECK (trong_luong_dong_goi_gram > 0),

    -- Ebook va sach noi
    so_trang_dien_tu INTEGER
        CHECK (so_trang_dien_tu > 0),
    thoi_luong_am_thanh_giay INTEGER
        CHECK (thoi_luong_am_thanh_giay > 0),
    dinh_dang_am_thanh VARCHAR(30),
    toc_do_bit_am_thanh INTEGER
        CHECK (toc_do_bit_am_thanh > 0),
    dung_luong_noi_dung_byte BIGINT
        CHECK (dung_luong_noi_dung_byte > 0),

    co_drm BOOLEAN,
    loai_drm VARCHAR(50),
    dieu_kien_truy_cap_so TEXT,

    -- Gia bia tham khao
    gia_bia NUMERIC(18,2)
        CHECK (gia_bia >= 0),
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',

    -- Hinh anh va mo ta rieng
    anh_bia_chinh_id INTEGER REFERENCES tep_dinh_kem(id),
    mo_ta_rieng_phien_ban TEXT,
    ghi_chu_quy_cach TEXT,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'NHAP'
        CHECK (
            trang_thai IN (
                'NHAP',
                'DANG_DUNG',
                'TAM_NGUNG',
                'NGUNG_PHAT_HANH'
            )
        ),

    ngay_ngung_kinh_doanh TIMESTAMPTZ,
    ly_do_ngung TEXT,

    CONSTRAINT fk_pbs_dau_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT fk_pbs_nxb
        FOREIGN KEY (don_vi_id, nha_xuat_ban_id)
        REFERENCES nha_xuat_ban(don_vi_id, id),

    CONSTRAINT fk_pbs_thuong_hieu
        FOREIGN KEY (
            don_vi_id,
            nha_xuat_ban_id,
            thuong_hieu_xuat_ban_id
        )
        REFERENCES thuong_hieu_xuat_ban(
            don_vi_id,
            nha_xuat_ban_id,
            id
        ),

    CONSTRAINT fk_pbs_nph
        FOREIGN KEY (don_vi_id, nha_phat_hanh_id)
        REFERENCES nha_phat_hanh(don_vi_id, id),

    CONSTRAINT ck_pbs_thuong_hieu_can_nxb CHECK (
        thuong_hieu_xuat_ban_id IS NULL
        OR nha_xuat_ban_id IS NOT NULL
    ),

    CONSTRAINT ck_pbs_ngay_phat_hanh CHECK (
        ngay_ngung_phat_hanh IS NULL
        OR ngay_phat_hanh IS NULL
        OR ngay_ngung_phat_hanh >= ngay_phat_hanh
    ),

    CONSTRAINT ck_pbs_so_trang CHECK (
        so_trang IS NULL
        OR so_trang_noi_dung IS NULL
        OR so_trang >= so_trang_noi_dung
    ),

    CONSTRAINT uq_pbs_ma
        UNIQUE (don_vi_id, ma_phien_ban),

    CONSTRAINT uq_pbs_tenant_id
        UNIQUE (don_vi_id, id)
);

CREATE UNIQUE INDEX uq_pbs_isbn10
ON phien_ban_sach (
    don_vi_id,
    isbn_10
)
WHERE isbn_10 IS NOT NULL;

CREATE UNIQUE INDEX uq_pbs_isbn13
ON phien_ban_sach (
    don_vi_id,
    isbn_13
)
WHERE isbn_13 IS NOT NULL;

CREATE UNIQUE INDEX uq_pbs_sku
ON phien_ban_sach (
    don_vi_id,
    ma_sku_noi_bo
)
WHERE ma_sku_noi_bo IS NOT NULL;

CREATE INDEX idx_pbs_dau_sach
ON phien_ban_sach (
    don_vi_id,
    dau_sach_id,
    trang_thai
);


CREATE TABLE phien_ban_nguoi_dong_gop (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    phien_ban_sach_id INTEGER NOT NULL,
    tac_gia_id INTEGER NOT NULL,
    vai_tro_dong_gop VARCHAR(30) NOT NULL,

    thu_tu_hien_thi SMALLINT NOT NULL DEFAULT 1
        CHECK (thu_tu_hien_thi >= 1),

    ghi_chu TEXT,

    CONSTRAINT fk_pbndg_pb
        FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),

    CONSTRAINT fk_pbndg_tac_gia
        FOREIGN KEY (don_vi_id, tac_gia_id)
        REFERENCES tac_gia(don_vi_id, id),

    CONSTRAINT uq_pbndg
        UNIQUE (
            don_vi_id,
            phien_ban_sach_id,
            tac_gia_id,
            vai_tro_dong_gop
        )
);


CREATE TABLE phien_ban_ngon_ngu (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    phien_ban_sach_id INTEGER NOT NULL,
    ma_ngon_ngu VARCHAR(15) NOT NULL,

    vai_tro_ngon_ngu VARCHAR(30) NOT NULL
        CHECK (
            vai_tro_ngon_ngu IN (
                'CHINH',
                'PHU',
                'DOI_CHIEU'
            )
        ),

    ghi_chu TEXT,

    CONSTRAINT fk_pbnn_pb
        FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),

    CONSTRAINT uq_pbnn
        UNIQUE (
            don_vi_id,
            phien_ban_sach_id,
            ma_ngon_ngu,
            vai_tro_ngon_ngu
        )
);

CREATE UNIQUE INDEX uq_pbnn_chinh
ON phien_ban_ngon_ngu (
    don_vi_id,
    phien_ban_sach_id
)
WHERE vai_tro_ngon_ngu = 'CHINH';


CREATE TABLE phien_ban_ma_dinh_danh (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    phien_ban_sach_id INTEGER NOT NULL,
    loai_ma VARCHAR(40) NOT NULL,
    gia_tri_ma VARCHAR(160) NOT NULL,
    nguon_cap_ma VARCHAR(160),
    url_kiem_chung TEXT,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT fk_pbmd_pb
        FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),

    CONSTRAINT uq_pbmd
        UNIQUE (don_vi_id, loai_ma, gia_tri_ma)
);


CREATE TABLE tep_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER,
    phien_ban_sach_id INTEGER,
    tep_dinh_kem_id INTEGER NOT NULL REFERENCES tep_dinh_kem(id),

    loai_tep_sach VARCHAR(40) NOT NULL
        CHECK (
            loai_tep_sach IN (
                'ANH_BIA_TRUOC',
                'ANH_BIA_SAU',
                'ANH_GAY',
                'ANH_TRANG_TRONG',
                'ANH_HOP',
                'ANH_PHU',
                'MUC_LUC',
                'TRICH_DOAN',
                'VIDEO_GIOI_THIEU',
                'TAI_LIEU_KHAC'
            )
        ),

    thu_tu INTEGER NOT NULL DEFAULT 0
        CHECK (thu_tu >= 0),

    la_anh_bia_chinh BOOLEAN NOT NULL DEFAULT FALSE,
    tieu_de VARCHAR(200),
    mo_ta VARCHAR(500),
    van_ban_thay_the VARCHAR(300),
    chu_thich_ban_quyen TEXT,

    duoc_phep_cong_khai BOOLEAN NOT NULL DEFAULT FALSE,
    ngay_bat_dau_cong_khai TIMESTAMPTZ,
    ngay_ket_thuc_cong_khai TIMESTAMPTZ,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_AN',
                'DA_GO'
            )
        ),

    CONSTRAINT ck_tep_sach_mot_chu CHECK (
        num_nonnulls(
            dau_sach_id,
            phien_ban_sach_id
        ) = 1
    ),

    CONSTRAINT fk_tep_sach_dau
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT fk_tep_sach_pb
        FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),

    CONSTRAINT ck_tep_sach_cong_khai CHECK (
        ngay_ket_thuc_cong_khai IS NULL
        OR ngay_bat_dau_cong_khai IS NULL
        OR ngay_ket_thuc_cong_khai > ngay_bat_dau_cong_khai
    )
);

CREATE UNIQUE INDEX uq_tep_sach_dau_file
ON tep_sach (
    don_vi_id,
    dau_sach_id,
    tep_dinh_kem_id
)
WHERE dau_sach_id IS NOT NULL
  AND trang_thai <> 'DA_GO';

CREATE UNIQUE INDEX uq_tep_sach_pb_file
ON tep_sach (
    don_vi_id,
    phien_ban_sach_id,
    tep_dinh_kem_id
)
WHERE phien_ban_sach_id IS NOT NULL
  AND trang_thai <> 'DA_GO';

CREATE UNIQUE INDEX uq_tep_sach_bia_dau
ON tep_sach (
    don_vi_id,
    dau_sach_id
)
WHERE dau_sach_id IS NOT NULL
  AND la_anh_bia_chinh
  AND trang_thai = 'DANG_DUNG';

CREATE UNIQUE INDEX uq_tep_sach_bia_pb
ON tep_sach (
    don_vi_id,
    phien_ban_sach_id
)
WHERE phien_ban_sach_id IS NOT NULL
  AND la_anh_bia_chinh
  AND trang_thai = 'DANG_DUNG';

CREATE INDEX idx_tep_sach_thu_tu
ON tep_sach (
    don_vi_id,
    dau_sach_id,
    phien_ban_sach_id,
    thu_tu
);


CREATE TABLE nguon_du_lieu_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER,
    phien_ban_sach_id INTEGER,

    ten_nguon VARCHAR(120) NOT NULL,
    loai_nguon VARCHAR(40) NOT NULL
        CHECK (
            loai_nguon IN (
                'THU_CONG',
                'NHA_XUAT_BAN',
                'NHA_CUNG_CAP',
                'ISBN_API',
                'DOI_TAC'
            )
        ),

    ma_ban_ghi_nguon VARCHAR(160),
    url_nguon TEXT,
    du_lieu_nguon JSONB,

    ngay_lay_du_lieu TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_doi_chieu TIMESTAMPTZ,
    nguoi_doi_chieu_id INTEGER REFERENCES tai_khoan(id),

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'CHO_DOI_CHIEU'
        CHECK (
            trang_thai IN (
                'CHO_DOI_CHIEU',
                'DA_DOI_CHIEU',
                'DA_BO_QUA'
            )
        ),

    CONSTRAINT ck_ndls_mot_chu CHECK (
        num_nonnulls(
            dau_sach_id,
            phien_ban_sach_id
        ) = 1
    ),

    CONSTRAINT fk_ndls_dau
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT fk_ndls_pb
        FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id)
);

CREATE INDEX idx_ndls_dau
ON nguon_du_lieu_sach (
    don_vi_id,
    dau_sach_id,
    ngay_lay_du_lieu DESC
);

CREATE INDEX idx_ndls_pb
ON nguon_du_lieu_sach (
    don_vi_id,
    phien_ban_sach_id,
    ngay_lay_du_lieu DESC
);


CREATE TABLE quyen_noi_dung_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    dau_sach_id INTEGER,
    phien_ban_sach_id INTEGER,
    tep_dinh_kem_id INTEGER REFERENCES tep_dinh_kem(id),

    loai_noi_dung VARCHAR(40) NOT NULL,
    chu_so_huu_quyen VARCHAR(255),
    nguon_cap_quyen VARCHAR(255),
    loai_giay_phep VARCHAR(80),
    pham_vi_su_dung VARCHAR(100),

    duoc_hien_thi_cong_khai BOOLEAN NOT NULL DEFAULT FALSE,
    duoc_dung_cho_ai BOOLEAN NOT NULL DEFAULT FALSE,

    ngay_bat_dau DATE,
    ngay_het_han DATE,
    tep_chung_minh_id INTEGER REFERENCES tep_dinh_kem(id),
    ghi_chu TEXT,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'CHO_XAC_MINH'
        CHECK (
            trang_thai IN (
                'CHO_XAC_MINH',
                'HIEU_LUC',
                'HET_HAN',
                'HUY'
            )
        ),

    CONSTRAINT ck_qnds_co_doi_tuong CHECK (
        num_nonnulls(
            dau_sach_id,
            phien_ban_sach_id,
            tep_dinh_kem_id
        ) >= 1
    ),

    CONSTRAINT fk_qnds_dau
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id),

    CONSTRAINT fk_qnds_pb
        FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),

    CONSTRAINT ck_qnds_ngay CHECK (
        ngay_het_han IS NULL
        OR ngay_bat_dau IS NULL
        OR ngay_het_han >= ngay_bat_dau
    )
);

CREATE INDEX idx_qnds_doi_tuong
ON quyen_noi_dung_sach (
    don_vi_id,
    dau_sach_id,
    phien_ban_sach_id,
    tep_dinh_kem_id,
    trang_thai
);


DO $$
DECLARE
    ten_bang TEXT;
BEGIN
    FOREACH ten_bang IN ARRAY ARRAY[
        'phien_ban_sach',
        'phien_ban_nguoi_dong_gop',
        'phien_ban_ngon_ngu',
        'phien_ban_ma_dinh_danh',
        'tep_sach',
        'nguon_du_lieu_sach',
        'quyen_noi_dung_sach'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I
             BEFORE UPDATE ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || ten_bang || '_ngay_cap_nhat',
            ten_bang
        );
    END LOOP;
END;
$$;