CREATE TABLE hinh_thuc_kinh_doanh_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    phien_ban_sach_id INTEGER NOT NULL,
    chi_nhanh_id INTEGER NOT NULL,
    ma_hinh_thuc VARCHAR(50) NOT NULL,

    hinh_thuc VARCHAR(24) NOT NULL
        CHECK (
            hinh_thuc IN (
                'BAN',
                'MUON_MIEN_PHI',
                'THUE_CO_PHI'
            )
        ),

    -- FK sang chinh_sach_muon se tao
    -- khi trien khai migration phan he muon/tra.
    chinh_sach_muon_id INTEGER,

    cho_dat_truoc BOOLEAN NOT NULL DEFAULT TRUE,
    cho_giao_tan_noi BOOLEAN NOT NULL DEFAULT FALSE,
    cho_nhan_tai_quay BOOLEAN NOT NULL DEFAULT TRUE,

    ngay_bat_dau TIMESTAMPTZ,
    ngay_ket_thuc TIMESTAMPTZ,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (
            trang_thai IN (
                'DANG_DUNG',
                'TAM_NGUNG',
                'NGUNG_DUNG'
            )
        ),

    CONSTRAINT fk_htkd_pb
        FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),

    CONSTRAINT fk_htkd_chi_nhanh
        FOREIGN KEY (don_vi_id, chi_nhanh_id)
        REFERENCES chi_nhanh(don_vi_id, id),

    CONSTRAINT uq_htkd_ma
        UNIQUE (
            don_vi_id,
            chi_nhanh_id,
            ma_hinh_thuc
        ),

    CONSTRAINT uq_htkd_phien_ban_loai
        UNIQUE (
            don_vi_id,
            chi_nhanh_id,
            phien_ban_sach_id,
            hinh_thuc
        ),

    CONSTRAINT uq_htkd_tenant_id
        UNIQUE (don_vi_id, id),

    CONSTRAINT ck_htkd_ngay CHECK (
        ngay_ket_thuc IS NULL
        OR ngay_bat_dau IS NULL
        OR ngay_ket_thuc > ngay_bat_dau
    )
);

CREATE INDEX idx_htkd_tim_kiem
ON hinh_thuc_kinh_doanh_sach (
    don_vi_id,
    phien_ban_sach_id,
    chi_nhanh_id,
    hinh_thuc,
    trang_thai
);


CREATE TABLE bang_gia_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),

    hinh_thuc_kinh_doanh_sach_id INTEGER NOT NULL,
    ma_bang_gia VARCHAR(50) NOT NULL,

    gia_niem_yet NUMERIC(18,2) NOT NULL
        CHECK (gia_niem_yet >= 0),

    gia_ban NUMERIC(18,2) NOT NULL
        CHECK (gia_ban >= 0),

    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',

    kenh_ban VARCHAR(20) NOT NULL DEFAULT 'TAT_CA'
        CHECK (
            kenh_ban IN (
                'TAT_CA',
                'TAI_QUAY',
                'TRUC_TUYEN'
            )
        ),

    ngay_bat_dau TIMESTAMPTZ NOT NULL,
    ngay_ket_thuc TIMESTAMPTZ,
    ly_do_dieu_chinh TEXT,

    trang_thai VARCHAR(24) NOT NULL DEFAULT 'CHO_AP_DUNG'
        CHECK (
            trang_thai IN (
                'CHO_AP_DUNG',
                'HIEU_LUC',
                'HET_HAN',
                'HUY'
            )
        ),

    CONSTRAINT fk_bgs_hinh_thuc
        FOREIGN KEY (
            don_vi_id,
            hinh_thuc_kinh_doanh_sach_id
        )
        REFERENCES hinh_thuc_kinh_doanh_sach(
            don_vi_id,
            id
        ),

    CONSTRAINT uq_bgs_ma
        UNIQUE (don_vi_id, ma_bang_gia),

    CONSTRAINT ck_bgs_ngay CHECK (
        ngay_ket_thuc IS NULL
        OR ngay_ket_thuc > ngay_bat_dau
    )
);

CREATE INDEX idx_bgs_hieu_luc
ON bang_gia_sach (
    don_vi_id,
    hinh_thuc_kinh_doanh_sach_id,
    kenh_ban,
    ngay_bat_dau DESC
);


-- Khoa offering khi ghi gia de tranh hai request
-- cung tao gia trung khoang thoi gian.

CREATE FUNCTION public.kiem_tra_gia_sach_khong_chong_cheo()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.trang_thai NOT IN (
        'CHO_AP_DUNG',
        'HIEU_LUC'
    ) THEN
        RETURN NEW;
    END IF;

    PERFORM 1
    FROM hinh_thuc_kinh_doanh_sach
    WHERE don_vi_id = NEW.don_vi_id
      AND id = NEW.hinh_thuc_kinh_doanh_sach_id
    FOR UPDATE;

    IF EXISTS (
        SELECT 1
        FROM bang_gia_sach b
        WHERE b.don_vi_id = NEW.don_vi_id
          AND b.hinh_thuc_kinh_doanh_sach_id =
              NEW.hinh_thuc_kinh_doanh_sach_id
          AND b.id IS DISTINCT FROM NEW.id
          AND b.trang_thai IN (
              'CHO_AP_DUNG',
              'HIEU_LUC'
          )
          AND (
              b.kenh_ban = NEW.kenh_ban
              OR b.kenh_ban = 'TAT_CA'
              OR NEW.kenh_ban = 'TAT_CA'
          )
          AND tstzrange(
              b.ngay_bat_dau,
              b.ngay_ket_thuc,
              '[)'
          ) && tstzrange(
              NEW.ngay_bat_dau,
              NEW.ngay_ket_thuc,
              '[)'
          )
    ) THEN
        RAISE EXCEPTION
            'Bang gia bi trung thoi gian hieu luc cho cung offering va kenh ban'
            USING ERRCODE = '23505';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_bang_gia_khong_chong_cheo
BEFORE INSERT OR UPDATE ON bang_gia_sach
FOR EACH ROW
EXECUTE FUNCTION public.kiem_tra_gia_sach_khong_chong_cheo();


DO $$
DECLARE
    ten_bang TEXT;
BEGIN
    FOREACH ten_bang IN ARRAY ARRAY[
        'hinh_thuc_kinh_doanh_sach',
        'bang_gia_sach'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I
             BEFORE UPDATE ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || ten_bang || '_ngay_cap_nhat',
            ten_bang
        );
    END LOOP;
END;
$$;