CREATE TABLE anh_dau_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    dau_sach_id INTEGER NOT NULL,
    tep_dinh_kem_id INTEGER NOT NULL,
    loai_anh VARCHAR(30) NOT NULL DEFAULT 'ANH_KHAC'
        CHECK (loai_anh IN (
            'BIA_TRUOC',
            'BIA_SAU',
            'GAY_SACH',
            'MUC_LUC',
            'TRANG_DOC_THU',
            'ANH_BEN_TRONG',
            'ANH_GIOI_THIEU',
            'ANH_KHAC'
        )),
    tieu_de VARCHAR(200),
    mo_ta TEXT,
    van_ban_thay_the VARCHAR(300),
    thu_tu INTEGER NOT NULL DEFAULT 0 CHECK (thu_tu >= 0),
    la_anh_chinh BOOLEAN NOT NULL DEFAULT FALSE,
    hien_thi_cong_khai BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_anh_dau_sach
        FOREIGN KEY (don_vi_id, dau_sach_id)
        REFERENCES dau_sach(don_vi_id, id)
        ON DELETE CASCADE,
    CONSTRAINT fk_anh_tep_cung_don_vi
        FOREIGN KEY (don_vi_id, tep_dinh_kem_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT uq_anh_dau_sach_tep
        UNIQUE (don_vi_id, dau_sach_id, tep_dinh_kem_id),
    CONSTRAINT uq_anh_dau_sach_tenant_id
        UNIQUE (don_vi_id, id)
);
CREATE UNIQUE INDEX uq_anh_dau_sach_chinh
ON anh_dau_sach (don_vi_id, dau_sach_id)
WHERE la_anh_chinh = TRUE;
CREATE INDEX idx_anh_dau_sach_hien_thi
ON anh_dau_sach (don_vi_id, dau_sach_id, la_anh_chinh DESC, thu_tu, id);
CREATE INDEX idx_anh_dau_sach_tep
ON anh_dau_sach (tep_dinh_kem_id);
CREATE TRIGGER trg_anh_dau_sach_ngay_cap_nhat
BEFORE UPDATE ON anh_dau_sach
FOR EACH ROW
EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat();

INSERT INTO anh_dau_sach (
    don_vi_id, dau_sach_id, tep_dinh_kem_id, loai_anh,
    thu_tu, la_anh_chinh, hien_thi_cong_khai, nguoi_tao_id
)
SELECT ds.don_vi_id, ds.id, ds.anh_bia_chinh_id, 'BIA_TRUOC',
       0, TRUE, TRUE, ds.nguoi_tao_id
FROM dau_sach ds
JOIN tep_dinh_kem t
    ON t.id = ds.anh_bia_chinh_id
   AND t.don_vi_so_huu_id = ds.don_vi_id
WHERE ds.anh_bia_chinh_id IS NOT NULL
ON CONFLICT (don_vi_id, dau_sach_id, tep_dinh_kem_id) DO NOTHING;