-- 022_nha-cung-cap.sql
CREATE TABLE nha_cung_cap (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    ma_nha_cung_cap VARCHAR(50) NOT NULL,
    ten_nha_cung_cap VARCHAR(255) NOT NULL,
    ten_phap_ly VARCHAR(255),
    ten_giao_dich VARCHAR(255),
    ten_viet_tat VARCHAR(100),
    loai_nha_cung_cap VARCHAR(30) NOT NULL DEFAULT 'DOANH_NGHIEP'
        CHECK (loai_nha_cung_cap IN ('CA_NHAN','HO_KINH_DOANH','DOANH_NGHIEP','NHA_XUAT_BAN','NHA_PHAN_PHOI','KHAC')),
    ma_so_thue VARCHAR(40),
    ma_dang_ky_kinh_doanh VARCHAR(80),
    ngay_cap_dang_ky DATE,
    noi_cap_dang_ky VARCHAR(255),
    quoc_gia CHAR(2) NOT NULL DEFAULT 'VN',
    email VARCHAR(254),
    so_dien_thoai VARCHAR(30),
    so_dien_thoai_phu VARCHAR(30),
    website TEXT,
    logo_tep_id INTEGER,
    nguoi_dai_dien_phap_luat VARCHAR(160),
    chuc_vu_dai_dien VARCHAR(120),
    nhom_nha_cung_cap VARCHAR(80),
    xep_hang_noi_bo VARCHAR(30),
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    han_muc_cong_no NUMERIC(18,2) CHECK (han_muc_cong_no >= 0),
    so_ngay_cong_no INTEGER NOT NULL DEFAULT 0 CHECK (so_ngay_cong_no >= 0),
    phuong_thuc_thanh_toan_uu_tien VARCHAR(30)
        CHECK (phuong_thuc_thanh_toan_uu_tien IN ('TIEN_MAT','CHUYEN_KHOAN','CONG_NO','KHAC')),
    thoi_gian_giao_hang_du_kien_ngay INTEGER CHECK (thoi_gian_giao_hang_du_kien_ngay >= 0),
    gia_tri_don_hang_toi_thieu NUMERIC(18,2) CHECK (gia_tri_don_hang_toi_thieu >= 0),
    cho_phep_tra_hang BOOLEAN NOT NULL DEFAULT FALSE,
    chinh_sach_doi_tra TEXT,
    chinh_sach_bao_hanh TEXT,
    dieu_khoan_hop_tac TEXT,
    ngay_bat_dau_hop_tac DATE,
    ngay_ket_thuc_hop_tac DATE,
    ghi_chu TEXT,
    ghi_chu_noi_bo TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_HOP_TAC'
        CHECK (trang_thai IN ('TIEM_NANG','DANG_HOP_TAC','TAM_NGUNG','NGUNG_HOP_TAC','DANH_SACH_DEN')),
    ly_do_ngung_hop_tac TEXT,
    ngay_ngung_hop_tac TIMESTAMPTZ,
    ngay_xoa TIMESTAMPTZ,
    CONSTRAINT uq_ncc_ma UNIQUE (don_vi_id, ma_nha_cung_cap),
    CONSTRAINT uq_ncc_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT fk_ncc_logo FOREIGN KEY (don_vi_id, logo_tep_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT ck_ncc_ngay_hop_tac CHECK (
        ngay_ket_thuc_hop_tac IS NULL OR ngay_bat_dau_hop_tac IS NULL
        OR ngay_ket_thuc_hop_tac >= ngay_bat_dau_hop_tac
    )
);
CREATE UNIQUE INDEX uq_ncc_ma_so_thue
ON nha_cung_cap (don_vi_id, ma_so_thue)
WHERE ma_so_thue IS NOT NULL AND ngay_xoa IS NULL;
CREATE INDEX idx_ncc_tim_kiem ON nha_cung_cap (don_vi_id, trang_thai, ten_nha_cung_cap);
CREATE INDEX idx_ncc_nhom ON nha_cung_cap (don_vi_id, nhom_nha_cung_cap);

CREATE TABLE dia_chi_nha_cung_cap (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    nha_cung_cap_id INTEGER NOT NULL,
    ma_dia_chi VARCHAR(50) NOT NULL,
    ten_dia_chi VARCHAR(160),
    loai_dia_chi VARCHAR(30) NOT NULL DEFAULT 'GIAO_HANG'
        CHECK (loai_dia_chi IN ('TRU_SO','GIAO_HANG','XUAT_HOA_DON','KHO','KHAC')),
    nguoi_nhan VARCHAR(160),
    so_dien_thoai VARCHAR(30),
    email VARCHAR(254),
    dia_chi_chi_tiet VARCHAR(350) NOT NULL,
    ma_tinh_thanh VARCHAR(20),
    ten_tinh_thanh VARCHAR(120),
    ma_phuong_xa VARCHAR(20),
    ten_phuong_xa VARCHAR(120),
    ma_buu_chinh VARCHAR(20),
    quoc_gia CHAR(2) NOT NULL DEFAULT 'VN',
    vi_do NUMERIC(10,7) CHECK (vi_do BETWEEN -90 AND 90),
    kinh_do NUMERIC(10,7) CHECK (kinh_do BETWEEN -180 AND 180),
    la_mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    huong_dan_giao_hang TEXT,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (trang_thai IN ('DANG_DUNG','NGUNG_DUNG')),
    CONSTRAINT fk_dcncc_ncc FOREIGN KEY (don_vi_id, nha_cung_cap_id)
        REFERENCES nha_cung_cap(don_vi_id, id),
    CONSTRAINT uq_dcncc_ma UNIQUE (don_vi_id, nha_cung_cap_id, ma_dia_chi),
    CONSTRAINT uq_dcncc_don_vi_id UNIQUE (don_vi_id, id)
);
CREATE UNIQUE INDEX uq_dcncc_mac_dinh
ON dia_chi_nha_cung_cap (don_vi_id, nha_cung_cap_id, loai_dia_chi)
WHERE la_mac_dinh = TRUE AND trang_thai = 'DANG_DUNG';

CREATE TABLE lien_he_nha_cung_cap (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    nha_cung_cap_id INTEGER NOT NULL,
    ho_ten VARCHAR(160) NOT NULL,
    chuc_vu VARCHAR(120),
    bo_phan VARCHAR(120),
    email VARCHAR(254),
    so_dien_thoai VARCHAR(30),
    so_dien_thoai_phu VARCHAR(30),
    zalo VARCHAR(100),
    kenh_lien_he_uu_tien VARCHAR(30)
        CHECK (kenh_lien_he_uu_tien IN ('DIEN_THOAI','EMAIL','ZALO','KHAC')),
    la_lien_he_chinh BOOLEAN NOT NULL DEFAULT FALSE,
    phu_trach_dat_hang BOOLEAN NOT NULL DEFAULT FALSE,
    phu_trach_cong_no BOOLEAN NOT NULL DEFAULT FALSE,
    phu_trach_giao_hang BOOLEAN NOT NULL DEFAULT FALSE,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (trang_thai IN ('DANG_DUNG','NGUNG_DUNG')),
    CONSTRAINT fk_lhncc_ncc FOREIGN KEY (don_vi_id, nha_cung_cap_id)
        REFERENCES nha_cung_cap(don_vi_id, id),
    CONSTRAINT uq_lhncc_don_vi_id UNIQUE (don_vi_id, id)
);
CREATE UNIQUE INDEX uq_lhncc_chinh
ON lien_he_nha_cung_cap (don_vi_id, nha_cung_cap_id)
WHERE la_lien_he_chinh = TRUE AND trang_thai = 'DANG_DUNG';

CREATE TABLE tai_khoan_ngan_hang_nha_cung_cap (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    nha_cung_cap_id INTEGER NOT NULL,
    ten_ngan_hang VARCHAR(200) NOT NULL,
    ma_ngan_hang VARCHAR(30),
    ma_swift VARCHAR(20),
    chi_nhanh_ngan_hang VARCHAR(200),
    so_tai_khoan VARCHAR(60) NOT NULL,
    ten_chu_tai_khoan VARCHAR(255) NOT NULL,
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    la_mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    da_xac_minh BOOLEAN NOT NULL DEFAULT FALSE,
    ngay_xac_minh TIMESTAMPTZ,
    nguoi_xac_minh_id INTEGER REFERENCES tai_khoan(id),
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (trang_thai IN ('DANG_DUNG','NGUNG_DUNG')),
    CONSTRAINT fk_tknhncc_ncc FOREIGN KEY (don_vi_id, nha_cung_cap_id)
        REFERENCES nha_cung_cap(don_vi_id, id),
    CONSTRAINT uq_tknhncc_so UNIQUE (don_vi_id, nha_cung_cap_id, ma_ngan_hang, so_tai_khoan),
    CONSTRAINT uq_tknhncc_don_vi_id UNIQUE (don_vi_id, id)
);
CREATE UNIQUE INDEX uq_tknhncc_mac_dinh
ON tai_khoan_ngan_hang_nha_cung_cap (don_vi_id, nha_cung_cap_id, don_vi_tien_te)
WHERE la_mac_dinh = TRUE AND trang_thai = 'DANG_DUNG';

CREATE TABLE hop_dong_nha_cung_cap (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    nha_cung_cap_id INTEGER NOT NULL,
    so_hop_dong VARCHAR(100) NOT NULL,
    ten_hop_dong VARCHAR(255),
    loai_hop_dong VARCHAR(30) NOT NULL DEFAULT 'CUNG_CAP'
        CHECK (loai_hop_dong IN ('CUNG_CAP','KY_GUI','PHAN_PHOI','KHUNG','KHAC')),
    ngay_ky DATE,
    ngay_hieu_luc DATE,
    ngay_het_han DATE,
    ngay_thanh_ly DATE,
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    gia_tri_hop_dong NUMERIC(18,2) CHECK (gia_tri_hop_dong >= 0),
    han_muc_cong_no NUMERIC(18,2) CHECK (han_muc_cong_no >= 0),
    so_ngay_thanh_toan INTEGER CHECK (so_ngay_thanh_toan >= 0),
    dieu_khoan_giao_hang TEXT,
    dieu_khoan_thanh_toan TEXT,
    dieu_khoan_doi_tra TEXT,
    tep_hop_dong_id INTEGER,
    nguoi_phu_trach_id INTEGER REFERENCES tai_khoan(id),
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DU_THAO'
        CHECK (trang_thai IN ('DU_THAO','CHO_DUYET','HIEU_LUC','HET_HAN','THANH_LY','HUY')),
    CONSTRAINT fk_hdncc_ncc FOREIGN KEY (don_vi_id, nha_cung_cap_id)
        REFERENCES nha_cung_cap(don_vi_id, id),
    CONSTRAINT fk_hdncc_tep FOREIGN KEY (don_vi_id, tep_hop_dong_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT uq_hdncc_so UNIQUE (don_vi_id, so_hop_dong),
    CONSTRAINT uq_hdncc_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_hdncc_ngay CHECK (
        ngay_het_han IS NULL OR ngay_hieu_luc IS NULL OR ngay_het_han >= ngay_hieu_luc
    )
);
CREATE INDEX idx_hdncc_ncc ON hop_dong_nha_cung_cap (don_vi_id, nha_cung_cap_id, trang_thai);

CREATE TABLE nha_cung_cap_phien_ban_sach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    nha_cung_cap_id INTEGER NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL,
    ma_sach_nha_cung_cap VARCHAR(100),
    ten_sach_nha_cung_cap VARCHAR(300),
    ma_vach_nha_cung_cap VARCHAR(100),
    don_vi_tinh VARCHAR(30) NOT NULL DEFAULT 'CUON',
    so_luong_moi_thung INTEGER CHECK (so_luong_moi_thung > 0),
    so_luong_dat_toi_thieu INTEGER CHECK (so_luong_dat_toi_thieu > 0),
    boi_so_dat_hang INTEGER CHECK (boi_so_dat_hang > 0),
    gia_nhap_tham_khao NUMERIC(18,2) CHECK (gia_nhap_tham_khao >= 0),
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    thue_suat_tham_khao NUMERIC(7,4) CHECK (thue_suat_tham_khao BETWEEN 0 AND 100),
    chiet_khau_tham_khao NUMERIC(7,4) CHECK (chiet_khau_tham_khao BETWEEN 0 AND 100),
    thoi_gian_cung_ung_ngay INTEGER CHECK (thoi_gian_cung_ung_ngay >= 0),
    la_nha_cung_cap_uu_tien BOOLEAN NOT NULL DEFAULT FALSE,
    ngay_bat_dau DATE,
    ngay_ket_thuc DATE,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_CUNG_UNG'
        CHECK (trang_thai IN ('DANG_CUNG_UNG','TAM_NGUNG','NGUNG_CUNG_UNG')),
    CONSTRAINT fk_nccpbs_ncc FOREIGN KEY (don_vi_id, nha_cung_cap_id)
        REFERENCES nha_cung_cap(don_vi_id, id),
    CONSTRAINT fk_nccpbs_pb FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),
    CONSTRAINT uq_nccpbs UNIQUE (don_vi_id, nha_cung_cap_id, phien_ban_sach_id),
    CONSTRAINT uq_nccpbs_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_nccpbs_ngay CHECK (
        ngay_ket_thuc IS NULL OR ngay_bat_dau IS NULL OR ngay_ket_thuc >= ngay_bat_dau
    )
);
CREATE UNIQUE INDEX uq_nccpbs_uu_tien
ON nha_cung_cap_phien_ban_sach (don_vi_id, phien_ban_sach_id)
WHERE la_nha_cung_cap_uu_tien = TRUE AND trang_thai = 'DANG_CUNG_UNG';
CREATE INDEX idx_nccpbs_phien_ban ON nha_cung_cap_phien_ban_sach (don_vi_id, phien_ban_sach_id);

DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN
        SELECT table_name FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name IN (
              'nha_cung_cap','dia_chi_nha_cung_cap','lien_he_nha_cung_cap',
              'tai_khoan_ngan_hang_nha_cung_cap','hop_dong_nha_cung_cap',
              'nha_cung_cap_phien_ban_sach'
          )
          AND column_name = 'ngay_cap_nhat'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || r.table_name || '_ngay_cap_nhat', r.table_name
        );
    END LOOP;
END $$;