-- 023_kho.sql
CREATE TABLE kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    chi_nhanh_id INTEGER NOT NULL,
    ma_kho VARCHAR(50) NOT NULL,
    ten_kho VARCHAR(200) NOT NULL,
    ten_viet_tat VARCHAR(80),
    loai_kho VARCHAR(30) NOT NULL DEFAULT 'TONG_HOP'
        CHECK (loai_kho IN (
            'TONG_HOP','BAN_HANG','DU_TRU','TRUNG_CHUYEN',
            'NHAN_HANG','TRA_HANG','CACH_LY','KY_GUI','KHAC'
        )),
    hinh_thuc_so_huu VARCHAR(30) NOT NULL DEFAULT 'SO_HUU'
        CHECK (hinh_thuc_so_huu IN ('SO_HUU','THUE','THUE_NGOAI','DOI_TAC','KHAC')),
    ma_kho_ben_ngoai VARCHAR(100),
    kho_cha_id INTEGER,
    la_kho_mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    la_kho_nhan_hang_mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    la_kho_xuat_hang_mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    cho_nhap_hang BOOLEAN NOT NULL DEFAULT TRUE,
    cho_xuat_hang BOOLEAN NOT NULL DEFAULT TRUE,
    cho_ban_hang BOOLEAN NOT NULL DEFAULT TRUE,
    cho_chuyen_kho BOOLEAN NOT NULL DEFAULT TRUE,
    cho_nhan_chuyen_kho BOOLEAN NOT NULL DEFAULT TRUE,
    cho_kiem_kho BOOLEAN NOT NULL DEFAULT TRUE,
    cho_chua_hang_hong BOOLEAN NOT NULL DEFAULT FALSE,
    cho_chua_hang_ky_gui BOOLEAN NOT NULL DEFAULT FALSE,
    cho_ton_am BOOLEAN NOT NULL DEFAULT FALSE,
    yeu_cau_vi_tri_khi_nhap BOOLEAN NOT NULL DEFAULT TRUE,
    yeu_cau_vi_tri_khi_xuat BOOLEAN NOT NULL DEFAULT TRUE,
    yeu_cau_kiem_nhan_khi_nhap BOOLEAN NOT NULL DEFAULT TRUE,
    yeu_cau_phe_duyet_dieu_chinh BOOLEAN NOT NULL DEFAULT TRUE,
    phuong_phap_xuat_kho VARCHAR(20) NOT NULL DEFAULT 'FIFO'
        CHECK (phuong_phap_xuat_kho IN ('FIFO','FEFO','THU_CONG')),
    nguong_canh_bao_suc_chua_phan_tram NUMERIC(5,2) NOT NULL DEFAULT 90
        CHECK (nguong_canh_bao_suc_chua_phan_tram BETWEEN 0 AND 100),
    suc_chua_toi_da_cuon INTEGER CHECK (suc_chua_toi_da_cuon > 0),
    suc_chua_toi_da_kg NUMERIC(15,3) CHECK (suc_chua_toi_da_kg > 0),
    dien_tich_m2 NUMERIC(15,3) CHECK (dien_tich_m2 > 0),
    dien_tich_su_dung_m2 NUMERIC(15,3) CHECK (dien_tich_su_dung_m2 > 0),
    chieu_cao_su_dung_m NUMERIC(10,3) CHECK (chieu_cao_su_dung_m > 0),
    the_tich_su_dung_m3 NUMERIC(15,3) CHECK (the_tich_su_dung_m3 > 0),
    nhiet_do_toi_thieu_c NUMERIC(6,2),
    nhiet_do_toi_da_c NUMERIC(6,2),
    do_am_toi_thieu_phan_tram NUMERIC(5,2)
        CHECK (do_am_toi_thieu_phan_tram BETWEEN 0 AND 100),
    do_am_toi_da_phan_tram NUMERIC(5,2)
        CHECK (do_am_toi_da_phan_tram BETWEEN 0 AND 100),
    co_dieu_hoa BOOLEAN NOT NULL DEFAULT FALSE,
    co_hut_am BOOLEAN NOT NULL DEFAULT FALSE,
    co_he_thong_chua_chay BOOLEAN NOT NULL DEFAULT FALSE,
    co_camera BOOLEAN NOT NULL DEFAULT FALSE,
    co_kiem_soat_ra_vao BOOLEAN NOT NULL DEFAULT FALSE,
    co_cam_bien_nhiet_do BOOLEAN NOT NULL DEFAULT FALSE,
    co_cam_bien_do_am BOOLEAN NOT NULL DEFAULT FALSE,
    ma_cam_bien VARCHAR(100),
    dia_chi_chi_tiet VARCHAR(350),
    ma_tinh_thanh VARCHAR(20),
    ten_tinh_thanh VARCHAR(120),
    ma_phuong_xa VARCHAR(20),
    ten_phuong_xa VARCHAR(120),
    ma_buu_chinh VARCHAR(20),
    quoc_gia CHAR(2) NOT NULL DEFAULT 'VN',
    vi_do NUMERIC(10,7) CHECK (vi_do BETWEEN -90 AND 90),
    kinh_do NUMERIC(10,7) CHECK (kinh_do BETWEEN -180 AND 180),
    huong_dan_duong_di TEXT,
    huong_dan_boc_do TEXT,
    cong_nhap_hang VARCHAR(80),
    cong_xuat_hang VARCHAR(80),
    so_dien_thoai VARCHAR(30),
    email VARCHAR(254),
    nguoi_quan_ly_id INTEGER REFERENCES tai_khoan(id),
    nguoi_phu_trach_nhap_id INTEGER REFERENCES tai_khoan(id),
    nguoi_phu_trach_xuat_id INTEGER REFERENCES tai_khoan(id),
    gio_mo_cua TIME,
    gio_dong_cua TIME,
    lich_lam_viec JSONB NOT NULL DEFAULT '{}'::jsonb,
    ngay_bat_dau_hoat_dong DATE,
    ngay_ngung_hoat_dong DATE,
    ly_do_ngung_hoat_dong TEXT,
    anh_dai_dien_tep_id INTEGER,
    so_do_kho_tep_id INTEGER,
    quy_trinh_bao_quan TEXT,
    quy_trinh_an_toan TEXT,
    ghi_chu TEXT,
    ghi_chu_noi_bo TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_HOAT_DONG'
        CHECK (trang_thai IN ('CHUAN_BI','DANG_HOAT_DONG','TAM_KHOA','DANG_KIEM_KE','NGUNG_HOAT_DONG')),
    ngay_xoa TIMESTAMPTZ,
    CONSTRAINT fk_kho_chi_nhanh FOREIGN KEY (don_vi_id, chi_nhanh_id)
        REFERENCES chi_nhanh(don_vi_id, id),
    CONSTRAINT fk_kho_cha FOREIGN KEY (don_vi_id, kho_cha_id)
        REFERENCES kho(don_vi_id, id),
    CONSTRAINT fk_kho_anh FOREIGN KEY (don_vi_id, anh_dai_dien_tep_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT fk_kho_so_do FOREIGN KEY (don_vi_id, so_do_kho_tep_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT uq_kho_ma UNIQUE (don_vi_id, ma_kho),
    CONSTRAINT uq_kho_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT uq_kho_chi_nhanh_id UNIQUE (don_vi_id, chi_nhanh_id, id),
    CONSTRAINT ck_kho_khong_tu_lam_cha CHECK (kho_cha_id IS NULL OR kho_cha_id <> id),
    CONSTRAINT ck_kho_suc_chua CHECK (
        dien_tich_su_dung_m2 IS NULL OR dien_tich_m2 IS NULL
        OR dien_tich_su_dung_m2 <= dien_tich_m2
    ),
    CONSTRAINT ck_kho_nhiet_do CHECK (
        nhiet_do_toi_thieu_c IS NULL OR nhiet_do_toi_da_c IS NULL
        OR nhiet_do_toi_thieu_c <= nhiet_do_toi_da_c
    ),
    CONSTRAINT ck_kho_do_am CHECK (
        do_am_toi_thieu_phan_tram IS NULL OR do_am_toi_da_phan_tram IS NULL
        OR do_am_toi_thieu_phan_tram <= do_am_toi_da_phan_tram
    ),
    CONSTRAINT ck_kho_ngay CHECK (
        ngay_ngung_hoat_dong IS NULL OR ngay_bat_dau_hoat_dong IS NULL
        OR ngay_ngung_hoat_dong >= ngay_bat_dau_hoat_dong
    )
);
CREATE INDEX idx_kho_chi_nhanh ON kho (don_vi_id, chi_nhanh_id, trang_thai);
CREATE INDEX idx_kho_cha ON kho (don_vi_id, kho_cha_id);
CREATE UNIQUE INDEX uq_kho_mac_dinh
ON kho (don_vi_id, chi_nhanh_id)
WHERE la_kho_mac_dinh = TRUE AND ngay_xoa IS NULL;
CREATE UNIQUE INDEX uq_kho_nhan_mac_dinh
ON kho (don_vi_id, chi_nhanh_id)
WHERE la_kho_nhan_hang_mac_dinh = TRUE AND ngay_xoa IS NULL;
CREATE UNIQUE INDEX uq_kho_xuat_mac_dinh
ON kho (don_vi_id, chi_nhanh_id)
WHERE la_kho_xuat_hang_mac_dinh = TRUE AND ngay_xoa IS NULL;

CREATE TABLE khu_vuc_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    kho_id INTEGER NOT NULL,
    ma_khu_vuc VARCHAR(50) NOT NULL,
    ten_khu_vuc VARCHAR(160) NOT NULL,
    loai_khu_vuc VARCHAR(30) NOT NULL DEFAULT 'LUU_TRU'
        CHECK (loai_khu_vuc IN (
            'TIEP_NHAN','KIEM_NHAN','LUU_TRU','SOAN_HANG','DONG_GOI',
            'CHO_XUAT','TRA_HANG','CACH_LY','HANG_HONG','KY_GUI','KHAC'
        )),
    tang VARCHAR(30),
    toa_nha VARCHAR(80),
    dien_tich_m2 NUMERIC(15,3) CHECK (dien_tich_m2 > 0),
    suc_chua_toi_da_cuon INTEGER CHECK (suc_chua_toi_da_cuon > 0),
    suc_chua_toi_da_kg NUMERIC(15,3) CHECK (suc_chua_toi_da_kg > 0),
    nhiet_do_toi_thieu_c NUMERIC(6,2),
    nhiet_do_toi_da_c NUMERIC(6,2),
    do_am_toi_thieu_phan_tram NUMERIC(5,2) CHECK (do_am_toi_thieu_phan_tram BETWEEN 0 AND 100),
    do_am_toi_da_phan_tram NUMERIC(5,2) CHECK (do_am_toi_da_phan_tram BETWEEN 0 AND 100),
    cho_nhap BOOLEAN NOT NULL DEFAULT TRUE,
    cho_xuat BOOLEAN NOT NULL DEFAULT TRUE,
    cho_ban BOOLEAN NOT NULL DEFAULT TRUE,
    cho_chua_hang_hong BOOLEAN NOT NULL DEFAULT FALSE,
    thu_tu INTEGER NOT NULL DEFAULT 0,
    mo_ta TEXT,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (trang_thai IN ('DANG_DUNG','TAM_KHOA','NGUNG_DUNG')),
    CONSTRAINT fk_kvk_kho FOREIGN KEY (don_vi_id, kho_id) REFERENCES kho(don_vi_id, id),
    CONSTRAINT uq_kvk_ma UNIQUE (don_vi_id, kho_id, ma_khu_vuc),
    CONSTRAINT uq_kvk_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT uq_kvk_kho_id UNIQUE (don_vi_id, kho_id, id),
    CONSTRAINT ck_kvk_nhiet_do CHECK (
        nhiet_do_toi_thieu_c IS NULL OR nhiet_do_toi_da_c IS NULL
        OR nhiet_do_toi_thieu_c <= nhiet_do_toi_da_c
    ),
    CONSTRAINT ck_kvk_do_am CHECK (
        do_am_toi_thieu_phan_tram IS NULL OR do_am_toi_da_phan_tram IS NULL
        OR do_am_toi_thieu_phan_tram <= do_am_toi_da_phan_tram
    )
);

CREATE TABLE vi_tri_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    kho_id INTEGER NOT NULL,
    khu_vuc_kho_id INTEGER NOT NULL,
    vi_tri_cha_id INTEGER,
    ma_vi_tri VARCHAR(80) NOT NULL,
    ten_vi_tri VARCHAR(160),
    ma_vach VARCHAR(120),
    loai_vi_tri VARCHAR(30) NOT NULL DEFAULT 'O_KE'
        CHECK (loai_vi_tri IN ('DAY','KE','TANG_KE','O_KE','PALLET','THUNG','SAN','KHAC')),
    day_ke VARCHAR(50),
    so_ke VARCHAR(50),
    tang_ke VARCHAR(50),
    so_o VARCHAR(50),
    toa_do_x INTEGER,
    toa_do_y INTEGER,
    toa_do_z INTEGER,
    chieu_dai_cm NUMERIC(12,2) CHECK (chieu_dai_cm > 0),
    chieu_rong_cm NUMERIC(12,2) CHECK (chieu_rong_cm > 0),
    chieu_cao_cm NUMERIC(12,2) CHECK (chieu_cao_cm > 0),
    suc_chua_toi_da_cuon INTEGER CHECK (suc_chua_toi_da_cuon > 0),
    suc_chua_toi_da_kg NUMERIC(15,3) CHECK (suc_chua_toi_da_kg > 0),
    la_vi_tri_mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    cho_nhap BOOLEAN NOT NULL DEFAULT TRUE,
    cho_xuat BOOLEAN NOT NULL DEFAULT TRUE,
    cho_chua_hang_hong BOOLEAN NOT NULL DEFAULT FALSE,
    cho_tron_phien_ban BOOLEAN NOT NULL DEFAULT TRUE,
    thu_tu_lay_hang INTEGER NOT NULL DEFAULT 0,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (trang_thai IN ('DANG_DUNG','DAY','TAM_KHOA','NGUNG_DUNG')),
    CONSTRAINT fk_vtk_kho FOREIGN KEY (don_vi_id, kho_id) REFERENCES kho(don_vi_id, id),
    CONSTRAINT fk_vtk_khu_vuc FOREIGN KEY (don_vi_id, kho_id, khu_vuc_kho_id)
        REFERENCES khu_vuc_kho(don_vi_id, kho_id, id),
    CONSTRAINT fk_vtk_cha FOREIGN KEY (don_vi_id, kho_id, vi_tri_cha_id)
        REFERENCES vi_tri_kho(don_vi_id, kho_id, id),
    CONSTRAINT uq_vtk_ma UNIQUE (don_vi_id, kho_id, ma_vi_tri),
    CONSTRAINT uq_vtk_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT uq_vtk_kho_id UNIQUE (don_vi_id, kho_id, id),
    CONSTRAINT ck_vtk_khong_tu_lam_cha CHECK (vi_tri_cha_id IS NULL OR vi_tri_cha_id <> id)
);
CREATE UNIQUE INDEX uq_vtk_ma_vach
ON vi_tri_kho (don_vi_id, ma_vach) WHERE ma_vach IS NOT NULL;
CREATE UNIQUE INDEX uq_vtk_mac_dinh
ON vi_tri_kho (don_vi_id, kho_id)
WHERE la_vi_tri_mac_dinh = TRUE AND trang_thai = 'DANG_DUNG';
CREATE INDEX idx_vtk_khu_vuc ON vi_tri_kho (don_vi_id, kho_id, khu_vuc_kho_id);
CREATE INDEX idx_vtk_lay_hang ON vi_tri_kho (don_vi_id, kho_id, trang_thai, thu_tu_lay_hang);

CREATE TABLE nhan_su_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    kho_id INTEGER NOT NULL,
    tai_khoan_id INTEGER NOT NULL REFERENCES tai_khoan(id),
    vai_tro_tai_kho VARCHAR(30) NOT NULL
        CHECK (vai_tro_tai_kho IN ('QUAN_LY','THU_KHO','NHAP_HANG','XUAT_HANG','KIEM_KE','GIAM_SAT','KHAC')),
    la_nguoi_phu_trach_chinh BOOLEAN NOT NULL DEFAULT FALSE,
    cho_nhap BOOLEAN NOT NULL DEFAULT FALSE,
    cho_xuat BOOLEAN NOT NULL DEFAULT FALSE,
    cho_dieu_chuyen BOOLEAN NOT NULL DEFAULT FALSE,
    cho_kiem_ke BOOLEAN NOT NULL DEFAULT FALSE,
    cho_dieu_chinh_ton BOOLEAN NOT NULL DEFAULT FALSE,
    ngay_bat_dau DATE NOT NULL DEFAULT CURRENT_DATE,
    ngay_ket_thuc DATE,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_PHAN_CONG'
        CHECK (trang_thai IN ('DANG_PHAN_CONG','TAM_DUNG','KET_THUC')),
    CONSTRAINT fk_nsk_kho FOREIGN KEY (don_vi_id, kho_id) REFERENCES kho(don_vi_id, id),
    CONSTRAINT uq_nsk UNIQUE (don_vi_id, kho_id, tai_khoan_id, vai_tro_tai_kho),
    CONSTRAINT ck_nsk_ngay CHECK (ngay_ket_thuc IS NULL OR ngay_ket_thuc >= ngay_bat_dau)
);
CREATE INDEX idx_nsk_tai_khoan ON nhan_su_kho (don_vi_id, tai_khoan_id, trang_thai);

CREATE TABLE thiet_bi_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    kho_id INTEGER NOT NULL,
    khu_vuc_kho_id INTEGER,
    ma_thiet_bi VARCHAR(80) NOT NULL,
    ten_thiet_bi VARCHAR(200) NOT NULL,
    loai_thiet_bi VARCHAR(40) NOT NULL
        CHECK (loai_thiet_bi IN (
            'CAM_BIEN_NHIET_DO','CAM_BIEN_DO_AM','CAMERA','MAY_QUET_MA_VACH',
            'MAY_IN_TEM','CAN','DIEU_HOA','HUT_AM','CHUA_CHAY','KHAC'
        )),
    hang_san_xuat VARCHAR(160),
    model VARCHAR(120),
    so_serial VARCHAR(120),
    ma_tai_san VARCHAR(100),
    ngay_mua DATE,
    ngay_lap_dat DATE,
    ngay_het_bao_hanh DATE,
    ngay_bao_tri_gan_nhat DATE,
    ngay_bao_tri_tiep_theo DATE,
    chu_ky_bao_tri_ngay INTEGER CHECK (chu_ky_bao_tri_ngay > 0),
    don_vi_bao_tri VARCHAR(200),
    thong_so_ky_thuat JSONB NOT NULL DEFAULT '{}'::jsonb,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_SU_DUNG'
        CHECK (trang_thai IN ('DU_PHONG','DANG_SU_DUNG','DANG_BAO_TRI','HONG','NGUNG_SU_DUNG')),
    CONSTRAINT fk_tbk_kho FOREIGN KEY (don_vi_id, kho_id) REFERENCES kho(don_vi_id, id),
    CONSTRAINT fk_tbk_khu_vuc FOREIGN KEY (don_vi_id, kho_id, khu_vuc_kho_id)
        REFERENCES khu_vuc_kho(don_vi_id, kho_id, id),
    CONSTRAINT uq_tbk_ma UNIQUE (don_vi_id, ma_thiet_bi)
);
ALTER TABLE thiet_bi_kho ADD CONSTRAINT uq_tbk_don_vi_id UNIQUE (don_vi_id, id);
CREATE INDEX idx_tbk_bao_tri ON thiet_bi_kho (don_vi_id, ngay_bao_tri_tiep_theo)
WHERE trang_thai = 'DANG_SU_DUNG';

CREATE TABLE nhat_ky_dieu_kien_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    kho_id INTEGER NOT NULL,
    khu_vuc_kho_id INTEGER,
    thiet_bi_kho_id INTEGER,
    thoi_diem_do TIMESTAMPTZ NOT NULL DEFAULT now(),
    nhiet_do_c NUMERIC(6,2),
    do_am_phan_tram NUMERIC(5,2) CHECK (do_am_phan_tram BETWEEN 0 AND 100),
    nguon_do VARCHAR(24) NOT NULL DEFAULT 'THU_CONG'
        CHECK (nguon_do IN ('THU_CONG','CAM_BIEN','NHAP_DU_LIEU')),
    vuot_nguong BOOLEAN NOT NULL DEFAULT FALSE,
    noi_dung_canh_bao TEXT,
    bien_phap_xu_ly TEXT,
    nguoi_xu_ly_id INTEGER REFERENCES tai_khoan(id),
    ngay_xu_ly TIMESTAMPTZ,
    ghi_chu TEXT,
    CONSTRAINT fk_njdk_kho FOREIGN KEY (don_vi_id, kho_id) REFERENCES kho(don_vi_id, id),
    CONSTRAINT fk_njdk_khu_vuc FOREIGN KEY (don_vi_id, kho_id, khu_vuc_kho_id)
        REFERENCES khu_vuc_kho(don_vi_id, kho_id, id),
    CONSTRAINT fk_njdk_thiet_bi FOREIGN KEY (don_vi_id, thiet_bi_kho_id)
        REFERENCES thiet_bi_kho(don_vi_id, id)
);
CREATE INDEX idx_njdk_thoi_gian ON nhat_ky_dieu_kien_kho (don_vi_id, kho_id, thoi_diem_do DESC);

CREATE TABLE tai_lieu_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    kho_id INTEGER NOT NULL,
    tep_dinh_kem_id INTEGER NOT NULL,
    loai_tai_lieu VARCHAR(40) NOT NULL
        CHECK (loai_tai_lieu IN ('SO_DO','HINH_ANH','HOP_DONG_THUE','PCCC','QUY_TRINH','BIEN_BAN','KHAC')),
    ten_tai_lieu VARCHAR(200) NOT NULL,
    mo_ta TEXT,
    thu_tu INTEGER NOT NULL DEFAULT 0,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (trang_thai IN ('DANG_DUNG','NGUNG_DUNG')),
    CONSTRAINT fk_tlk_kho FOREIGN KEY (don_vi_id, kho_id) REFERENCES kho(don_vi_id, id),
    CONSTRAINT fk_tlk_tep FOREIGN KEY (don_vi_id, tep_dinh_kem_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT uq_tlk UNIQUE (don_vi_id, kho_id, tep_dinh_kem_id)
);

DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN
        SELECT table_name FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name IN (
              'kho','khu_vuc_kho','vi_tri_kho','nhan_su_kho',
              'thiet_bi_kho','nhat_ky_dieu_kien_kho','tai_lieu_kho'
          )
          AND column_name = 'ngay_cap_nhat'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || r.table_name || '_ngay_cap_nhat', r.table_name
        );
    END LOOP;
END $$;