-- 024_nhap-kho.sql
CREATE TABLE phieu_nhap_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    ma_phieu VARCHAR(60) NOT NULL,
    loai_nhap VARCHAR(30) NOT NULL
        CHECK (loai_nhap IN ('NHA_CUNG_CAP','TRA_HANG','DIEU_CHUYEN','TON_DAU_KY','DIEU_CHINH','KHAC')),
    chi_nhanh_id INTEGER NOT NULL,
    kho_id INTEGER NOT NULL,
    nha_cung_cap_id INTEGER,
    hop_dong_nha_cung_cap_id INTEGER,
    so_don_dat_hang VARCHAR(100),
    so_phieu_giao_hang VARCHAR(100),
    so_hoa_don VARCHAR(100),
    ngay_hoa_don DATE,
    ngay_chung_tu DATE,
    ngay_du_kien_nhan TIMESTAMPTZ,
    ngay_thuc_nhan TIMESTAMPTZ,
    ngay_hoan_tat TIMESTAMPTZ,
    nguoi_giao_hang VARCHAR(160),
    so_dien_thoai_nguoi_giao VARCHAR(30),
    don_vi_van_chuyen VARCHAR(200),
    ma_van_don VARCHAR(120),
    bien_so_xe VARCHAR(30),
    nguoi_nhan_id INTEGER REFERENCES tai_khoan(id),
    nguoi_kiem_nhan_id INTEGER REFERENCES tai_khoan(id),
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ngay_duyet TIMESTAMPTZ,
    nguoi_hoan_tat_id INTEGER REFERENCES tai_khoan(id),
    tong_so_dong INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_dong >= 0),
    tong_so_luong_du_kien INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_du_kien >= 0),
    tong_so_luong_thuc_nhan INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_thuc_nhan >= 0),
    tong_so_luong_dat INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_dat >= 0),
    tong_so_luong_loi INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_loi >= 0),
    tong_tien_hang NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tong_tien_hang >= 0),
    tong_chiet_khau NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tong_chiet_khau >= 0),
    tong_thue NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tong_thue >= 0),
    tong_chi_phi_nhap NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tong_chi_phi_nhap >= 0),
    tong_thanh_tien NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tong_thanh_tien >= 0),
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    ty_gia NUMERIC(18,6) NOT NULL DEFAULT 1 CHECK (ty_gia > 0),
    ghi_chu TEXT,
    ghi_chu_noi_bo TEXT,
    ly_do_huy TEXT,
    ngay_huy TIMESTAMPTZ,
    nguoi_huy_id INTEGER REFERENCES tai_khoan(id),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'NHAP'
        CHECK (trang_thai IN ('NHAP','CHO_NHAN','DANG_KIEM_NHAN','CHO_DUYET','DA_DUYET','HOAN_TAT','TU_CHOI','DA_HUY')),
    CONSTRAINT fk_pnk_kho FOREIGN KEY (don_vi_id, chi_nhanh_id, kho_id)
        REFERENCES kho(don_vi_id, chi_nhanh_id, id),
    CONSTRAINT fk_pnk_ncc FOREIGN KEY (don_vi_id, nha_cung_cap_id)
        REFERENCES nha_cung_cap(don_vi_id, id),
    CONSTRAINT fk_pnk_hop_dong FOREIGN KEY (don_vi_id, hop_dong_nha_cung_cap_id)
        REFERENCES hop_dong_nha_cung_cap(don_vi_id, id),
    CONSTRAINT uq_pnk_ma UNIQUE (don_vi_id, ma_phieu),
    CONSTRAINT uq_pnk_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_pnk_ncc CHECK (loai_nhap <> 'NHA_CUNG_CAP' OR nha_cung_cap_id IS NOT NULL)
);
CREATE INDEX idx_pnk_kho ON phieu_nhap_kho (don_vi_id, kho_id, trang_thai, ngay_tao DESC);
CREATE INDEX idx_pnk_ncc ON phieu_nhap_kho (don_vi_id, nha_cung_cap_id, ngay_tao DESC);

CREATE TABLE chi_tiet_phieu_nhap_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    phieu_nhap_kho_id INTEGER NOT NULL,
    so_dong INTEGER NOT NULL CHECK (so_dong > 0),
    phien_ban_sach_id INTEGER NOT NULL,
    vi_tri_kho_id INTEGER,
    ma_sach_nha_cung_cap VARCHAR(100),
    so_lo VARCHAR(100),
    ngay_san_xuat DATE,
    ngay_het_han DATE,
    so_luong_du_kien INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_du_kien >= 0),
    so_luong_thuc_nhan INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_thuc_nhan >= 0),
    so_luong_dat INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_dat >= 0),
    so_luong_hong INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_hong >= 0),
    so_luong_thieu INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_thieu >= 0),
    so_luong_thua INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_thua >= 0),
    don_vi_tinh VARCHAR(30) NOT NULL DEFAULT 'CUON',
    don_gia_nhap NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (don_gia_nhap >= 0),
    ty_le_chiet_khau NUMERIC(7,4) NOT NULL DEFAULT 0 CHECK (ty_le_chiet_khau BETWEEN 0 AND 100),
    tien_chiet_khau NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_chiet_khau >= 0),
    thue_suat NUMERIC(7,4) NOT NULL DEFAULT 0 CHECK (thue_suat BETWEEN 0 AND 100),
    tien_thue NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_thue >= 0),
    chi_phi_phan_bo NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (chi_phi_phan_bo >= 0),
    thanh_tien NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (thanh_tien >= 0),
    gia_von_don_vi NUMERIC(18,4) CHECK (gia_von_don_vi >= 0),
    tinh_trang_sach VARCHAR(30) NOT NULL DEFAULT 'MOI'
        CHECK (tinh_trang_sach IN ('MOI','DA_SU_DUNG','HONG_NHE','HONG_NANG','KHAC')),
    ghi_chu_kiem_nhan TEXT,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'CHO_KIEM_NHAN'
        CHECK (trang_thai IN ('CHO_KIEM_NHAN','DA_KIEM_NHAN','TU_CHOI','DA_NHAP')),
    CONSTRAINT fk_ctpnk_phieu FOREIGN KEY (don_vi_id, phieu_nhap_kho_id)
        REFERENCES phieu_nhap_kho(don_vi_id, id),
    CONSTRAINT fk_ctpnk_pb FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),
    CONSTRAINT fk_ctpnk_vi_tri FOREIGN KEY (don_vi_id, vi_tri_kho_id)
        REFERENCES vi_tri_kho(don_vi_id, id),
    CONSTRAINT uq_ctpnk_dong UNIQUE (don_vi_id, phieu_nhap_kho_id, so_dong),
    CONSTRAINT uq_ctpnk_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_ctpnk_so_luong CHECK (
        so_luong_dat + so_luong_hong <= so_luong_thuc_nhan
        AND so_luong_thieu >= GREATEST(so_luong_du_kien - so_luong_thuc_nhan, 0)
    ),
    CONSTRAINT ck_ctpnk_ngay CHECK (
        ngay_het_han IS NULL OR ngay_san_xuat IS NULL OR ngay_het_han >= ngay_san_xuat
    )
);
CREATE INDEX idx_ctpnk_pb ON chi_tiet_phieu_nhap_kho (don_vi_id, phien_ban_sach_id);

CREATE TABLE kiem_nhan_nhap_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    chi_tiet_phieu_nhap_kho_id INTEGER NOT NULL,
    lan_kiem_nhan INTEGER NOT NULL DEFAULT 1 CHECK (lan_kiem_nhan > 0),
    nguoi_kiem_nhan_id INTEGER REFERENCES tai_khoan(id),
    thoi_diem_kiem_nhan TIMESTAMPTZ NOT NULL DEFAULT now(),
    so_luong_kiem INTEGER NOT NULL CHECK (so_luong_kiem > 0),
    so_luong_dat INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_dat >= 0),
    so_luong_hong INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_hong >= 0),
    so_luong_sai_phien_ban INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_sai_phien_ban >= 0),
    loai_loi VARCHAR(40),
    mo_ta_loi TEXT,
    huong_xu_ly VARCHAR(30)
        CHECK (huong_xu_ly IN ('NHAP_KHO','CACH_LY','TRA_NHA_CUNG_CAP','CHO_XU_LY')),
    anh_bang_chung_tep_id INTEGER,
    ghi_chu TEXT,
    CONSTRAINT fk_knnk_chi_tiet FOREIGN KEY (don_vi_id, chi_tiet_phieu_nhap_kho_id)
        REFERENCES chi_tiet_phieu_nhap_kho(don_vi_id, id),
    CONSTRAINT fk_knnk_anh FOREIGN KEY (don_vi_id, anh_bang_chung_tep_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT uq_knnk_lan UNIQUE (don_vi_id, chi_tiet_phieu_nhap_kho_id, lan_kiem_nhan),
    CONSTRAINT ck_knnk_so_luong CHECK (
        so_luong_dat + so_luong_hong + so_luong_sai_phien_ban <= so_luong_kiem
    )
);

CREATE TABLE tep_phieu_nhap_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    phieu_nhap_kho_id INTEGER NOT NULL,
    tep_dinh_kem_id INTEGER NOT NULL,
    loai_tai_lieu VARCHAR(40) NOT NULL
        CHECK (loai_tai_lieu IN ('PHIEU_GIAO','HOA_DON','BIEN_BAN','ANH_HANG','CHUNG_TU_KHAC')),
    ten_tai_lieu VARCHAR(200),
    ghi_chu TEXT,
    CONSTRAINT fk_tpnk_phieu FOREIGN KEY (don_vi_id, phieu_nhap_kho_id)
        REFERENCES phieu_nhap_kho(don_vi_id, id),
    CONSTRAINT fk_tpnk_tep FOREIGN KEY (don_vi_id, tep_dinh_kem_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT uq_tpnk UNIQUE (don_vi_id, phieu_nhap_kho_id, tep_dinh_kem_id)
);

DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN
        SELECT table_name FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name IN (
              'phieu_nhap_kho','chi_tiet_phieu_nhap_kho',
              'kiem_nhan_nhap_kho','tep_phieu_nhap_kho'
          )
          AND column_name = 'ngay_cap_nhat'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || r.table_name || '_ngay_cap_nhat', r.table_name
        );
    END LOOP;
END $$;