-- 025_ton-kho.sql
CREATE TABLE lo_ton_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    ma_lo VARCHAR(100) NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL,
    nha_cung_cap_id INTEGER,
    chi_tiet_phieu_nhap_kho_id INTEGER,
    ngay_nhap_dau_tien TIMESTAMPTZ,
    ngay_san_xuat DATE,
    ngay_het_han DATE,
    gia_von_don_vi NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (gia_von_don_vi >= 0),
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    tinh_trang_sach VARCHAR(30) NOT NULL DEFAULT 'MOI'
        CHECK (tinh_trang_sach IN ('MOI','DA_SU_DUNG','HONG_NHE','HONG_NANG','KHAC')),
    loai_so_huu VARCHAR(24) NOT NULL DEFAULT 'SO_HUU'
        CHECK (loai_so_huu IN ('SO_HUU','KY_GUI','MUON','KHAC')),
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (trang_thai IN ('DANG_DUNG','TAM_KHOA','DA_DONG')),
    CONSTRAINT fk_ltk_pb FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),
    CONSTRAINT fk_ltk_ncc FOREIGN KEY (don_vi_id, nha_cung_cap_id)
        REFERENCES nha_cung_cap(don_vi_id, id),
    CONSTRAINT fk_ltk_nhap FOREIGN KEY (don_vi_id, chi_tiet_phieu_nhap_kho_id)
        REFERENCES chi_tiet_phieu_nhap_kho(don_vi_id, id),
    CONSTRAINT uq_ltk_ma UNIQUE (don_vi_id, ma_lo),
    CONSTRAINT uq_ltk_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT uq_ltk_phien_ban UNIQUE (don_vi_id, phien_ban_sach_id, id),
    CONSTRAINT ck_ltk_ngay CHECK (
        ngay_het_han IS NULL OR ngay_san_xuat IS NULL OR ngay_het_han >= ngay_san_xuat
    )
);

CREATE TABLE ton_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    kho_id INTEGER NOT NULL,
    vi_tri_kho_id INTEGER NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL,
    lo_ton_kho_id INTEGER NOT NULL,
    so_luong_thuc_te INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_thuc_te >= 0),
    so_luong_giu_cho INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_giu_cho >= 0),
    so_luong_cach_ly INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_cach_ly >= 0),
    so_luong_hong INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_hong >= 0),
    so_luong_cho_xuat INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_cho_xuat >= 0),
    so_luong_dang_chuyen INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_dang_chuyen >= 0),
    so_luong_kha_dung INTEGER GENERATED ALWAYS AS (
        so_luong_thuc_te - so_luong_giu_cho - so_luong_cach_ly
        - so_luong_hong - so_luong_cho_xuat - so_luong_dang_chuyen
    ) STORED,
    gia_von_don_vi NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (gia_von_don_vi >= 0),
    ngay_nhap_gan_nhat TIMESTAMPTZ,
    ngay_xuat_gan_nhat TIMESTAMPTZ,
    ngay_kiem_ke_gan_nhat TIMESTAMPTZ,
    phien_ban_du_lieu BIGINT NOT NULL DEFAULT 0 CHECK (phien_ban_du_lieu >= 0),
    CONSTRAINT fk_tk_kho FOREIGN KEY (don_vi_id, kho_id) REFERENCES kho(don_vi_id, id),
    CONSTRAINT fk_tk_vi_tri FOREIGN KEY (don_vi_id, kho_id, vi_tri_kho_id)
        REFERENCES vi_tri_kho(don_vi_id, kho_id, id),
    CONSTRAINT fk_tk_lo_pb FOREIGN KEY (don_vi_id, phien_ban_sach_id, lo_ton_kho_id)
        REFERENCES lo_ton_kho(don_vi_id, phien_ban_sach_id, id),
    CONSTRAINT uq_tk_toa_do UNIQUE (
        don_vi_id, kho_id, vi_tri_kho_id, phien_ban_sach_id, lo_ton_kho_id
    ),
    CONSTRAINT uq_tk_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_tk_kha_dung CHECK (
        so_luong_giu_cho + so_luong_cach_ly + so_luong_hong
        + so_luong_cho_xuat + so_luong_dang_chuyen <= so_luong_thuc_te
    )
);
CREATE INDEX idx_tk_phien_ban ON ton_kho (don_vi_id, phien_ban_sach_id, kho_id);
CREATE INDEX idx_tk_kho_vi_tri ON ton_kho (don_vi_id, kho_id, vi_tri_kho_id);
CREATE INDEX idx_tk_kha_dung ON ton_kho (don_vi_id, kho_id, phien_ban_sach_id)
WHERE so_luong_thuc_te > 0;

CREATE TABLE bien_dong_ton_kho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    ma_giao_dich VARCHAR(100) NOT NULL,
    ton_kho_id INTEGER NOT NULL,
    kho_id INTEGER NOT NULL,
    vi_tri_kho_id INTEGER NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL,
    lo_ton_kho_id INTEGER NOT NULL,
    loai_bien_dong VARCHAR(40) NOT NULL
        CHECK (loai_bien_dong IN (
            'NHAP_NHA_CUNG_CAP','NHAP_TRA_HANG','NHAP_TON_DAU_KY',
            'XUAT_BAN','XUAT_TRA_NHA_CUNG_CAP','XUAT_HUY',
            'CHUYEN_KHO_DI','CHUYEN_KHO_DEN','CHUYEN_VI_TRI_DI','CHUYEN_VI_TRI_DEN',
            'KIEM_KE_TANG','KIEM_KE_GIAM','DIEU_CHINH_TANG','DIEU_CHINH_GIAM',
            'GIU_CHO','BO_GIU_CHO','CACH_LY','BO_CACH_LY',
            'DANH_DAU_HONG','BO_DANH_DAU_HONG','CHO_XUAT','BO_CHO_XUAT',
            'BAT_DAU_CHUYEN','KET_THUC_CHUYEN','KHAC'
        )),
    nguon_chung_tu VARCHAR(40) NOT NULL,
    chung_tu_id INTEGER,
    chi_tiet_chung_tu_id INTEGER,
    chi_tiet_phieu_nhap_kho_id INTEGER,
    so_luong_thay_doi INTEGER NOT NULL DEFAULT 0,
    thay_doi_giu_cho INTEGER NOT NULL DEFAULT 0,
    thay_doi_cach_ly INTEGER NOT NULL DEFAULT 0,
    thay_doi_hong INTEGER NOT NULL DEFAULT 0,
    thay_doi_cho_xuat INTEGER NOT NULL DEFAULT 0,
    thay_doi_dang_chuyen INTEGER NOT NULL DEFAULT 0,
    ton_truoc INTEGER NOT NULL CHECK (ton_truoc >= 0),
    ton_sau INTEGER NOT NULL CHECK (ton_sau >= 0),
    gia_von_don_vi NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (gia_von_don_vi >= 0),
    gia_tri_thay_doi NUMERIC(18,2),
    thoi_diem_hach_toan TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_chung_tu DATE,
    noi_dung TEXT,
    ly_do TEXT,
    nguoi_thuc_hien_id INTEGER REFERENCES tai_khoan(id),
    request_id VARCHAR(100),
    giao_dich_dao_id BIGINT,
    CONSTRAINT fk_bdtk_ton FOREIGN KEY (don_vi_id, ton_kho_id)
        REFERENCES ton_kho(don_vi_id, id),
    CONSTRAINT fk_bdtk_nhap FOREIGN KEY (don_vi_id, chi_tiet_phieu_nhap_kho_id)
        REFERENCES chi_tiet_phieu_nhap_kho(don_vi_id, id),
    CONSTRAINT fk_bdtk_dao FOREIGN KEY (giao_dich_dao_id)
        REFERENCES bien_dong_ton_kho(id),
    CONSTRAINT uq_bdtk_ma UNIQUE (don_vi_id, ma_giao_dich),
    CONSTRAINT ck_bdtk_ton CHECK (ton_sau = ton_truoc + so_luong_thay_doi),
    CONSTRAINT ck_bdtk_co_thay_doi CHECK (
        so_luong_thay_doi <> 0 OR thay_doi_giu_cho <> 0
        OR thay_doi_cach_ly <> 0 OR thay_doi_hong <> 0
        OR thay_doi_cho_xuat <> 0 OR thay_doi_dang_chuyen <> 0
    )
);
CREATE INDEX idx_bdtk_ton ON bien_dong_ton_kho (don_vi_id, ton_kho_id, thoi_diem_hach_toan DESC);
CREATE INDEX idx_bdtk_phien_ban ON bien_dong_ton_kho (don_vi_id, phien_ban_sach_id, thoi_diem_hach_toan DESC);
CREATE INDEX idx_bdtk_chung_tu ON bien_dong_ton_kho (don_vi_id, nguon_chung_tu, chung_tu_id);
CREATE UNIQUE INDEX uq_bdtk_request
ON bien_dong_ton_kho (don_vi_id, request_id)
WHERE request_id IS NOT NULL;

CREATE TABLE giu_cho_ton_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    ma_giu_cho VARCHAR(100) NOT NULL,
    ton_kho_id INTEGER NOT NULL,
    so_luong INTEGER NOT NULL CHECK (so_luong > 0),
    nguon_giu_cho VARCHAR(40) NOT NULL
        CHECK (nguon_giu_cho IN ('DON_HANG','MUON_SACH','CHUYEN_KHO','SOAN_HANG','THU_CONG','KHAC')),
    chung_tu_id INTEGER,
    chi_tiet_chung_tu_id INTEGER,
    ngay_bat_dau TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_het_han TIMESTAMPTZ,
    ngay_giai_phong TIMESTAMPTZ,
    nguoi_giai_phong_id INTEGER REFERENCES tai_khoan(id),
    ly_do_giai_phong TEXT,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_GIU'
        CHECK (trang_thai IN ('DANG_GIU','DA_SU_DUNG','DA_GIAI_PHONG','HET_HAN','DA_HUY')),
    CONSTRAINT fk_gctk_ton FOREIGN KEY (don_vi_id, ton_kho_id)
        REFERENCES ton_kho(don_vi_id, id),
    CONSTRAINT uq_gctk_ma UNIQUE (don_vi_id, ma_giu_cho),
    CONSTRAINT ck_gctk_ngay CHECK (
        ngay_het_han IS NULL OR ngay_het_han > ngay_bat_dau
    )
);
CREATE INDEX idx_gctk_ton ON giu_cho_ton_kho (don_vi_id, ton_kho_id, trang_thai);
CREATE INDEX idx_gctk_het_han ON giu_cho_ton_kho (ngay_het_han)
WHERE trang_thai = 'DANG_GIU';

CREATE TABLE cau_hinh_ton_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    kho_id INTEGER NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL,
    so_luong_toi_thieu INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_toi_thieu >= 0),
    so_luong_toi_da INTEGER CHECK (so_luong_toi_da >= 0),
    diem_dat_hang_lai INTEGER NOT NULL DEFAULT 0 CHECK (diem_dat_hang_lai >= 0),
    so_luong_dat_hang_goi_y INTEGER CHECK (so_luong_dat_hang_goi_y > 0),
    ton_an_toan INTEGER NOT NULL DEFAULT 0 CHECK (ton_an_toan >= 0),
    so_ngay_du_tru INTEGER CHECK (so_ngay_du_tru >= 0),
    nha_cung_cap_uu_tien_id INTEGER,
    cho_tu_dong_canh_bao BOOLEAN NOT NULL DEFAULT TRUE,
    cho_tu_dong_de_xuat_nhap BOOLEAN NOT NULL DEFAULT FALSE,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_DUNG'
        CHECK (trang_thai IN ('DANG_DUNG','NGUNG_DUNG')),
    CONSTRAINT fk_chtk_kho FOREIGN KEY (don_vi_id, kho_id) REFERENCES kho(don_vi_id, id),
    CONSTRAINT fk_chtk_pb FOREIGN KEY (don_vi_id, phien_ban_sach_id)
        REFERENCES phien_ban_sach(don_vi_id, id),
    CONSTRAINT fk_chtk_ncc FOREIGN KEY (don_vi_id, nha_cung_cap_uu_tien_id)
        REFERENCES nha_cung_cap(don_vi_id, id),
    CONSTRAINT uq_chtk UNIQUE (don_vi_id, kho_id, phien_ban_sach_id),
    CONSTRAINT ck_chtk_nguong CHECK (
        so_luong_toi_da IS NULL OR so_luong_toi_da >= so_luong_toi_thieu
    )
);

DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN
        SELECT table_name FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name IN (
              'lo_ton_kho','ton_kho','bien_dong_ton_kho',
              'giu_cho_ton_kho','cau_hinh_ton_kho'
          )
          AND column_name = 'ngay_cap_nhat'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || r.table_name || '_ngay_cap_nhat', r.table_name
        );
    END LOOP;
END $$;