-- 026_chuyen-kho.sql
CREATE TABLE phieu_chuyen_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    ma_phieu VARCHAR(60) NOT NULL,
    loai_chuyen VARCHAR(30) NOT NULL DEFAULT 'GIUA_KHO'
        CHECK (loai_chuyen IN ('CUNG_KHO','GIUA_KHO','GIUA_CHI_NHANH')),
    chi_nhanh_nguon_id INTEGER NOT NULL,
    kho_nguon_id INTEGER NOT NULL,
    chi_nhanh_dich_id INTEGER NOT NULL,
    kho_dich_id INTEGER NOT NULL,
    ngay_yeu_cau TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_du_kien_xuat TIMESTAMPTZ,
    ngay_du_kien_nhan TIMESTAMPTZ,
    ngay_xuat_thuc_te TIMESTAMPTZ,
    ngay_nhan_thuc_te TIMESTAMPTZ,
    ngay_hoan_tat TIMESTAMPTZ,
    nguoi_yeu_cau_id INTEGER REFERENCES tai_khoan(id),
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ngay_duyet TIMESTAMPTZ,
    nguoi_xuat_id INTEGER REFERENCES tai_khoan(id),
    nguoi_van_chuyen VARCHAR(160),
    so_dien_thoai_van_chuyen VARCHAR(30),
    don_vi_van_chuyen VARCHAR(200),
    ma_van_don VARCHAR(120),
    bien_so_xe VARCHAR(30),
    nguoi_nhan_id INTEGER REFERENCES tai_khoan(id),
    nguoi_kiem_nhan_id INTEGER REFERENCES tai_khoan(id),
    tong_so_dong INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_dong >= 0),
    tong_so_luong_yeu_cau INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_yeu_cau >= 0),
    tong_so_luong_xuat INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_xuat >= 0),
    tong_so_luong_nhan INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_nhan >= 0),
    tong_so_luong_thieu INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_thieu >= 0),
    tong_so_luong_hong INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_hong >= 0),
    chi_phi_van_chuyen NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (chi_phi_van_chuyen >= 0),
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    ly_do_chuyen TEXT NOT NULL,
    ghi_chu TEXT,
    ghi_chu_noi_bo TEXT,
    ly_do_tu_choi TEXT,
    ly_do_huy TEXT,
    nguoi_huy_id INTEGER REFERENCES tai_khoan(id),
    ngay_huy TIMESTAMPTZ,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'NHAP'
        CHECK (trang_thai IN (
            'NHAP','CHO_DUYET','DA_DUYET','DANG_SOAN',
            'DA_XUAT','DANG_VAN_CHUYEN','DANG_NHAN',
            'NHAN_MOT_PHAN','CHO_XU_LY_CHENH_LECH','HOAN_TAT','TU_CHOI','DA_HUY'
        )),
    CONSTRAINT fk_pck_nguon FOREIGN KEY (don_vi_id, chi_nhanh_nguon_id, kho_nguon_id)
        REFERENCES kho(don_vi_id, chi_nhanh_id, id),
    CONSTRAINT fk_pck_dich FOREIGN KEY (don_vi_id, chi_nhanh_dich_id, kho_dich_id)
        REFERENCES kho(don_vi_id, chi_nhanh_id, id),
    CONSTRAINT uq_pck_ma UNIQUE (don_vi_id, ma_phieu),
    CONSTRAINT uq_pck_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_pck_kho CHECK (
        kho_nguon_id <> kho_dich_id OR loai_chuyen = 'CUNG_KHO'
    ),
    CONSTRAINT ck_pck_loai CHECK (
        (loai_chuyen = 'CUNG_KHO' AND kho_nguon_id = kho_dich_id)
        OR (loai_chuyen = 'GIUA_KHO' AND kho_nguon_id <> kho_dich_id
            AND chi_nhanh_nguon_id = chi_nhanh_dich_id)
        OR (loai_chuyen = 'GIUA_CHI_NHANH'
            AND chi_nhanh_nguon_id <> chi_nhanh_dich_id)
    )
);
CREATE INDEX idx_pck_nguon ON phieu_chuyen_kho (don_vi_id, kho_nguon_id, trang_thai, ngay_tao DESC);
CREATE INDEX idx_pck_dich ON phieu_chuyen_kho (don_vi_id, kho_dich_id, trang_thai, ngay_tao DESC);

CREATE TABLE chi_tiet_phieu_chuyen_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    phieu_chuyen_kho_id INTEGER NOT NULL,
    so_dong INTEGER NOT NULL CHECK (so_dong > 0),
    phien_ban_sach_id INTEGER NOT NULL,
    lo_ton_kho_id INTEGER NOT NULL,
    vi_tri_nguon_id INTEGER NOT NULL,
    vi_tri_dich_id INTEGER,
    so_luong_yeu_cau INTEGER NOT NULL CHECK (so_luong_yeu_cau > 0),
    so_luong_duyet INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_duyet >= 0),
    so_luong_da_giu INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_da_giu >= 0),
    so_luong_da_xuat INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_da_xuat >= 0),
    so_luong_da_nhan INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_da_nhan >= 0),
    so_luong_hong INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_hong >= 0),
    so_luong_thieu INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_thieu >= 0),
    gia_von_don_vi NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (gia_von_don_vi >= 0),
    ghi_chu TEXT,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET'
        CHECK (trang_thai IN ('CHO_DUYET','DA_DUYET','DA_XUAT','NHAN_MOT_PHAN','HOAN_TAT','TU_CHOI','DA_HUY')),
    CONSTRAINT fk_ctpck_phieu FOREIGN KEY (don_vi_id, phieu_chuyen_kho_id)
        REFERENCES phieu_chuyen_kho(don_vi_id, id),
    CONSTRAINT fk_ctpck_lo FOREIGN KEY (don_vi_id, phien_ban_sach_id, lo_ton_kho_id)
        REFERENCES lo_ton_kho(don_vi_id, phien_ban_sach_id, id),
    CONSTRAINT fk_ctpck_vt_nguon FOREIGN KEY (don_vi_id, vi_tri_nguon_id)
        REFERENCES vi_tri_kho(don_vi_id, id),
    CONSTRAINT fk_ctpck_vt_dich FOREIGN KEY (don_vi_id, vi_tri_dich_id)
        REFERENCES vi_tri_kho(don_vi_id, id),
    CONSTRAINT uq_ctpck_dong UNIQUE (don_vi_id, phieu_chuyen_kho_id, so_dong),
    CONSTRAINT uq_ctpck_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_ctpck_so_luong CHECK (
        so_luong_duyet <= so_luong_yeu_cau
        AND so_luong_da_xuat <= so_luong_duyet
        AND so_luong_da_nhan + so_luong_hong + so_luong_thieu <= so_luong_da_xuat
    )
);
CREATE INDEX idx_ctpck_pb ON chi_tiet_phieu_chuyen_kho (don_vi_id, phien_ban_sach_id);

CREATE TABLE lan_giao_nhan_chuyen_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    phieu_chuyen_kho_id INTEGER NOT NULL,
    ma_lan_giao_nhan VARCHAR(80) NOT NULL,
    lan_thu INTEGER NOT NULL CHECK (lan_thu > 0),
    ngay_xuat TIMESTAMPTZ,
    ngay_nhan TIMESTAMPTZ,
    nguoi_giao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_nhan_id INTEGER REFERENCES tai_khoan(id),
    nguoi_van_chuyen VARCHAR(160),
    ma_van_don VARCHAR(120),
    so_kien INTEGER CHECK (so_kien >= 0),
    so_luong_xuat INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_xuat >= 0),
    so_luong_nhan INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_nhan >= 0),
    so_luong_thieu INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_thieu >= 0),
    so_luong_hong INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_hong >= 0),
    ghi_chu TEXT,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_XUAT'
        CHECK (trang_thai IN ('CHO_XUAT','DA_XUAT','DANG_VAN_CHUYEN','DA_NHAN','CO_CHENH_LECH','DA_HUY')),
    CONSTRAINT fk_lgnck_phieu FOREIGN KEY (don_vi_id, phieu_chuyen_kho_id)
        REFERENCES phieu_chuyen_kho(don_vi_id, id),
    CONSTRAINT uq_lgnck_ma UNIQUE (don_vi_id, ma_lan_giao_nhan),
    CONSTRAINT uq_lgnck_lan UNIQUE (don_vi_id, phieu_chuyen_kho_id, lan_thu),
    CONSTRAINT uq_lgnck_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_lgnck_so_luong CHECK (
        so_luong_nhan + so_luong_thieu + so_luong_hong <= so_luong_xuat
    )
);

CREATE TABLE chi_tiet_giao_nhan_chuyen_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    lan_giao_nhan_chuyen_kho_id INTEGER NOT NULL,
    chi_tiet_phieu_chuyen_kho_id INTEGER NOT NULL,
    so_luong_xuat INTEGER NOT NULL CHECK (so_luong_xuat > 0),
    so_luong_nhan_dat INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_nhan_dat >= 0),
    so_luong_nhan_hong INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_nhan_hong >= 0),
    so_luong_thieu INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_thieu >= 0),
    vi_tri_nhan_id INTEGER,
    ngay_kiem_nhan TIMESTAMPTZ,
    nguoi_kiem_nhan_id INTEGER REFERENCES tai_khoan(id),
    mo_ta_chinh_lech TEXT,
    huong_xu_ly VARCHAR(30)
        CHECK (huong_xu_ly IN ('NHAP_KHO','CACH_LY','BOI_THUONG','TIM_HANG','CHO_XU_LY')),
    ghi_chu TEXT,
    CONSTRAINT fk_ctgnck_lan FOREIGN KEY (don_vi_id, lan_giao_nhan_chuyen_kho_id)
        REFERENCES lan_giao_nhan_chuyen_kho(don_vi_id, id),
    CONSTRAINT fk_ctgnck_dong FOREIGN KEY (don_vi_id, chi_tiet_phieu_chuyen_kho_id)
        REFERENCES chi_tiet_phieu_chuyen_kho(don_vi_id, id),
    CONSTRAINT fk_ctgnck_vi_tri FOREIGN KEY (don_vi_id, vi_tri_nhan_id)
        REFERENCES vi_tri_kho(don_vi_id, id),
    CONSTRAINT uq_ctgnck UNIQUE (
        don_vi_id, lan_giao_nhan_chuyen_kho_id, chi_tiet_phieu_chuyen_kho_id
    ),
    CONSTRAINT uq_ctgnck_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_ctgnck_so_luong CHECK (
        so_luong_nhan_dat + so_luong_nhan_hong + so_luong_thieu <= so_luong_xuat
    )
);

CREATE TABLE tep_phieu_chuyen_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    phieu_chuyen_kho_id INTEGER NOT NULL,
    tep_dinh_kem_id INTEGER NOT NULL,
    loai_tai_lieu VARCHAR(40) NOT NULL
        CHECK (loai_tai_lieu IN ('PHIEU_XUAT','PHIEU_GIAO','PHIEU_NHAN','BIEN_BAN','ANH_HANG','KHAC')),
    ghi_chu TEXT,
    CONSTRAINT fk_tpck_phieu FOREIGN KEY (don_vi_id, phieu_chuyen_kho_id)
        REFERENCES phieu_chuyen_kho(don_vi_id, id),
    CONSTRAINT fk_tpck_tep FOREIGN KEY (don_vi_id, tep_dinh_kem_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT uq_tpck UNIQUE (don_vi_id, phieu_chuyen_kho_id, tep_dinh_kem_id)
);

ALTER TABLE bien_dong_ton_kho
ADD COLUMN chi_tiet_giao_nhan_chuyen_kho_id INTEGER,
ADD CONSTRAINT fk_bdtk_chuyen
FOREIGN KEY (don_vi_id, chi_tiet_giao_nhan_chuyen_kho_id)
REFERENCES chi_tiet_giao_nhan_chuyen_kho(don_vi_id, id);

DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN
        SELECT table_name FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name IN (
              'phieu_chuyen_kho','chi_tiet_phieu_chuyen_kho',
              'lan_giao_nhan_chuyen_kho','chi_tiet_giao_nhan_chuyen_kho',
              'tep_phieu_chuyen_kho'
          )
          AND column_name = 'ngay_cap_nhat'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || r.table_name || '_ngay_cap_nhat', r.table_name
        );
    END LOOP;
END $$;