-- 027_kiem-kho.sql
CREATE TABLE phieu_kiem_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    ma_phieu VARCHAR(60) NOT NULL,
    chi_nhanh_id INTEGER NOT NULL,
    kho_id INTEGER NOT NULL,
    loai_kiem_ke VARCHAR(30) NOT NULL DEFAULT 'DINH_KY'
        CHECK (loai_kiem_ke IN ('DINH_KY','DOT_XUAT','THEO_VI_TRI','THEO_SACH','BAN_GIAO','KHAC')),
    pham_vi_kiem_ke VARCHAR(30) NOT NULL DEFAULT 'TOAN_KHO'
        CHECK (pham_vi_kiem_ke IN ('TOAN_KHO','KHU_VUC','VI_TRI','DANH_SACH_SACH')),
    khu_vuc_kho_id INTEGER,
    vi_tri_kho_id INTEGER,
    ngay_du_kien_bat_dau TIMESTAMPTZ,
    ngay_du_kien_ket_thuc TIMESTAMPTZ,
    ngay_chot_ton TIMESTAMPTZ,
    ngay_bat_dau_thuc_te TIMESTAMPTZ,
    ngay_ket_thuc_thuc_te TIMESTAMPTZ,
    ngay_hoan_tat TIMESTAMPTZ,
    nguoi_phu_trach_id INTEGER REFERENCES tai_khoan(id),
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ngay_duyet TIMESTAMPTZ,
    nguoi_chot_ton_id INTEGER REFERENCES tai_khoan(id),
    nguoi_hoan_tat_id INTEGER REFERENCES tai_khoan(id),
    khoa_nhap_xuat_khi_kiem_ke BOOLEAN NOT NULL DEFAULT TRUE,
    cho_phep_kiem_lai BOOLEAN NOT NULL DEFAULT TRUE,
    so_lan_kiem_toi_da INTEGER NOT NULL DEFAULT 3 CHECK (so_lan_kiem_toi_da > 0),
    tong_so_dong INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_dong >= 0),
    tong_so_luong_he_thong INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_he_thong >= 0),
    tong_so_luong_thuc_dem INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_thuc_dem >= 0),
    tong_so_luong_thua INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_thua >= 0),
    tong_so_luong_thieu INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_luong_thieu >= 0),
    tong_gia_tri_thua NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tong_gia_tri_thua >= 0),
    tong_gia_tri_thieu NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tong_gia_tri_thieu >= 0),
    don_vi_tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    ly_do_kiem_ke TEXT,
    ket_luan TEXT,
    ghi_chu TEXT,
    ly_do_huy TEXT,
    nguoi_huy_id INTEGER REFERENCES tai_khoan(id),
    ngay_huy TIMESTAMPTZ,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'NHAP'
        CHECK (trang_thai IN (
            'NHAP','CHO_DUYET','DA_DUYET','DA_CHOT_TON','DANG_KIEM',
            'CHO_KIEM_LAI','CHO_DOI_CHIEU','CHO_DUYET_CHENH_LECH',
            'DA_DUYET_CHENH_LECH','DANG_DIEU_CHINH','HOAN_TAT','TU_CHOI','DA_HUY'
        )),
    CONSTRAINT fk_pkk_kho FOREIGN KEY (don_vi_id, chi_nhanh_id, kho_id)
        REFERENCES kho(don_vi_id, chi_nhanh_id, id),
    CONSTRAINT fk_pkk_khu_vuc FOREIGN KEY (don_vi_id, kho_id, khu_vuc_kho_id)
        REFERENCES khu_vuc_kho(don_vi_id, kho_id, id),
    CONSTRAINT fk_pkk_vi_tri FOREIGN KEY (don_vi_id, kho_id, vi_tri_kho_id)
        REFERENCES vi_tri_kho(don_vi_id, kho_id, id),
    CONSTRAINT uq_pkk_ma UNIQUE (don_vi_id, ma_phieu),
    CONSTRAINT uq_pkk_don_vi_id UNIQUE (don_vi_id, id),
    CONSTRAINT ck_pkk_pham_vi CHECK (
        (pham_vi_kiem_ke <> 'KHU_VUC' OR khu_vuc_kho_id IS NOT NULL)
        AND (pham_vi_kiem_ke <> 'VI_TRI' OR vi_tri_kho_id IS NOT NULL)
    )
);
CREATE INDEX idx_pkk_kho ON phieu_kiem_kho (don_vi_id, kho_id, trang_thai, ngay_tao DESC);

CREATE TABLE nhan_su_kiem_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    phieu_kiem_kho_id INTEGER NOT NULL,
    tai_khoan_id INTEGER NOT NULL REFERENCES tai_khoan(id),
    vai_tro VARCHAR(30) NOT NULL
        CHECK (vai_tro IN ('TRUONG_BAN','NGUOI_DEM','NGUOI_GHI','GIAM_SAT','NGUOI_DOI_CHIEU')),
    khu_vuc_kho_id INTEGER,
    ngay_phan_cong TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_hoan_thanh TIMESTAMPTZ,
    ghi_chu TEXT,
    trang_thai VARCHAR(24) NOT NULL DEFAULT 'DANG_PHAN_CONG'
        CHECK (trang_thai IN ('DANG_PHAN_CONG','HOAN_THANH','HUY_PHAN_CONG')),
    CONSTRAINT fk_nskk_phieu FOREIGN KEY (don_vi_id, phieu_kiem_kho_id)
        REFERENCES phieu_kiem_kho(don_vi_id, id),
    CONSTRAINT fk_nskk_khu_vuc FOREIGN KEY (don_vi_id, khu_vuc_kho_id)
        REFERENCES khu_vuc_kho(don_vi_id, id),
    CONSTRAINT uq_nskk UNIQUE (don_vi_id, phieu_kiem_kho_id, tai_khoan_id, vai_tro)
);

CREATE TABLE chi_tiet_kiem_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    phieu_kiem_kho_id INTEGER NOT NULL,
    so_dong INTEGER NOT NULL CHECK (so_dong > 0),
    ton_kho_id INTEGER,
    kho_id INTEGER NOT NULL,
    vi_tri_kho_id INTEGER NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL,
    lo_ton_kho_id INTEGER NOT NULL,
    so_luong_he_thong INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_he_thong >= 0),
    so_luong_giu_cho_luc_chot INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_giu_cho_luc_chot >= 0),
    so_luong_cach_ly_luc_chot INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_cach_ly_luc_chot >= 0),
    so_luong_hong_luc_chot INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_hong_luc_chot >= 0),
    phien_ban_du_lieu_luc_chot BIGINT,
    so_luong_dem_lan_cuoi INTEGER CHECK (so_luong_dem_lan_cuoi >= 0),
    so_luong_chot INTEGER CHECK (so_luong_chot >= 0),
    so_luong_chenh_lech INTEGER GENERATED ALWAYS AS (
        CASE WHEN so_luong_chot IS NULL THEN NULL
             ELSE so_luong_chot - so_luong_he_thong END
    ) STORED,
    gia_von_don_vi NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (gia_von_don_vi >= 0),
    gia_tri_chenh_lech NUMERIC(18,2),
    so_lan_kiem INTEGER NOT NULL DEFAULT 0 CHECK (so_lan_kiem >= 0),
    nguoi_chot_so_luong_id INTEGER REFERENCES tai_khoan(id),
    ngay_chot_so_luong TIMESTAMPTZ,
    nguyen_nhan_chenh_lech VARCHAR(40)
        CHECK (nguyen_nhan_chenh_lech IN (
            'NHAP_THIEU','NHAP_THUA','XUAT_THIEU','XUAT_THUA',
            'NHAM_VI_TRI','NHAM_PHien_BAN','HU_HONG','MAT_MAT','SAI_DU_LIEU','KHAC'
        )),
    mo_ta_nguyen_nhan TEXT,
    huong_xu_ly VARCHAR(30)
        CHECK (huong_xu_ly IN ('DIEU_CHINH_TANG','DIEU_CHINH_GIAM','CHUYEN_VI_TRI','KHONG_DIEU_CHINH','CHO_XAC_MINH')),
    ghi_chu TEXT,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_KIEM'
        CHECK (trang_thai IN ('CHO_KIEM','DA_KIEM','CHO_KIEM_LAI','DA_CHOT','CHO_DUYET','DA_DUYET','DA_DIEU_CHINH','BO_QUA')),
    CONSTRAINT fk_ctkk_phieu FOREIGN KEY (don_vi_id, phieu_kiem_kho_id)
        REFERENCES phieu_kiem_kho(don_vi_id, id),
    CONSTRAINT fk_ctkk_ton FOREIGN KEY (don_vi_id, ton_kho_id)
        REFERENCES ton_kho(don_vi_id, id),
    CONSTRAINT fk_ctkk_kho FOREIGN KEY (don_vi_id, kho_id)
        REFERENCES kho(don_vi_id, id),
    CONSTRAINT fk_ctkk_vi_tri FOREIGN KEY (don_vi_id, kho_id, vi_tri_kho_id)
        REFERENCES vi_tri_kho(don_vi_id, kho_id, id),
    CONSTRAINT fk_ctkk_lo FOREIGN KEY (don_vi_id, phien_ban_sach_id, lo_ton_kho_id)
        REFERENCES lo_ton_kho(don_vi_id, phien_ban_sach_id, id),
    CONSTRAINT uq_ctkk_dong UNIQUE (don_vi_id, phieu_kiem_kho_id, so_dong),
    CONSTRAINT uq_ctkk_toa_do UNIQUE (
        don_vi_id, phieu_kiem_kho_id, kho_id,
        vi_tri_kho_id, phien_ban_sach_id, lo_ton_kho_id
    ),
    CONSTRAINT uq_ctkk_don_vi_id UNIQUE (don_vi_id, id)
);
CREATE INDEX idx_ctkk_phien_ban ON chi_tiet_kiem_kho (don_vi_id, phien_ban_sach_id);

CREATE TABLE lan_dem_kiem_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    chi_tiet_kiem_kho_id INTEGER NOT NULL,
    lan_dem INTEGER NOT NULL CHECK (lan_dem > 0),
    so_luong_dem INTEGER NOT NULL CHECK (so_luong_dem >= 0),
    nguoi_dem_id INTEGER NOT NULL REFERENCES tai_khoan(id),
    nguoi_ghi_id INTEGER REFERENCES tai_khoan(id),
    thoi_diem_bat_dau TIMESTAMPTZ,
    thoi_diem_ket_thuc TIMESTAMPTZ NOT NULL DEFAULT now(),
    ma_vach_quet VARCHAR(160),
    phuong_phap_dem VARCHAR(30) NOT NULL DEFAULT 'THU_CONG'
        CHECK (phuong_phap_dem IN ('THU_CONG','QUET_MA_VACH','NHAP_FILE')),
    ket_qua VARCHAR(24) NOT NULL DEFAULT 'CHO_DOI_CHIEU'
        CHECK (ket_qua IN ('CHO_DOI_CHIEU','KHOP','CHENH_LECH','KHONG_HOP_LE')),
    ghi_chu TEXT,
    CONSTRAINT fk_ldkk_chi_tiet FOREIGN KEY (don_vi_id, chi_tiet_kiem_kho_id)
        REFERENCES chi_tiet_kiem_kho(don_vi_id, id),
    CONSTRAINT uq_ldkk_lan UNIQUE (don_vi_id, chi_tiet_kiem_kho_id, lan_dem)
);

CREATE TABLE dieu_chinh_kiem_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    ma_dieu_chinh VARCHAR(80) NOT NULL,
    phieu_kiem_kho_id INTEGER NOT NULL,
    chi_tiet_kiem_kho_id INTEGER NOT NULL,
    ton_kho_id INTEGER,
    so_luong_de_xuat INTEGER NOT NULL CHECK (so_luong_de_xuat <> 0),
    so_luong_duyet INTEGER,
    so_luong_da_hach_toan INTEGER NOT NULL DEFAULT 0,
    gia_von_don_vi NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (gia_von_don_vi >= 0),
    gia_tri_dieu_chinh NUMERIC(18,2),
    ly_do TEXT NOT NULL,
    nguoi_de_xuat_id INTEGER REFERENCES tai_khoan(id),
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ngay_duyet TIMESTAMPTZ,
    nguoi_hach_toan_id INTEGER REFERENCES tai_khoan(id),
    ngay_hach_toan TIMESTAMPTZ,
    ly_do_tu_choi TEXT,
    ghi_chu TEXT,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_DUYET'
        CHECK (trang_thai IN ('CHO_DUYET','DA_DUYET','TU_CHOI','DA_HACH_TOAN','DA_HUY')),
    CONSTRAINT fk_dckk_phieu FOREIGN KEY (don_vi_id, phieu_kiem_kho_id)
        REFERENCES phieu_kiem_kho(don_vi_id, id),
    CONSTRAINT fk_dckk_chi_tiet FOREIGN KEY (don_vi_id, chi_tiet_kiem_kho_id)
        REFERENCES chi_tiet_kiem_kho(don_vi_id, id),
    CONSTRAINT fk_dckk_ton FOREIGN KEY (don_vi_id, ton_kho_id)
        REFERENCES ton_kho(don_vi_id, id),
    CONSTRAINT uq_dckk_ma UNIQUE (don_vi_id, ma_dieu_chinh),
    CONSTRAINT uq_dckk_chi_tiet UNIQUE (don_vi_id, chi_tiet_kiem_kho_id),
    CONSTRAINT uq_dckk_don_vi_id UNIQUE (don_vi_id, id)
);

CREATE TABLE tep_phieu_kiem_kho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    phieu_kiem_kho_id INTEGER NOT NULL,
    tep_dinh_kem_id INTEGER NOT NULL,
    loai_tai_lieu VARCHAR(40) NOT NULL
        CHECK (loai_tai_lieu IN ('BIEN_BAN','BANG_KIEM','ANH_BANG_CHUNG','PHIEU_DIEU_CHINH','KHAC')),
    ghi_chu TEXT,
    CONSTRAINT fk_tpkk_phieu FOREIGN KEY (don_vi_id, phieu_kiem_kho_id)
        REFERENCES phieu_kiem_kho(don_vi_id, id),
    CONSTRAINT fk_tpkk_tep FOREIGN KEY (don_vi_id, tep_dinh_kem_id)
        REFERENCES tep_dinh_kem(don_vi_so_huu_id, id),
    CONSTRAINT uq_tpkk UNIQUE (don_vi_id, phieu_kiem_kho_id, tep_dinh_kem_id)
);

ALTER TABLE bien_dong_ton_kho
ADD COLUMN dieu_chinh_kiem_kho_id INTEGER,
ADD CONSTRAINT fk_bdtk_dieu_chinh_kiem_kho
FOREIGN KEY (don_vi_id, dieu_chinh_kiem_kho_id)
REFERENCES dieu_chinh_kiem_kho(don_vi_id, id);

DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN
        SELECT table_name FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name IN (
              'phieu_kiem_kho','nhan_su_kiem_kho','chi_tiet_kiem_kho',
              'lan_dem_kiem_kho','dieu_chinh_kiem_kho','tep_phieu_kiem_kho'
          )
          AND column_name = 'ngay_cap_nhat'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION public.cap_nhat_ngay_cap_nhat()',
            'trg_' || r.table_name || '_ngay_cap_nhat', r.table_name
        );
    END LOOP;
END $$;