CREATE TABLE IF NOT EXISTS gio_hang (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    khach_hang_id INTEGER,
    tai_khoan_id INTEGER REFERENCES tai_khoan(id),
    ma_phien_khach VARCHAR(100),
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAT_DONG' CHECK (trang_thai IN ('HOAT_DONG','DA_CHOT','DA_HUY','HET_HAN')),
    ngay_het_han TIMESTAMPTZ,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    CHECK (khach_hang_id IS NOT NULL OR tai_khoan_id IS NOT NULL OR ma_phien_khach IS NOT NULL)
);
CREATE TABLE IF NOT EXISTS chi_tiet_gio_hang (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    gio_hang_id BIGINT NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL REFERENCES phien_ban_sach(id),
    hinh_thuc VARCHAR(20) NOT NULL DEFAULT 'MUA' CHECK (hinh_thuc IN ('MUA','THUE','MUON','DAT_TRUOC')),
    so_luong INTEGER NOT NULL CHECK (so_luong > 0),
    ngay_bat_dau_du_kien DATE,
    ngay_ket_thuc_du_kien DATE,
    ghi_chu TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,gio_hang_id) REFERENCES gio_hang(don_vi_id,id) ON DELETE CASCADE,
    CHECK (ngay_ket_thuc_du_kien IS NULL OR ngay_bat_dau_du_kien IS NULL OR ngay_ket_thuc_du_kien >= ngay_bat_dau_du_kien)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_gio_hang_mat_hang ON chi_tiet_gio_hang(gio_hang_id,phien_ban_sach_id,hinh_thuc,ngay_bat_dau_du_kien,ngay_ket_thuc_du_kien) NULLS NOT DISTINCT;
CREATE TABLE IF NOT EXISTS ma_giam_gia (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ma VARCHAR(60) NOT NULL,
    ten VARCHAR(200) NOT NULL,
    loai VARCHAR(20) NOT NULL CHECK (loai IN ('PHAN_TRAM','SO_TIEN','MIEN_PHI_VAN_CHUYEN')),
    gia_tri NUMERIC(18,2) NOT NULL CHECK (gia_tri >= 0),
    giam_toi_da NUMERIC(18,2) CHECK (giam_toi_da >= 0),
    don_toi_thieu NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (don_toi_thieu >= 0),
    tong_luot INTEGER CHECK (tong_luot >= 0),
    luot_moi_khach INTEGER CHECK (luot_moi_khach > 0),
    hieu_luc_tu TIMESTAMPTZ NOT NULL,
    hieu_luc_den TIMESTAMPTZ NOT NULL,
    dieu_kien JSONB NOT NULL DEFAULT '{}'::jsonb,
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAT_DONG' CHECK (trang_thai IN ('HOAT_DONG','TAM_DUNG','NGUNG_HOAT_DONG')),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma),
    UNIQUE (don_vi_id,id),
    CHECK (hieu_luc_den > hieu_luc_tu),
    CHECK (loai <> 'PHAN_TRAM' OR gia_tri <= 100)
);
CREATE TABLE IF NOT EXISTS don_hang (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    khach_hang_id INTEGER,
    gio_hang_id BIGINT,
    ma_don_hang VARCHAR(50) NOT NULL,
    kenh_ban VARCHAR(20) NOT NULL CHECK (kenh_ban IN ('POS','WEBSITE','APP','DIEN_THOAI','NOI_BO','KHAC')),
    loai_don VARCHAR(20) NOT NULL DEFAULT 'BAN' CHECK (loai_don IN ('BAN','DAT_TRUOC','THUE','MUON','HON_HOP')),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'MOI' CHECK (trang_thai IN ('MOI','CHO_XAC_NHAN','DA_XAC_NHAN','DANG_CHUAN_BI','DANG_GIAO','GIAO_MOT_PHAN','HOAN_TAT','DA_HUY','HOAN_MOT_PHAN','DA_HOAN')),
    trang_thai_thanh_toan VARCHAR(25) NOT NULL DEFAULT 'CHUA_THANH_TOAN' CHECK (trang_thai_thanh_toan IN ('CHUA_THANH_TOAN','THANH_TOAN_MOT_PHAN','DA_THANH_TOAN','HOAN_MOT_PHAN','DA_HOAN')),
    tien_hang NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_hang >= 0),
    tien_giam_gia NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_giam_gia >= 0),
    tien_thue NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_thue >= 0),
    phi_van_chuyen NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (phi_van_chuyen >= 0),
    tien_coc_yeu_cau NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_coc_yeu_cau >= 0),
    tong_thanh_toan NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tong_thanh_toan >= 0),
    tien_da_thanh_toan NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_da_thanh_toan >= 0),
    tien_da_hoan NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_da_hoan >= 0),
    tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    ma_giam_gia_id INTEGER,
    ma_giam_gia_ap_dung VARCHAR(60),
    ten_nguoi_mua VARCHAR(200),
    email_nguoi_mua VARCHAR(255),
    so_dien_thoai_nguoi_mua VARCHAR(30),
    thong_tin_xuat_hoa_don JSONB NOT NULL DEFAULT '{}'::jsonb,
    ghi_chu_khach_hang TEXT,
    ghi_chu_noi_bo TEXT,
    ngay_dat TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_xac_nhan TIMESTAMPTZ,
    ngay_hoan_tat TIMESTAMPTZ,
    ngay_huy TIMESTAMPTZ,
    ly_do_huy TEXT,
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_xac_nhan_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_don_hang),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,gio_hang_id) REFERENCES gio_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,ma_giam_gia_id) REFERENCES ma_giam_gia(don_vi_id,id),
    CHECK (tien_giam_gia <= tien_hang + phi_van_chuyen)
);
CREATE INDEX IF NOT EXISTS idx_don_hang_khach ON don_hang(don_vi_id,khach_hang_id,ngay_dat DESC);
CREATE INDEX IF NOT EXISTS idx_don_hang_trang_thai ON don_hang(don_vi_id,chi_nhanh_id,trang_thai,ngay_dat DESC);
CREATE TABLE IF NOT EXISTS chi_tiet_don_hang (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    don_hang_id BIGINT NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL REFERENCES phien_ban_sach(id),
    ten_sach VARCHAR(500) NOT NULL,
    isbn VARCHAR(30),
    hinh_thuc VARCHAR(20) NOT NULL CHECK (hinh_thuc IN ('MUA','THUE','MUON','DAT_TRUOC')),
    so_luong INTEGER NOT NULL CHECK (so_luong > 0),
    don_gia NUMERIC(18,2) NOT NULL CHECK (don_gia >= 0),
    giam_gia NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (giam_gia >= 0),
    thue_suat NUMERIC(6,3) NOT NULL DEFAULT 0 CHECK (thue_suat BETWEEN 0 AND 100),
    tien_thue NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_thue >= 0),
    thanh_tien NUMERIC(18,2) NOT NULL CHECK (thanh_tien >= 0),
    so_luong_da_giao INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_da_giao >= 0),
    so_luong_da_hoan INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_da_hoan >= 0),
    ngay_bat_dau_du_kien DATE,
    ngay_ket_thuc_du_kien DATE,
    ghi_chu TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,don_hang_id) REFERENCES don_hang(don_vi_id,id),
    CHECK (so_luong_da_giao <= so_luong),
    CHECK (so_luong_da_hoan <= so_luong_da_giao)
);
CREATE INDEX IF NOT EXISTS idx_chi_tiet_don_hang ON chi_tiet_don_hang(don_vi_id,don_hang_id);
CREATE TABLE IF NOT EXISTS lich_su_trang_thai_don_hang (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    don_hang_id BIGINT NOT NULL,
    trang_thai_cu VARCHAR(30),
    trang_thai_moi VARCHAR(30) NOT NULL,
    ly_do TEXT,
    nguoi_thuc_hien_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,don_hang_id) REFERENCES don_hang(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS van_don (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    don_hang_id BIGINT NOT NULL,
    ma_van_don VARCHAR(100),
    don_vi_van_chuyen VARCHAR(150),
    ma_theo_doi VARCHAR(150),
    phuong_thuc VARCHAR(30) NOT NULL CHECK (phuong_thuc IN ('GIAO_NOI_BO','DOI_TAC','KHACH_TU_NHAN')),
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_GIAO' CHECK (trang_thai IN ('CHO_GIAO','DA_BAN_GIAO','DANG_VAN_CHUYEN','GIAO_MOT_PHAN','DA_GIAO','GIAO_THAT_BAI','HOAN_HANG','DA_HUY')),
    nguoi_nhan VARCHAR(200) NOT NULL,
    so_dien_thoai VARCHAR(30),
    dia_chi_nhan JSONB NOT NULL DEFAULT '{}'::jsonb,
    phi_van_chuyen NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (phi_van_chuyen >= 0),
    ngay_du_kien_giao TIMESTAMPTZ,
    ngay_ban_giao TIMESTAMPTZ,
    ngay_giao TIMESTAMPTZ,
    nguoi_giao_id INTEGER REFERENCES tai_khoan(id),
    bang_chung_giao JSONB NOT NULL DEFAULT '[]'::jsonb,
    ghi_chu TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,don_hang_id) REFERENCES don_hang(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS chi_tiet_van_don (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    van_don_id BIGINT NOT NULL,
    chi_tiet_don_hang_id BIGINT NOT NULL,
    so_luong INTEGER NOT NULL CHECK (so_luong > 0),
    so_luong_da_nhan INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_da_nhan >= 0),
    FOREIGN KEY (don_vi_id,van_don_id) REFERENCES van_don(don_vi_id,id),
    FOREIGN KEY (don_vi_id,chi_tiet_don_hang_id) REFERENCES chi_tiet_don_hang(don_vi_id,id),
    CHECK (so_luong_da_nhan <= so_luong)
);
CREATE TABLE IF NOT EXISTS lich_su_van_don (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    van_don_id BIGINT NOT NULL,
    trang_thai VARCHAR(30) NOT NULL,
    vi_tri VARCHAR(255),
    noi_dung TEXT,
    thoi_gian_su_kien TIMESTAMPTZ NOT NULL DEFAULT now(),
    nguoi_cap_nhat_id INTEGER REFERENCES tai_khoan(id),
    FOREIGN KEY (don_vi_id,van_don_id) REFERENCES van_don(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS ca_ban_hang (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chi_nhanh_id INTEGER NOT NULL REFERENCES chi_nhanh(id),
    ma_ca VARCHAR(50) NOT NULL,
    thu_ngan_id INTEGER NOT NULL REFERENCES tai_khoan(id),
    tien_dau_ca NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_dau_ca >= 0),
    tien_mat_thu NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_mat_thu >= 0),
    tien_mat_chi NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (tien_mat_chi >= 0),
    tien_mat_kiem_dem NUMERIC(18,2) CHECK (tien_mat_kiem_dem >= 0),
    chenh_lech NUMERIC(18,2),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'DANG_MO' CHECK (trang_thai IN ('DANG_MO','CHO_DUYET','DA_DONG')),
    ngay_mo TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_dong TIMESTAMPTZ,
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ghi_chu TEXT,
    UNIQUE (don_vi_id,ma_ca),
    UNIQUE (don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS phien_ban_hang (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    ca_ban_hang_id BIGINT,
    don_hang_id BIGINT,
    kenh_ban VARCHAR(20) NOT NULL CHECK (kenh_ban IN ('POS','WEBSITE','APP','DIEN_THOAI','NOI_BO','KHAC')),
    ma_phien VARCHAR(80) NOT NULL,
    thiet_bi VARCHAR(150),
    dia_chi_ip INET,
    nguoi_ban_id INTEGER REFERENCES tai_khoan(id),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'DANG_BAN' CHECK (trang_thai IN ('DANG_BAN','DA_CHOT','DA_HUY')),
    ngay_bat_dau TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_ket_thuc TIMESTAMPTZ,
    UNIQUE (don_vi_id,ma_phien),
    FOREIGN KEY (don_vi_id,ca_ban_hang_id) REFERENCES ca_ban_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,don_hang_id) REFERENCES don_hang(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS su_dung_ma_giam_gia (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    ma_giam_gia_id INTEGER NOT NULL,
    don_hang_id BIGINT NOT NULL,
    khach_hang_id INTEGER,
    so_tien_giam NUMERIC(18,2) NOT NULL CHECK (so_tien_giam >= 0),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'DA_AP_DUNG' CHECK (trang_thai IN ('DA_AP_DUNG','DA_HUY')),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_giam_gia_id,don_hang_id),
    FOREIGN KEY (don_vi_id,ma_giam_gia_id) REFERENCES ma_giam_gia(don_vi_id,id),
    FOREIGN KEY (don_vi_id,don_hang_id) REFERENCES don_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id)
);