CREATE TABLE IF NOT EXISTS phuong_thuc_thanh_toan (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ma VARCHAR(40) NOT NULL,
    ten VARCHAR(150) NOT NULL,
    loai VARCHAR(30) NOT NULL CHECK (loai IN ('TIEN_MAT','CHUYEN_KHOAN','QR','THE','VI_DIEN_TU','CONG_NO','DIEM','KHAC')),
    cau_hinh JSONB NOT NULL DEFAULT '{}'::jsonb,
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    thu_tu INTEGER NOT NULL DEFAULT 0,
    hoat_dong BOOLEAN NOT NULL DEFAULT TRUE,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma),
    UNIQUE (don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS tai_khoan_nhan_tien (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    ten_ngan_hang VARCHAR(150),
    ma_ngan_hang VARCHAR(30),
    so_tai_khoan VARCHAR(60),
    chu_tai_khoan VARCHAR(200),
    ma_vi VARCHAR(100),
    loai VARCHAR(20) NOT NULL CHECK (loai IN ('NGAN_HANG','VI_DIEN_TU','TIEN_MAT')),
    mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    hoat_dong BOOLEAN NOT NULL DEFAULT TRUE,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS giao_dich_thanh_toan (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    khach_hang_id INTEGER,
    phuong_thuc_id INTEGER NOT NULL,
    tai_khoan_nhan_id INTEGER,
    ma_giao_dich VARCHAR(100) NOT NULL,
    ma_giao_dich_doi_tac VARCHAR(200),
    ma_yeu_cau_doi_tac VARCHAR(200),
    loai_giao_dich VARCHAR(20) NOT NULL CHECK (loai_giao_dich IN ('THU','CHI','HOAN_TIEN')),
    so_tien NUMERIC(18,2) NOT NULL CHECK (so_tien > 0),
    tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'KHOI_TAO' CHECK (trang_thai IN ('KHOI_TAO','CHO_XU_LY','THANH_CONG','THAT_BAI','DA_HUY','HET_HAN')),
    khoa_chong_trung VARCHAR(150),
    du_lieu_yeu_cau JSONB NOT NULL DEFAULT '{}'::jsonb,
    du_lieu_phan_hoi JSONB NOT NULL DEFAULT '{}'::jsonb,
    noi_dung TEXT,
    thoi_gian_het_han TIMESTAMPTZ,
    thoi_gian_thanh_cong TIMESTAMPTZ,
    nguoi_thuc_hien_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_giao_dich),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,phuong_thuc_id) REFERENCES phuong_thuc_thanh_toan(don_vi_id,id),
    FOREIGN KEY (don_vi_id,tai_khoan_nhan_id) REFERENCES tai_khoan_nhan_tien(don_vi_id,id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_giao_dich_thanh_toan_chong_trung ON giao_dich_thanh_toan(don_vi_id,khoa_chong_trung) WHERE khoa_chong_trung IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_giao_dich_thanh_toan ON giao_dich_thanh_toan(don_vi_id,trang_thai,ngay_tao DESC);
CREATE TABLE IF NOT EXISTS su_kien_thanh_toan (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    giao_dich_id BIGINT,
    nha_cung_cap VARCHAR(100) NOT NULL,
    ma_su_kien VARCHAR(200) NOT NULL,
    loai_su_kien VARCHAR(100),
    chu_ky_hop_le BOOLEAN,
    payload JSONB NOT NULL,
    ket_qua_xu_ly VARCHAR(20) NOT NULL DEFAULT 'MOI' CHECK (ket_qua_xu_ly IN ('MOI','THANH_CONG','THAT_BAI','BO_QUA')),
    loi_xu_ly TEXT,
    so_lan_xu_ly INTEGER NOT NULL DEFAULT 0 CHECK (so_lan_xu_ly >= 0),
    ngay_nhan TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_xu_ly TIMESTAMPTZ,
    UNIQUE (don_vi_id,nha_cung_cap,ma_su_kien),
    FOREIGN KEY (don_vi_id,giao_dich_id) REFERENCES giao_dich_thanh_toan(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS phan_bo_thanh_toan (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    giao_dich_id BIGINT NOT NULL,
    loai_doi_tuong VARCHAR(30) NOT NULL CHECK (loai_doi_tuong IN ('DON_HANG','CONG_NO','TIEN_COC','PHI_PHAT','MUON_TRA','KHAC')),
    doi_tuong_id BIGINT NOT NULL,
    so_tien NUMERIC(18,2) NOT NULL CHECK (so_tien > 0),
    ghi_chu TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,giao_dich_id) REFERENCES giao_dich_thanh_toan(don_vi_id,id)
);
CREATE INDEX IF NOT EXISTS idx_phan_bo_thanh_toan_doi_tuong ON phan_bo_thanh_toan(don_vi_id,loai_doi_tuong,doi_tuong_id);
CREATE TABLE IF NOT EXISTS yeu_cau_hoan_tien (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    giao_dich_goc_id BIGINT NOT NULL,
    giao_dich_hoan_id BIGINT,
    don_hang_id BIGINT,
    ma_yeu_cau VARCHAR(80) NOT NULL,
    so_tien NUMERIC(18,2) NOT NULL CHECK (so_tien > 0),
    ly_do TEXT NOT NULL,
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'CHO_DUYET' CHECK (trang_thai IN ('CHO_DUYET','DA_DUYET','TU_CHOI','DANG_HOAN','DA_HOAN','THAT_BAI','DA_HUY')),
    nguoi_yeu_cau_id INTEGER REFERENCES tai_khoan(id),
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ngay_duyet TIMESTAMPTZ,
    ngay_hoan TIMESTAMPTZ,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_yeu_cau),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,giao_dich_goc_id) REFERENCES giao_dich_thanh_toan(don_vi_id,id),
    FOREIGN KEY (don_vi_id,giao_dich_hoan_id) REFERENCES giao_dich_thanh_toan(don_vi_id,id),
    FOREIGN KEY (don_vi_id,don_hang_id) REFERENCES don_hang(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS doi_soat_thanh_toan (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ma_dot VARCHAR(80) NOT NULL,
    nha_cung_cap VARCHAR(100),
    tai_khoan_nhan_id INTEGER,
    tu_ngay DATE NOT NULL,
    den_ngay DATE NOT NULL,
    tong_so_giao_dich INTEGER NOT NULL DEFAULT 0 CHECK (tong_so_giao_dich >= 0),
    tong_tien_he_thong NUMERIC(18,2) NOT NULL DEFAULT 0,
    tong_tien_doi_tac NUMERIC(18,2) NOT NULL DEFAULT 0,
    chenh_lech NUMERIC(18,2) NOT NULL DEFAULT 0,
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'NHAP' CHECK (trang_thai IN ('NHAP','DANG_DOI_SOAT','CO_CHENH_LECH','DA_KHOP','DA_CHOT')),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_chot_id INTEGER REFERENCES tai_khoan(id),
    ngay_chot TIMESTAMPTZ,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_dot),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,tai_khoan_nhan_id) REFERENCES tai_khoan_nhan_tien(don_vi_id,id),
    CHECK (den_ngay >= tu_ngay)
);
CREATE TABLE IF NOT EXISTS chi_tiet_doi_soat_thanh_toan (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    doi_soat_id BIGINT NOT NULL,
    giao_dich_id BIGINT,
    ma_giao_dich_doi_tac VARCHAR(200),
    so_tien_he_thong NUMERIC(18,2),
    so_tien_doi_tac NUMERIC(18,2),
    ket_qua VARCHAR(25) NOT NULL CHECK (ket_qua IN ('KHOP','THIEU_HE_THONG','THIEU_DOI_TAC','SAI_SO_TIEN','SAI_TRANG_THAI')),
    ghi_chu TEXT,
    FOREIGN KEY (don_vi_id,doi_soat_id) REFERENCES doi_soat_thanh_toan(don_vi_id,id),
    FOREIGN KEY (don_vi_id,giao_dich_id) REFERENCES giao_dich_thanh_toan(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS cong_no (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    khach_hang_id INTEGER,
    nha_cung_cap_id INTEGER,
    ma_cong_no VARCHAR(80) NOT NULL,
    loai_cong_no VARCHAR(20) NOT NULL CHECK (loai_cong_no IN ('PHAI_THU','PHAI_TRA')),
    loai_nguon VARCHAR(30) NOT NULL CHECK (loai_nguon IN ('DON_HANG','PHIEU_NHAP','MUON_TRA','PHI_PHAT','DIEU_CHINH','KHAC')),
    nguon_id BIGINT,
    so_tien_goc NUMERIC(18,2) NOT NULL CHECK (so_tien_goc > 0),
    so_tien_da_thanh_toan NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (so_tien_da_thanh_toan >= 0),
    so_tien_da_giam NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (so_tien_da_giam >= 0),
    ngay_phat_sinh DATE NOT NULL DEFAULT CURRENT_DATE,
    ngay_den_han DATE,
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'CHUA_THANH_TOAN' CHECK (trang_thai IN ('CHUA_THANH_TOAN','THANH_TOAN_MOT_PHAN','DA_THANH_TOAN','QUA_HAN','DA_XOA_NO','DA_HUY')),
    ghi_chu TEXT,
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_cong_no),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    CHECK (so_tien_da_thanh_toan + so_tien_da_giam <= so_tien_goc),
    CHECK ((loai_cong_no = 'PHAI_THU' AND khach_hang_id IS NOT NULL) OR (loai_cong_no = 'PHAI_TRA' AND nha_cung_cap_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS idx_cong_no_den_han ON cong_no(don_vi_id,loai_cong_no,trang_thai,ngay_den_han);
CREATE TABLE IF NOT EXISTS but_toan_cong_no (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    cong_no_id BIGINT NOT NULL,
    loai VARCHAR(30) NOT NULL CHECK (loai IN ('PHAT_SINH','THANH_TOAN','GIAM_NO','HOAN_THANH_TOAN','DIEU_CHINH_TANG','DIEU_CHINH_GIAM','XOA_NO')),
    so_tien_thay_doi NUMERIC(18,2) NOT NULL CHECK (so_tien_thay_doi <> 0),
    du_no_truoc NUMERIC(18,2) NOT NULL CHECK (du_no_truoc >= 0),
    du_no_sau NUMERIC(18,2) NOT NULL CHECK (du_no_sau >= 0),
    giao_dich_thanh_toan_id BIGINT,
    ma_chung_tu VARCHAR(100),
    ly_do TEXT,
    nguoi_thuc_hien_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (du_no_sau = du_no_truoc + so_tien_thay_doi),
    FOREIGN KEY (don_vi_id,cong_no_id) REFERENCES cong_no(don_vi_id,id),
    FOREIGN KEY (don_vi_id,giao_dich_thanh_toan_id) REFERENCES giao_dich_thanh_toan(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS tien_coc (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    khach_hang_id INTEGER NOT NULL,
    ma_coc VARCHAR(80) NOT NULL,
    loai_doi_tuong VARCHAR(30) NOT NULL CHECK (loai_doi_tuong IN ('DON_HANG','DAT_TRUOC','MUON_TRA','KHAC')),
    doi_tuong_id BIGINT NOT NULL,
    so_tien_yeu_cau NUMERIC(18,2) NOT NULL CHECK (so_tien_yeu_cau >= 0),
    so_tien_da_thu NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (so_tien_da_thu >= 0),
    so_tien_da_khau_tru NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (so_tien_da_khau_tru >= 0),
    so_tien_da_hoan NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (so_tien_da_hoan >= 0),
    tien_te CHAR(3) NOT NULL DEFAULT 'VND',
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'CHO_THU' CHECK (trang_thai IN ('CHO_THU','THU_MOT_PHAN','DA_THU','GIU_MOT_PHAN','DA_TAT_TOAN','DA_HUY')),
    ngay_den_han TIMESTAMPTZ,
    ghi_chu TEXT,
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_coc),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    CHECK (so_tien_da_khau_tru + so_tien_da_hoan <= so_tien_da_thu)
);
CREATE TABLE IF NOT EXISTS giao_dich_tien_coc (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    tien_coc_id BIGINT NOT NULL,
    giao_dich_thanh_toan_id BIGINT,
    loai VARCHAR(25) NOT NULL CHECK (loai IN ('THU_COC','GIU_COC','GIAI_TOA','KHAU_TRU','HOAN_COC','DIEU_CHINH')),
    so_tien NUMERIC(18,2) NOT NULL CHECK (so_tien > 0),
    so_du_truoc NUMERIC(18,2) NOT NULL CHECK (so_du_truoc >= 0),
    so_du_sau NUMERIC(18,2) NOT NULL CHECK (so_du_sau >= 0),
    ly_do TEXT,
    nguoi_thuc_hien_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,tien_coc_id) REFERENCES tien_coc(don_vi_id,id),
    FOREIGN KEY (don_vi_id,giao_dich_thanh_toan_id) REFERENCES giao_dich_thanh_toan(don_vi_id,id)
);