CREATE TABLE IF NOT EXISTS dat_truoc (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    khach_hang_id INTEGER NOT NULL,
    don_hang_id BIGINT,
    ma_dat_truoc VARCHAR(80) NOT NULL,
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'CHO_SACH' CHECK (trang_thai IN ('CHO_SACH','CO_SACH','DA_THONG_BAO','CHO_NHAN','DA_NHAN','HET_HAN','DA_HUY')),
    muc_uu_tien INTEGER NOT NULL DEFAULT 0,
    ngay_dat TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_du_kien_co_sach TIMESTAMPTZ,
    ngay_het_han_nhan TIMESTAMPTZ,
    ngay_hoan_tat TIMESTAMPTZ,
    ghi_chu TEXT,
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_dat_truoc),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,don_hang_id) REFERENCES don_hang(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS chi_tiet_dat_truoc (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    dat_truoc_id BIGINT NOT NULL,
    phien_ban_sach_id INTEGER NOT NULL REFERENCES phien_ban_sach(id),
    hinh_thuc VARCHAR(20) NOT NULL CHECK (hinh_thuc IN ('MUA','MUON','THUE')),
    so_luong INTEGER NOT NULL CHECK (so_luong > 0),
    so_luong_da_phan_bo INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_da_phan_bo >= 0),
    so_luong_da_nhan INTEGER NOT NULL DEFAULT 0 CHECK (so_luong_da_nhan >= 0),
    gia_du_kien NUMERIC(18,2) CHECK (gia_du_kien >= 0),
    ngay_du_kien DATE,
    ghi_chu TEXT,
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,dat_truoc_id) REFERENCES dat_truoc(don_vi_id,id),
    CHECK (so_luong_da_phan_bo <= so_luong),
    CHECK (so_luong_da_nhan <= so_luong_da_phan_bo)
);
CREATE TABLE IF NOT EXISTS phan_bo_sach_dat_truoc (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    chi_tiet_dat_truoc_id BIGINT NOT NULL,
    kho_id INTEGER NOT NULL,
    vi_tri_kho_id INTEGER,
    so_luong INTEGER NOT NULL CHECK (so_luong > 0),
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'DA_GIU' CHECK (trang_thai IN ('DA_GIU','DA_THONG_BAO','DA_NHAN','DA_GIAI_TOA')),
    ngay_giu TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_het_han TIMESTAMPTZ,
    ngay_giai_toa TIMESTAMPTZ,
    FOREIGN KEY (don_vi_id,chi_tiet_dat_truoc_id) REFERENCES chi_tiet_dat_truoc(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS cuon_sach (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    phien_ban_sach_id INTEGER NOT NULL REFERENCES phien_ban_sach(id),
    kho_id INTEGER,
    vi_tri_kho_id INTEGER,
    ma_cuon VARCHAR(80) NOT NULL,
    ma_vach VARCHAR(100),
    rfid VARCHAR(150),
    so_serial VARCHAR(100),
    ngay_nhap DATE,
    gia_tri_sach NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (gia_tri_sach >= 0),
    tinh_trang VARCHAR(25) NOT NULL DEFAULT 'TOT' CHECK (tinh_trang IN ('MOI','TOT','DA_SU_DUNG','HU_HONG_NHE','HU_HONG_NANG','MAT')),
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'SAN_SANG' CHECK (trang_thai IN ('SAN_SANG','DA_GIU','DANG_MUON','DANG_THUE','DANG_VAN_CHUYEN','BAO_TRI','MAT','THANH_LY')),
    mo_ta_tinh_trang TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_cuon),
    UNIQUE (don_vi_id,id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cuon_sach_ma_vach ON cuon_sach(don_vi_id,ma_vach) WHERE ma_vach IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_cuon_sach_rfid ON cuon_sach(don_vi_id,rfid) WHERE rfid IS NOT NULL;
CREATE TABLE IF NOT EXISTS muon_tra (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    khach_hang_id INTEGER NOT NULL,
    don_hang_id BIGINT,
    ma_phieu VARCHAR(80) NOT NULL,
    loai VARCHAR(20) NOT NULL CHECK (loai IN ('MUON','THUE')),
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'NHAP' CHECK (trang_thai IN ('NHAP','CHO_GIAO','DANG_GIAO','DANG_MUON','TRA_MOT_PHAN','DA_TRA','QUA_HAN','DA_HUY')),
    ngay_bat_dau TIMESTAMPTZ,
    ngay_hen_tra TIMESTAMPTZ,
    ngay_tra_het TIMESTAMPTZ,
    phi_thue NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (phi_thue >= 0),
    tien_coc_id BIGINT,
    ghi_chu TEXT,
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_giao_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_phieu),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,don_hang_id) REFERENCES don_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,tien_coc_id) REFERENCES tien_coc(don_vi_id,id),
    CHECK (ngay_hen_tra IS NULL OR ngay_bat_dau IS NULL OR ngay_hen_tra >= ngay_bat_dau)
);
CREATE TABLE IF NOT EXISTS chi_tiet_muon_tra (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    muon_tra_id BIGINT NOT NULL,
    cuon_sach_id BIGINT NOT NULL,
    tinh_trang_luc_giao VARCHAR(25),
    mo_ta_luc_giao TEXT,
    tinh_trang_luc_tra VARCHAR(25),
    mo_ta_luc_tra TEXT,
    ngay_giao TIMESTAMPTZ,
    ngay_hen_tra TIMESTAMPTZ,
    ngay_tra TIMESTAMPTZ,
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'CHO_GIAO' CHECK (trang_thai IN ('CHO_GIAO','DANG_GIAO','DANG_MUON','DA_TRA','QUA_HAN','MAT','HU_HONG','DA_HUY')),
    so_lan_gia_han INTEGER NOT NULL DEFAULT 0 CHECK (so_lan_gia_han >= 0),
    phi_thue NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (phi_thue >= 0),
    ghi_chu TEXT,
    UNIQUE (don_vi_id,id),
    UNIQUE (muon_tra_id,cuon_sach_id),
    FOREIGN KEY (don_vi_id,muon_tra_id) REFERENCES muon_tra(don_vi_id,id),
    FOREIGN KEY (don_vi_id,cuon_sach_id) REFERENCES cuon_sach(don_vi_id,id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cuon_dang_muon ON chi_tiet_muon_tra(don_vi_id,cuon_sach_id) WHERE trang_thai IN ('CHO_GIAO','DANG_GIAO','DANG_MUON','QUA_HAN');
CREATE TABLE IF NOT EXISTS ban_giao_sach (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    muon_tra_id BIGINT NOT NULL,
    van_don_id BIGINT,
    loai VARCHAR(20) NOT NULL CHECK (loai IN ('GIAO','NHAN_TRA')),
    nguoi_giao_id INTEGER REFERENCES tai_khoan(id),
    ten_nguoi_nhan VARCHAR(200),
    thoi_gian TIMESTAMPTZ NOT NULL DEFAULT now(),
    chu_ky_nguoi_nhan TEXT,
    anh_bang_chung JSONB NOT NULL DEFAULT '[]'::jsonb,
    ghi_chu TEXT,
    FOREIGN KEY (don_vi_id,muon_tra_id) REFERENCES muon_tra(don_vi_id,id),
    FOREIGN KEY (don_vi_id,van_don_id) REFERENCES van_don(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS chi_tiet_ban_giao_sach (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    ban_giao_id BIGINT NOT NULL,
    chi_tiet_muon_tra_id BIGINT NOT NULL,
    tinh_trang VARCHAR(25) NOT NULL,
    mo_ta TEXT,
    anh_bang_chung JSONB NOT NULL DEFAULT '[]'::jsonb,
    FOREIGN KEY (don_vi_id,chi_tiet_muon_tra_id) REFERENCES chi_tiet_muon_tra(don_vi_id,id),
    FOREIGN KEY (ban_giao_id) REFERENCES ban_giao_sach(id)
);
CREATE TABLE IF NOT EXISTS yeu_cau_gia_han (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    muon_tra_id BIGINT NOT NULL,
    ma_yeu_cau VARCHAR(80) NOT NULL,
    ngay_hen_tra_cu TIMESTAMPTZ NOT NULL,
    ngay_hen_tra_moi TIMESTAMPTZ NOT NULL,
    ly_do TEXT,
    phi_gia_han NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (phi_gia_han >= 0),
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'CHO_DUYET' CHECK (trang_thai IN ('CHO_DUYET','DA_DUYET','TU_CHOI','DA_HUY')),
    nguoi_yeu_cau_id INTEGER REFERENCES tai_khoan(id),
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ly_do_tu_choi TEXT,
    ngay_duyet TIMESTAMPTZ,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_yeu_cau),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,muon_tra_id) REFERENCES muon_tra(don_vi_id,id),
    CHECK (ngay_hen_tra_moi > ngay_hen_tra_cu)
);
CREATE TABLE IF NOT EXISTS chi_tiet_gia_han (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    yeu_cau_gia_han_id BIGINT NOT NULL,
    chi_tiet_muon_tra_id BIGINT NOT NULL,
    ngay_hen_tra_cu TIMESTAMPTZ NOT NULL,
    ngay_hen_tra_moi TIMESTAMPTZ NOT NULL,
    phi_gia_han NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (phi_gia_han >= 0),
    UNIQUE (yeu_cau_gia_han_id,chi_tiet_muon_tra_id),
    FOREIGN KEY (don_vi_id,yeu_cau_gia_han_id) REFERENCES yeu_cau_gia_han(don_vi_id,id),
    FOREIGN KEY (don_vi_id,chi_tiet_muon_tra_id) REFERENCES chi_tiet_muon_tra(don_vi_id,id),
    CHECK (ngay_hen_tra_moi > ngay_hen_tra_cu)
);
CREATE TABLE IF NOT EXISTS chinh_sach_phi_phat (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chi_nhanh_id INTEGER REFERENCES chi_nhanh(id),
    ma VARCHAR(60) NOT NULL,
    ten VARCHAR(200) NOT NULL,
    loai VARCHAR(25) NOT NULL CHECK (loai IN ('QUA_HAN','MAT_SACH','HU_HONG','KHAC')),
    cach_tinh VARCHAR(25) NOT NULL CHECK (cach_tinh IN ('CO_DINH','THEO_NGAY','PHAN_TRAM_GIA_TRI','THEO_THUC_TE')),
    gia_tri NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (gia_tri >= 0),
    muc_toi_da NUMERIC(18,2) CHECK (muc_toi_da >= 0),
    so_ngay_mien_phi INTEGER NOT NULL DEFAULT 0 CHECK (so_ngay_mien_phi >= 0),
    dieu_kien JSONB NOT NULL DEFAULT '{}'::jsonb,
    hieu_luc_tu TIMESTAMPTZ NOT NULL,
    hieu_luc_den TIMESTAMPTZ,
    hoat_dong BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (don_vi_id,ma),
    UNIQUE (don_vi_id,id),
    CHECK (hieu_luc_den IS NULL OR hieu_luc_den > hieu_luc_tu)
);
CREATE TABLE IF NOT EXISTS phi_phat (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    khach_hang_id INTEGER NOT NULL,
    chi_tiet_muon_tra_id BIGINT,
    chinh_sach_id INTEGER,
    ma_phieu VARCHAR(80) NOT NULL,
    loai VARCHAR(25) NOT NULL CHECK (loai IN ('QUA_HAN','MAT_SACH','HU_HONG','KHAC')),
    so_ngay_qua_han INTEGER NOT NULL DEFAULT 0 CHECK (so_ngay_qua_han >= 0),
    gia_tri_sach NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (gia_tri_sach >= 0),
    so_tien_goc NUMERIC(18,2) NOT NULL CHECK (so_tien_goc >= 0),
    so_tien_mien_giam NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (so_tien_mien_giam >= 0),
    so_tien_phai_thu NUMERIC(18,2) NOT NULL CHECK (so_tien_phai_thu >= 0),
    so_tien_da_thu NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (so_tien_da_thu >= 0),
    cong_no_id BIGINT,
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'CHO_XAC_NHAN' CHECK (trang_thai IN ('CHO_XAC_NHAN','CHO_THU','THU_MOT_PHAN','DA_THU','DA_MIEN','DA_HUY')),
    ly_do TEXT,
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    nguoi_duyet_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_duyet TIMESTAMPTZ,
    UNIQUE (don_vi_id,ma_phieu),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,chi_tiet_muon_tra_id) REFERENCES chi_tiet_muon_tra(don_vi_id,id),
    FOREIGN KEY (don_vi_id,chinh_sach_id) REFERENCES chinh_sach_phi_phat(don_vi_id,id),
    FOREIGN KEY (don_vi_id,cong_no_id) REFERENCES cong_no(don_vi_id,id),
    CHECK (so_tien_phai_thu = so_tien_goc - so_tien_mien_giam),
    CHECK (so_tien_da_thu <= so_tien_phai_thu)
);
CREATE TABLE IF NOT EXISTS lich_su_phi_phat (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    phi_phat_id BIGINT NOT NULL,
    hanh_dong VARCHAR(30) NOT NULL CHECK (hanh_dong IN ('TAO','DUYET','MIEN_GIAM','THU_TIEN','HOAN_TIEN','HUY','DIEU_CHINH')),
    so_tien_truoc NUMERIC(18,2),
    so_tien_sau NUMERIC(18,2),
    ly_do TEXT,
    nguoi_thuc_hien_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,phi_phat_id) REFERENCES phi_phat(don_vi_id,id)
);