CREATE TABLE IF NOT EXISTS mau_thong_bao (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ma VARCHAR(100) NOT NULL,
    ten VARCHAR(200) NOT NULL,
    kenh VARCHAR(20) NOT NULL CHECK (kenh IN ('HE_THONG','EMAIL','SMS','PUSH')),
    tieu_de TEXT NOT NULL,
    noi_dung TEXT NOT NULL,
    bien_cho_phep JSONB NOT NULL DEFAULT '[]'::jsonb,
    hoat_dong BOOLEAN NOT NULL DEFAULT TRUE,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma,kenh),
    UNIQUE (don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS thong_bao (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    mau_thong_bao_id INTEGER,
    loai VARCHAR(60) NOT NULL,
    tieu_de VARCHAR(500) NOT NULL,
    noi_dung TEXT NOT NULL,
    du_lieu JSONB NOT NULL DEFAULT '{}'::jsonb,
    duong_dan TEXT,
    loai_doi_tuong VARCHAR(60),
    doi_tuong_id BIGINT,
    muc_do VARCHAR(20) NOT NULL DEFAULT 'THONG_TIN' CHECK (muc_do IN ('THONG_TIN','THANH_CONG','CANH_BAO','KHAN_CAP')),
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_het_han TIMESTAMPTZ,
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,mau_thong_bao_id) REFERENCES mau_thong_bao(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS nguoi_nhan_thong_bao (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    thong_bao_id BIGINT NOT NULL,
    tai_khoan_id INTEGER REFERENCES tai_khoan(id),
    khach_hang_id INTEGER,
    kenh VARCHAR(20) NOT NULL CHECK (kenh IN ('HE_THONG','EMAIL','SMS','PUSH')),
    dia_chi_nhan VARCHAR(255),
    trang_thai VARCHAR(25) NOT NULL DEFAULT 'CHO_GUI' CHECK (trang_thai IN ('CHO_GUI','DANG_GUI','DA_GUI','DA_NHAN','DA_DOC','THAT_BAI','DA_HUY')),
    da_doc BOOLEAN NOT NULL DEFAULT FALSE,
    ngay_doc TIMESTAMPTZ,
    ngay_gui TIMESTAMPTZ,
    ngay_nhan TIMESTAMPTZ,
    so_lan_thu INTEGER NOT NULL DEFAULT 0 CHECK (so_lan_thu >= 0),
    lan_thu_tiep_theo TIMESTAMPTZ,
    loi_cuoi TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,thong_bao_id) REFERENCES thong_bao(don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    CHECK (tai_khoan_id IS NOT NULL OR khach_hang_id IS NOT NULL OR dia_chi_nhan IS NOT NULL),
    CHECK (da_doc = FALSE OR ngay_doc IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_thong_bao_chua_doc ON nguoi_nhan_thong_bao(don_vi_id,tai_khoan_id,ngay_tao DESC) WHERE da_doc = FALSE;
CREATE TABLE IF NOT EXISTS lich_su_gui_thong_bao (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    nguoi_nhan_id BIGINT NOT NULL,
    nha_cung_cap VARCHAR(100),
    ma_thong_diep_doi_tac VARCHAR(200),
    lan_thu INTEGER NOT NULL CHECK (lan_thu > 0),
    trang_thai VARCHAR(20) NOT NULL CHECK (trang_thai IN ('THANH_CONG','THAT_BAI')),
    ma_loi VARCHAR(100),
    noi_dung_loi TEXT,
    phan_hoi JSONB NOT NULL DEFAULT '{}'::jsonb,
    ngay_gui TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (nguoi_nhan_id) REFERENCES nguoi_nhan_thong_bao(id)
);
CREATE TABLE IF NOT EXISTS danh_muc_bao_cao (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ma_bao_cao VARCHAR(80) NOT NULL,
    ten_bao_cao VARCHAR(255) NOT NULL,
    nhom VARCHAR(80) NOT NULL CHECK (nhom IN ('BAN_HANG','TON_KHO','NHAP_XUAT','KHACH_HANG','HOI_VIEN','MUON_TRA','CONG_NO','THANH_TOAN','DOANH_THU','KHAC')),
    mo_ta TEXT,
    cau_hinh_bo_loc JSONB NOT NULL DEFAULT '{}'::jsonb,
    cau_hinh_cot JSONB NOT NULL DEFAULT '[]'::jsonb,
    quyen_xem VARCHAR(100),
    hoat_dong BOOLEAN NOT NULL DEFAULT TRUE,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma_bao_cao),
    UNIQUE (don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS mau_bao_cao_ca_nhan (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    danh_muc_bao_cao_id INTEGER NOT NULL,
    tai_khoan_id INTEGER NOT NULL REFERENCES tai_khoan(id),
    ten_mau VARCHAR(200) NOT NULL,
    bo_loc JSONB NOT NULL DEFAULT '{}'::jsonb,
    cot_hien_thi JSONB NOT NULL DEFAULT '[]'::jsonb,
    sap_xep JSONB NOT NULL DEFAULT '[]'::jsonb,
    mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,danh_muc_bao_cao_id) REFERENCES danh_muc_bao_cao(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS lich_bao_cao (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    danh_muc_bao_cao_id INTEGER NOT NULL,
    ten_lich VARCHAR(200) NOT NULL,
    bieu_thuc_cron VARCHAR(100) NOT NULL,
    mui_gio VARCHAR(100) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    bo_loc JSONB NOT NULL DEFAULT '{}'::jsonb,
    dinh_dang VARCHAR(10) NOT NULL CHECK (dinh_dang IN ('XLSX','CSV','PDF','JSON')),
    nguoi_nhan JSONB NOT NULL DEFAULT '[]'::jsonb,
    lan_chay_tiep_theo TIMESTAMPTZ,
    lan_chay_cuoi TIMESTAMPTZ,
    hoat_dong BOOLEAN NOT NULL DEFAULT TRUE,
    nguoi_tao_id INTEGER REFERENCES tai_khoan(id),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,danh_muc_bao_cao_id) REFERENCES danh_muc_bao_cao(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS lan_chay_bao_cao (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    danh_muc_bao_cao_id INTEGER NOT NULL,
    lich_bao_cao_id BIGINT,
    nguoi_yeu_cau_id INTEGER REFERENCES tai_khoan(id),
    bo_loc JSONB NOT NULL DEFAULT '{}'::jsonb,
    dinh_dang VARCHAR(10) NOT NULL CHECK (dinh_dang IN ('XLSX','CSV','PDF','JSON')),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'CHO_CHAY' CHECK (trang_thai IN ('CHO_CHAY','DANG_CHAY','HOAN_TAT','THAT_BAI','DA_HUY')),
    duong_dan_file TEXT,
    ten_file VARCHAR(255),
    dung_luong_byte BIGINT CHECK (dung_luong_byte >= 0),
    so_dong BIGINT CHECK (so_dong >= 0),
    loi_xu_ly TEXT,
    ngay_bat_dau TIMESTAMPTZ,
    ngay_hoan_tat TIMESTAMPTZ,
    ngay_het_han_file TIMESTAMPTZ,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,danh_muc_bao_cao_id) REFERENCES danh_muc_bao_cao(don_vi_id,id),
    FOREIGN KEY (lich_bao_cao_id) REFERENCES lich_bao_cao(id)
);
CREATE INDEX IF NOT EXISTS idx_lan_chay_bao_cao ON lan_chay_bao_cao(don_vi_id,trang_thai,ngay_tao DESC);
CREATE TABLE IF NOT EXISTS cau_hinh_ai (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    ma VARCHAR(80) NOT NULL,
    ten VARCHAR(200) NOT NULL,
    nha_cung_cap VARCHAR(100) NOT NULL,
    ten_mo_hinh VARCHAR(150) NOT NULL,
    tham_chieu_bi_mat VARCHAR(255),
    dia_chi_dich_vu TEXT,
    nhiet_do NUMERIC(4,3) CHECK (nhiet_do BETWEEN 0 AND 2),
    so_token_toi_da INTEGER CHECK (so_token_toi_da > 0),
    gioi_han_token_ngay BIGINT CHECK (gioi_han_token_ngay >= 0),
    cau_hinh JSONB NOT NULL DEFAULT '{}'::jsonb,
    hoat_dong BOOLEAN NOT NULL DEFAULT TRUE,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,ma),
    UNIQUE (don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS nguon_du_lieu_ai (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    loai_nguon VARCHAR(30) NOT NULL CHECK (loai_nguon IN ('DAU_SACH','PHIEN_BAN_SACH','TEP_TIN','FAQ','CHINH_SACH','BAO_CAO','KHAC')),
    doi_tuong_id BIGINT,
    tieu_de VARCHAR(500) NOT NULL,
    noi_dung TEXT,
    duong_dan TEXT,
    phien_ban VARCHAR(80),
    muc_do_truy_cap VARCHAR(20) NOT NULL DEFAULT 'NOI_BO' CHECK (muc_do_truy_cap IN ('CONG_KHAI','NOI_BO','HAN_CHE')),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'CHO_DONG_BO' CHECK (trang_thai IN ('CHO_DONG_BO','DANG_DONG_BO','SAN_SANG','THAT_BAI','DA_XOA')),
    lan_dong_bo_cuoi TIMESTAMPTZ,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS doan_du_lieu_ai (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    nguon_du_lieu_id BIGINT NOT NULL,
    thu_tu INTEGER NOT NULL CHECK (thu_tu >= 0),
    noi_dung TEXT NOT NULL,
    so_token INTEGER CHECK (so_token >= 0),
    ma_bam VARCHAR(128),
    ma_vector VARCHAR(255),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (nguon_du_lieu_id,thu_tu),
    FOREIGN KEY (don_vi_id,nguon_du_lieu_id) REFERENCES nguon_du_lieu_ai(don_vi_id,id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS hoi_thoai_ai (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    tai_khoan_id INTEGER REFERENCES tai_khoan(id),
    khach_hang_id INTEGER,
    cau_hinh_ai_id INTEGER,
    tieu_de VARCHAR(255),
    muc_dich VARCHAR(30) NOT NULL CHECK (muc_dich IN ('TRO_LY_NOI_BO','TU_VAN_SACH','TIM_KIEM','HO_TRO_KHACH_HANG')),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAT_DONG' CHECK (trang_thai IN ('HOAT_DONG','DA_DONG','DA_XOA')),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,cau_hinh_ai_id) REFERENCES cau_hinh_ai(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS tin_nhan_ai (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    hoi_thoai_id BIGINT NOT NULL,
    vai_tro VARCHAR(20) NOT NULL CHECK (vai_tro IN ('SYSTEM','USER','ASSISTANT','TOOL')),
    noi_dung TEXT NOT NULL,
    ten_cong_cu VARCHAR(100),
    du_lieu_cong_cu JSONB,
    token_dau_vao INTEGER NOT NULL DEFAULT 0 CHECK (token_dau_vao >= 0),
    token_dau_ra INTEGER NOT NULL DEFAULT 0 CHECK (token_dau_ra >= 0),
    chi_phi_uoc_tinh NUMERIC(18,8) NOT NULL DEFAULT 0 CHECK (chi_phi_uoc_tinh >= 0),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAN_TAT' CHECK (trang_thai IN ('DANG_TAO','HOAN_TAT','THAT_BAI','DA_HUY')),
    loi_xu_ly TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (don_vi_id,id),
    FOREIGN KEY (don_vi_id,hoi_thoai_id) REFERENCES hoi_thoai_ai(don_vi_id,id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tin_nhan_ai_hoi_thoai ON tin_nhan_ai(don_vi_id,hoi_thoai_id,ngay_tao,id);
CREATE TABLE IF NOT EXISTS trich_dan_ai (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    tin_nhan_ai_id BIGINT NOT NULL,
    doan_du_lieu_ai_id BIGINT,
    loai_nguon VARCHAR(30),
    doi_tuong_id BIGINT,
    tieu_de VARCHAR(500),
    duong_dan TEXT,
    do_tuong_dong NUMERIC(6,5) CHECK (do_tuong_dong BETWEEN 0 AND 1),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,tin_nhan_ai_id) REFERENCES tin_nhan_ai(don_vi_id,id),
    FOREIGN KEY (doan_du_lieu_ai_id) REFERENCES doan_du_lieu_ai(id)
);
CREATE TABLE IF NOT EXISTS goi_y_sach_ai (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    khach_hang_id INTEGER,
    tai_khoan_id INTEGER REFERENCES tai_khoan(id),
    phien_ban_sach_id INTEGER NOT NULL REFERENCES phien_ban_sach(id),
    diem_goi_y NUMERIC(8,6) CHECK (diem_goi_y BETWEEN 0 AND 1),
    ly_do TEXT,
    phien_ban_mo_hinh VARCHAR(150),
    ngu_canh JSONB NOT NULL DEFAULT '{}'::jsonb,
    ngay_het_han TIMESTAMPTZ,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id)
);
CREATE TABLE IF NOT EXISTS phan_hoi_ai (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    tin_nhan_ai_id BIGINT,
    goi_y_sach_ai_id BIGINT,
    tai_khoan_id INTEGER REFERENCES tai_khoan(id),
    khach_hang_id INTEGER,
    danh_gia VARCHAR(20) NOT NULL CHECK (danh_gia IN ('HUU_ICH','KHONG_HUU_ICH','BAO_LOI','KHONG_PHU_HOP')),
    noi_dung TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,tin_nhan_ai_id) REFERENCES tin_nhan_ai(don_vi_id,id),
    FOREIGN KEY (goi_y_sach_ai_id) REFERENCES goi_y_sach_ai(id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    CHECK (tin_nhan_ai_id IS NOT NULL OR goi_y_sach_ai_id IS NOT NULL)
);
CREATE TABLE IF NOT EXISTS nhat_ky_su_dung_ai (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    cau_hinh_ai_id INTEGER,
    tai_khoan_id INTEGER REFERENCES tai_khoan(id),
    khach_hang_id INTEGER,
    hoi_thoai_id BIGINT,
    ma_yeu_cau VARCHAR(150),
    tac_vu VARCHAR(50) NOT NULL,
    token_dau_vao INTEGER NOT NULL DEFAULT 0 CHECK (token_dau_vao >= 0),
    token_dau_ra INTEGER NOT NULL DEFAULT 0 CHECK (token_dau_ra >= 0),
    chi_phi NUMERIC(18,8) NOT NULL DEFAULT 0 CHECK (chi_phi >= 0),
    thoi_gian_xu_ly_ms INTEGER CHECK (thoi_gian_xu_ly_ms >= 0),
    trang_thai VARCHAR(20) NOT NULL CHECK (trang_thai IN ('THANH_CONG','THAT_BAI','DA_HUY')),
    ma_loi VARCHAR(100),
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (don_vi_id,cau_hinh_ai_id) REFERENCES cau_hinh_ai(don_vi_id,id),
    FOREIGN KEY (don_vi_id,khach_hang_id) REFERENCES khach_hang(don_vi_id,id),
    FOREIGN KEY (don_vi_id,hoi_thoai_id) REFERENCES hoi_thoai_ai(don_vi_id,id)
);