BEGIN;


-- =========================================================
-- 1. GIỮ LẠI THÔNG BÁO CŨ TỪ MIGRATION 034
-- =========================================================

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'thong_bao'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'thong_bao_legacy'
    ) THEN

        ALTER TABLE thong_bao
            RENAME TO thong_bao_legacy;

    END IF;
END $$;


-- =========================================================
-- 2. BẢNG SỰ KIỆN THÔNG BÁO
-- =========================================================

CREATE TABLE IF NOT EXISTS thong_bao_su_kien (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    ma_su_kien VARCHAR(180) NOT NULL,
    loai_su_kien VARCHAR(60) NOT NULL,
    doi_tuong_loai VARCHAR(60),
    doi_tuong_id BIGINT,
    tieu_de VARCHAR(300) NOT NULL,
    noi_dung TEXT NOT NULL,
    du_lieu JSONB NOT NULL DEFAULT '{}'::jsonb,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_thong_bao_su_kien_don_vi
        FOREIGN KEY (don_vi_id)
        REFERENCES don_vi(id),

    CONSTRAINT uq_thong_bao_su_kien_ma
        UNIQUE (don_vi_id, ma_su_kien),

    CONSTRAINT ck_thong_bao_su_kien_ma
        CHECK (
            ma_su_kien ~ '^[A-Za-z0-9._:-]{2,180}$'
        ),

    CONSTRAINT ck_thong_bao_su_kien_loai
        CHECK (
            loai_su_kien ~ '^[A-Z0-9_]{2,60}$'
        )
);

CREATE INDEX IF NOT EXISTS idx_thong_bao_su_kien_don_vi_ngay
    ON thong_bao_su_kien (
        don_vi_id,
        ngay_tao DESC
    );

CREATE INDEX IF NOT EXISTS idx_thong_bao_su_kien_doi_tuong
    ON thong_bao_su_kien (
        don_vi_id,
        doi_tuong_loai,
        doi_tuong_id
    );


-- =========================================================
-- 3. THÔNG BÁO
-- =========================================================

CREATE TABLE IF NOT EXISTS thong_bao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    su_kien_id BIGINT NOT NULL,
    tai_khoan_id INTEGER NOT NULL,
    tieu_de VARCHAR(300) NOT NULL,
    noi_dung TEXT NOT NULL,
    du_lieu JSONB NOT NULL DEFAULT '{}'::jsonb,
    trang_thai_doc VARCHAR(20) NOT NULL DEFAULT 'CHUA_DOC',
    ngay_doc TIMESTAMPTZ,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_thong_bao_don_vi
        FOREIGN KEY (don_vi_id)
        REFERENCES don_vi(id),

    CONSTRAINT fk_thong_bao_su_kien
        FOREIGN KEY (su_kien_id)
        REFERENCES thong_bao_su_kien(id),

    CONSTRAINT fk_thong_bao_tai_khoan
        FOREIGN KEY (tai_khoan_id)
        REFERENCES tai_khoan(id),

    CONSTRAINT uq_thong_bao_tai_khoan_su_kien
        UNIQUE (su_kien_id, tai_khoan_id),

    CONSTRAINT ck_thong_bao_trang_thai_doc
        CHECK (
            trang_thai_doc IN (
                'CHUA_DOC',
                'DA_DOC'
            )
        ),

    CONSTRAINT ck_thong_bao_ngay_doc
        CHECK (
            (
                trang_thai_doc = 'CHUA_DOC'
                AND ngay_doc IS NULL
            )
            OR
            (
                trang_thai_doc = 'DA_DOC'
                AND ngay_doc IS NOT NULL
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_thong_bao_tai_khoan_moi
    ON thong_bao (
        don_vi_id,
        tai_khoan_id,
        ngay_tao DESC
    );

CREATE INDEX IF NOT EXISTS idx_thong_bao_chua_doc_moi
    ON thong_bao (
        don_vi_id,
        tai_khoan_id,
        ngay_tao DESC
    )
    WHERE trang_thai_doc = 'CHUA_DOC';


-- =========================================================
-- 4. KÊNH GỬI THÔNG BÁO
-- =========================================================

CREATE TABLE IF NOT EXISTS thong_bao_kenh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thong_bao_id BIGINT NOT NULL,
    kenh VARCHAR(20) NOT NULL,
    dia_chi VARCHAR(254),
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'CHO_GUI',
    so_lan_thu INTEGER NOT NULL DEFAULT 0,
    ngay_gui_cuoi TIMESTAMPTZ,
    ngay_gui_tiep TIMESTAMPTZ,
    loi_cuoi TEXT,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_thong_bao_kenh_thong_bao
        FOREIGN KEY (thong_bao_id)
        REFERENCES thong_bao(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_thong_bao_kenh
        UNIQUE (thong_bao_id, kenh),

    CONSTRAINT ck_thong_bao_kenh
        CHECK (
            kenh IN (
                'IN_APP',
                'EMAIL'
            )
        ),

    CONSTRAINT ck_thong_bao_kenh_trang_thai
        CHECK (
            trang_thai IN (
                'CHO_GUI',
                'DANG_GUI',
                'DA_GUI',
                'THAT_BAI',
                'HUY'
            )
        ),

    CONSTRAINT ck_thong_bao_kenh_so_lan
        CHECK (so_lan_thu >= 0)
);

CREATE INDEX IF NOT EXISTS idx_thong_bao_kenh_xu_ly
    ON thong_bao_kenh (
        trang_thai,
        ngay_gui_tiep,
        ngay_tao
    )
    WHERE trang_thai IN (
        'CHO_GUI',
        'THAT_BAI'
    );


-- =========================================================
-- 5. LỊCH THÔNG BÁO
-- =========================================================

CREATE TABLE IF NOT EXISTS lich_thong_bao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL,
    ma_lich VARCHAR(180) NOT NULL,
    tai_khoan_id INTEGER NOT NULL,
    loai_lich VARCHAR(40) NOT NULL,
    doi_tuong_loai VARCHAR(60) NOT NULL,
    doi_tuong_id BIGINT NOT NULL,
    tieu_de VARCHAR(300) NOT NULL,
    noi_dung TEXT NOT NULL,
    du_lieu JSONB NOT NULL DEFAULT '{}'::jsonb,
    thoi_diem_gui_tiep TIMESTAMPTZ NOT NULL,
    lap_lai_phut INTEGER,
    thoi_diem_ket_thuc TIMESTAMPTZ,
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'HOAT_DONG',
    lan_gui_cuoi TIMESTAMPTZ,
    so_lan_gui INTEGER NOT NULL DEFAULT 0,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT now(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_lich_thong_bao_don_vi
        FOREIGN KEY (don_vi_id)
        REFERENCES don_vi(id),

    CONSTRAINT fk_lich_thong_bao_tai_khoan
        FOREIGN KEY (tai_khoan_id)
        REFERENCES tai_khoan(id),

    CONSTRAINT uq_lich_thong_bao_ma
        UNIQUE (don_vi_id, ma_lich),

    CONSTRAINT ck_lich_thong_bao_ma
        CHECK (
            ma_lich ~ '^[A-Za-z0-9._:-]{2,180}$'
        ),

    CONSTRAINT ck_lich_thong_bao_loai
        CHECK (
            loai_lich ~ '^[A-Z0-9_]{2,40}$'
        ),

    CONSTRAINT ck_lich_thong_bao_trang_thai
        CHECK (
            trang_thai IN (
                'HOAT_DONG',
                'TAM_DUNG',
                'DA_KET_THUC',
                'DA_HUY'
            )
        ),

    CONSTRAINT ck_lich_thong_bao_lap_lai
        CHECK (
            lap_lai_phut IS NULL
            OR lap_lai_phut >= 1
        ),

    CONSTRAINT ck_lich_thong_bao_so_lan
        CHECK (
            so_lan_gui >= 0
        )
);

CREATE INDEX IF NOT EXISTS idx_lich_thong_bao_den_han
    ON lich_thong_bao (
        trang_thai,
        thoi_diem_gui_tiep
    )
    WHERE trang_thai = 'HOAT_DONG';

CREATE INDEX IF NOT EXISTS idx_lich_thong_bao_doi_tuong
    ON lich_thong_bao (
        don_vi_id,
        doi_tuong_loai,
        doi_tuong_id,
        trang_thai
    );


-- =========================================================
-- 6. LOG GỬI THÔNG BÁO
-- =========================================================

CREATE TABLE IF NOT EXISTS thong_bao_kenh_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thong_bao_kenh_id BIGINT NOT NULL,
    lan_thu INTEGER NOT NULL,
    trang_thai VARCHAR(20) NOT NULL,
    loi TEXT,
    thoi_gian TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_thong_bao_kenh_log_kenh
        FOREIGN KEY (thong_bao_kenh_id)
        REFERENCES thong_bao_kenh(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_thong_bao_kenh_log_lan
        CHECK (lan_thu >= 1),

    CONSTRAINT ck_thong_bao_kenh_log_trang_thai
        CHECK (
            trang_thai IN (
                'DA_GUI',
                'THAT_BAI'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_thong_bao_kenh_log
    ON thong_bao_kenh_log (
        thong_bao_kenh_id,
        thoi_gian DESC
    );


COMMIT;