CREATE TABLE dang_ky_cho_xac_minh (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten VARCHAR(200) NOT NULL,
    email VARCHAR(254) NOT NULL,
    ten_dang_nhap VARCHAR(40) NOT NULL,
    so_dien_thoai VARCHAR(30) NOT NULL,
    mat_khau_bam TEXT NOT NULL,
    otp_bam CHAR(64) NOT NULL,
    otp_het_han TIMESTAMPTZ NOT NULL,
    otp_ngay_gui_cuoi TIMESTAMPTZ NOT NULL,
    otp_so_lan_thu SMALLINT NOT NULL DEFAULT 0,
    otp_so_lan_gui SMALLINT NOT NULL DEFAULT 1,
    token_tiep_tuc_bam CHAR(64) NOT NULL UNIQUE,
    token_tiep_tuc_het_han TIMESTAMPTZ NOT NULL,
    ngay_tao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_dang_ky_otp_so_lan CHECK (otp_so_lan_thu >= 0 AND otp_so_lan_gui >= 1)
);

CREATE UNIQUE INDEX uq_dkcx_email ON dang_ky_cho_xac_minh (LOWER(email));
CREATE UNIQUE INDEX uq_dkcx_ten_dang_nhap ON dang_ky_cho_xac_minh (LOWER(ten_dang_nhap));
CREATE UNIQUE INDEX uq_dkcx_so_dien_thoai ON dang_ky_cho_xac_minh (so_dien_thoai);