const { Router } = require('express');
const { authenticate } = require('../../common/middlewares/authenticate.js');
const { tenantScope } = require('../../common/middlewares/tenant-scope.js');
const { authorize } = require('../../common/middlewares/authorize.js');
const controller = require('./don-hang.controller.js');
const router = Router();
router.get('/cua-toi', authenticate, controller.xuLy('danhSachCuaToi'));
router.get('/cua-toi/:donHangId', authenticate, controller.xuLy('chiTietCuaToi'));
router.use(authenticate, tenantScope);
router.get('/', authorize('orders.read'), controller.xuLy('danhSach'));
router.post('/', authorize('orders.manage'), controller.xuLy('tao', 201));
router.get('/:donHangId', authorize('orders.read'), controller.xuLy('chiTiet'));
router.post('/:donHangId/trang-thai', authorize('orders.manage'), controller.xuLy('doiTrangThai'));
module.exports = router;